//! pax.sty — PDF annotation extractor (extends `\includegraphics`
//! to fold in hyperlinks/annotations from PAX-format sidecar
//! files generated by the bundled pax.jar processor).
//!
//! pax.sty checks `\ifpdf` and `\PackageError`s out with
//! "Missing pdfTeX in PDF mode" when not running under
//! pdfTeX/lualatex. Our engine is neither, so the raw-load
//! always errors. Perl LaTeXML has no pax binding (default
//! `INCLUDE_STYLES=false` skips the raw .sty entirely).
//!
//! Witness arXiv:1512.06235 — loads `\usepackage{pax}` for PDF
//! annotation extraction (only meaningful in PDF output).
//!
//! Stub the package as a no-op shell. Our `\includegraphics`
//! already works without pax's PAX-file overlay.
use latexml_package::prelude::*;

LoadDefinitions!({
  Warn!(
    "missing_file",
    "pax.sty",
    "pax.sty is a no-op stub — PDF-annotation overlay is meaningless in HTML output."
  );
});
