//! svproc.cls (Springer Proceedings template, sister of svjour/svmult).
//!
//! Base = `article` + `sv_support` (Springer support), mirroring Perl's
//! svjour.cls.ltxml / svmult.cls.ltxml which both
//! `RequirePackage('sv_support')`. sv_support pulls inst_support + natbib
//! and provides the Springer frontmatter (`\email`/`\keywords`/`\institute`)
//! plus `\spnewtheorem` and the standard theorem set — so we do NOT need
//! OmniBus (its last-resort grab-bag) nor an eager amsthm preload. See
//! WISDOM #55. The paper's own `\usepackage{amsthm}` (if any) is then the
//! first real amsthm load, so the `\let\proof\relax` idiom works (witness
//! 1707.03222 {proof}).
use latexml_package::prelude::*;


LoadDefinitions!({
  LoadClass!("article");
  RequirePackage!("sv_support");
  RequirePackage!("amsmath");
  // Pre-load xcolor with [dvipsnames, table] so a paper's later
  // `\usepackage[table]{xcolor}` doesn't silently option-clash and
  // leave colortbl unloaded → `\cellcolor` undefined. svproc.cls
  // itself does NOT load xcolor (only uses the kernel `\normalcolor`),
  // so in Perl the user's `[table]{xcolor}` is the first load and
  // colortbl comes in via the `table` option; matching that outcome
  // here. Same anti-clash pattern as mnras_cls / quantumarticle_cls.
  // Witness: 1706.04315, 1804.09301, 1807.04749 ("undefined:\\cellcolor").
  RequirePackage!("xcolor", options => vec!["dvipsnames".to_string(), "table".to_string()]);
  RequirePackage!("hyperref");
  // svproc.cls L1387-1466 inlines the full standard AAS journal-abbreviation
  // set (`\newcommand*\apj{ApJ}`, `\aj`, `\mnras`, `\sovast`, … — 79 macros,
  // the same set as aas_macros.sty). Bibliographies generated by AAS/natbib
  // bst styles emit these directly in `\bibitem` text. Our binding intercepts
  // svproc.cls, so those inline defs never run; mirror them via aas_macros
  // (which Perl-faithfully wraps each as `\ref@jnl{…}`). Without this,
  // `\apj`/`\sovast` are undefined where Perl (which raw-loads the bundled
  // svproc.cls) is clean. Witness 2110.04152 (`\apj`, `\sovast` in thebibliography).
  RequirePackage!("aas_macros");

  // svproc.cls L864: \newtoks\tocauthor / \toctitle for TOC entries.
  // Preserve author content as ltx:note.
  DefMacro!("\\tocauthor{}",
    "\\@add@frontmatter{ltx:note}[role=tocauthor]{#1}");
  DefMacro!("\\toctitle{}",
    "\\@add@frontmatter{ltx:note}[role=toctitle]{#1}");
  DefMacro!("\\institute{}",
    "\\@add@frontmatter{ltx:note}[role=institute]{#1}");
  // \inst{N} is a superscript marker keyed to numbered affiliations.
  DefMacro!("\\inst{}", "\\textsuperscript{#1}");
  // svproc.cls L240-245 defines \frontmatter / \mainmatter / \backmatter as
  // page-numbering + \@mainmatter-flag toggles (`\pagenumbering{Roman}` etc.).
  // All three are pure page-layout — moot in our HTML paradigm — so Perl
  // (which raw-loads svproc.cls and runs them) produces no visible output for
  // them. Our binding intercepts svproc.cls, so the raw defs never run;
  // `\mainmatter` was already stubbed but `\frontmatter`/`\backmatter` were
  // left undefined where Perl is clean. No-op all three (matching their net
  // HTML effect). Witness 1902.03320 (`\documentclass{svproc}`, `\frontmatter`).
  def_macro_noop("\\frontmatter")?;
  def_macro_noop("\\mainmatter")?;
  def_macro_noop("\\backmatter")?;
});
