//! Versioned dump filename conventions and ambient-TeXLive detection.
//!
//! All kernel dumps generated by `--init=plain.tex` and `--init=latex.ltx`
//! are tagged with the TeXLive release year of the ambient install:
//!
//! ```text
//! resources/dumps/plain.2025.dump.txt
//! resources/dumps/latex.2025.dump.txt
//! resources/dumps/texlive.2025.version
//! ```
//!
//! At runtime we detect the ambient year (via the `kpsewhich --version` /
//! `kpsewhich -var-value=SELFAUTOPARENT` banners, with `pdflatex --version`
//! as fallback — see [`detect_ambient_texlive_year`]) and pick the matching
//! dump. If no exact match exists — or no TeXLive is installed at all — we
//! fall back to the most-recent year present.
//!
//! Why versioned: `latex.dump.txt` content reflects whatever raw `latex.ltx`
//! / `expl3-code.tex` shipped with the ambient TeXLive at `--init` time.
//! Cross-loading a dump from a different TL into a different TL silently
//! diverges. Tagging by year makes the relationship explicit and lets us
//! bundle multiple TL years into a single binary (see
//! [`embedded_dumps`](crate::embedded_dumps)).

use std::{
  path::{Path, PathBuf},
  sync::OnceLock,
};

/// Detect the ambient TeXLive release year. Returns `None` if no TeXLive
/// is installed (or detection fails for some other reason).
///
/// Strategy (ordered for one-subprocess-per-distro; see the body for the
/// spawn-cost rationale):
///   1. `kpsewhich --version` → MiKTeX prints `MiKTeX YY.MM` → `20YY` (TeX Live
///      has no year here and falls through).
///   2. `kpsewhich -var-value=SELFAUTOPARENT` → e.g. `/usr/local/texlive/2025`. Last path
///      component, if it parses as a 4-digit year (2000..=2099), wins.
///   3. `pdflatex --version` → first line typically contains `(TeX Live YYYY)`.
pub fn detect_ambient_texlive_year() -> Option<u32> {
  // Process-global memo. The ambient TeX year is a constant property of the
  // installed distribution — it cannot change mid-process — but detection is
  // called from several sites per conversion (plain/latex dump load, ini), and
  // each site spawns a probe subprocess. On MiKTeX those subprocesses are
  // ~340ms EACH (~10-25x TeX Live's), so an unmemoized detect cost ~0.7s PER
  // call site — the dominant Windows/MiKTeX slowdown (the "load" before the
  // first dump_reader log). Detect once. Thread-safe: the year is
  // process-level, not per-thread State.
  static AMBIENT_TEXLIVE_YEAR: OnceLock<Option<u32>> = OnceLock::new();
  *AMBIENT_TEXLIVE_YEAR.get_or_init(|| {
    // Probe order is chosen so EACH distribution resolves in a single
    // subprocess (the spawn is the whole cost — ~340ms on MiKTeX):
    //   1. `kpsewhich --version` banner. MiKTeX prints `MiKTeX YY.MM` on stdout
    //      → `20YY`, and this is MiKTeX's ONLY single-spawn year signal
    //      (SELFAUTOPARENT is empty there, so step 2 can't help it). Resolving
    //      here saves MiKTeX the extra `pdflatex --version` spawn. TeX Live's
    //      banner is `kpathsea version 6.4.x` (no year) so it returns None — but
    //      only costs ~28ms on TeX Live, so the extra probe is effectively free.
    //   2. `kpsewhich -var-value=SELFAUTOPARENT` → `.../texlive/2026`: TeX Live's
    //      fast path (MiKTeX already exited at step 1).
    //   3. `pdflatex --version`: last-resort fallback for exotic setups where
    //      neither kpsewhich signal carries a year.
    // Answer-identical to a SELFAUTOPARENT-first order on both distros; just
    // fewer spawns (MiKTeX: 2 → 1).
    if let Some(year) = year_from_kpsewhich_version_banner() {
      return Some(year);
    }
    if let Some(year) = year_from_kpsewhich_selfautoparent() {
      return Some(year);
    }
    year_from_pdflatex_version()
  })
}

/// The ambient `kpsewhich --version` banner, memoized ONCE per process in
/// `latexml_core` — the lowest crate that spawns kpsewhich, shared with the
/// kpathsea backend selection (`select_kpaths`), so the whole process spawns
/// `kpsewhich --version` at most once across backend-choice and year detection
/// (the year-based dump staleness check consumes that detected year — it does
/// not read this banner itself). Thin re-export for this crate's consumers.
/// Returns `None` if kpsewhich is absent or the call fails.
pub fn ambient_kpsewhich_version() -> Option<&'static str> {
  latexml_core::util::pathname::ambient_kpsewhich_version()
}

/// Year from the memoized `kpsewhich --version` banner. Only MiKTeX carries a
/// year here (`MiKTeX YY.MM` on stdout, e.g. `MiKTeX 25.12` → 2025); TeX Live
/// prints `kpathsea version 6.4.x` (no year) and so returns `None`, deferring
/// to SELFAUTOPARENT. Reuses [`parse_year_from_version_banner`] — the same
/// extractor as the `pdflatex --version` fallback, which also handles a
/// leading MiKTeX "check for updates" warning line without a false match.
fn year_from_kpsewhich_version_banner() -> Option<u32> {
  parse_year_from_version_banner(ambient_kpsewhich_version()?)
}

fn year_from_kpsewhich_selfautoparent() -> Option<u32> {
  let out = std::process::Command::new("kpsewhich")
    .arg("-var-value=SELFAUTOPARENT")
    .output()
    .ok()?;
  if !out.status.success() {
    return None;
  }
  let s = String::from_utf8(out.stdout).ok()?;
  let trimmed = s.trim();
  let last = Path::new(trimmed).file_name()?.to_str()?;
  parse_year_str(last)
}

fn year_from_pdflatex_version() -> Option<u32> {
  let out = std::process::Command::new("pdflatex")
    .arg("--version")
    .output()
    .ok()?;
  if !out.status.success() {
    return None;
  }
  let s = String::from_utf8(out.stdout).ok()?;
  parse_year_from_version_banner(&s)
}

/// Extract a TL-equivalent year from a `pdflatex --version` banner.
///
///   - TeX Live: first lines contain `(TeX Live YYYY)`.
///   - MiKTeX: no TL year exists anywhere (and `SELFAUTOPARENT` is EMPTY on
///     MiKTeX, so detection lands here). The banner reads
///     `MiKTeX-pdfTeX 4.23 (MiKTeX 25.12)`; MiKTeX is a rolling release
///     whose `YY.MM` package snapshot tracks the same-year TeX Live, so map
///     `MiKTeX YY.*` → `20YY` and let dump resolution do its usual
///     nearest/most-recent fallback if that exact year isn't bundled.
fn parse_year_from_version_banner(s: &str) -> Option<u32> {
  for line in s.lines().take(3) {
    if let Some(idx) = line.find("TeX Live ") {
      let tail = &line[idx + "TeX Live ".len()..];
      let candidate: String = tail.chars().take(4).collect();
      if let Some(y) = parse_year_str(&candidate) {
        return Some(y);
      }
    }
    // Match the parenthesized distro stamp, not the product prefix: the
    // banner starts `MiKTeX-pdfTeX 4.23 (MiKTeX 25.12)` and only the
    // second occurrence carries the version.
    if let Some(idx) = line.find("MiKTeX ") {
      let tail = &line[idx + "MiKTeX ".len()..];
      let digits: String = tail.chars().take_while(char::is_ascii_digit).collect();
      if digits.len() == 2
        && let Ok(yy) = digits.parse::<u32>()
        && (20..=99).contains(&yy)
      {
        return Some(2000 + yy);
      }
    }
  }
  None
}

fn parse_year_str(s: &str) -> Option<u32> {
  // Accept a trailing non-digit suffix: MacTeX/BasicTeX name their TL root
  // with one (e.g. `/usr/local/texlive/2026basic`), so SELFAUTOPARENT's
  // final component carries the year + "basic". Parse the leading digit
  // run; a string that doesn't START with the year (e.g. "texlive") still
  // fails over to the `pdflatex --version` detection.
  let digits = &s[..s.find(|c: char| !c.is_ascii_digit()).unwrap_or(s.len())];
  let y: u32 = digits.parse().ok()?;
  if (2000..=2099).contains(&y) {
    Some(y)
  } else {
    None
  }
}

/// Versioned filename for a kernel dump, e.g.
/// `dump_filename("plain", 2025) == "plain.2025.dump.txt"`.
pub fn dump_filename(kind: &str, year: u32) -> String { format!("{}.{}.dump.txt", kind, year) }

/// One-shot stderr banner emitted by the `LoadFormat` branches in
/// `tex.rs` / `latex.rs` when NO precompiled kernel dump is available
/// and the engine falls back to the raw `latex.ltx` + `expl3-code.tex`
/// load path.
///
/// Why this exists: the raw-load path hits known raw-load-ONLY cascades
/// (the `expl3-code.tex` L33075 codepoint dangling-group and the
/// `\@expl@pop@filename@@` expl-status desync) that the dump avoids. On
/// expl3-heavy arXiv articles this inflates per-paper error counts by
/// ~1000× (2112.11932: 1 → 1003; 2110.10227: 4 → 102), which previously
/// masqueraded as a Rust parity gap when it was really a missing-dump
/// SETUP error (`resources/dumps/` not populated — run
/// `tools/make_formats.sh`). The dump is a required kernel piece for
/// canvas/parity work, so its absence must never be silent.
///
/// Fires at most once per process (shared `Once`), and is a plain stderr
/// line — NOT an `Error:`/`Fatal:` (those are reserved for the per-paper
/// conversion log and would corrupt canvas error counts).
pub fn warn_degraded_no_dump() {
  static WARNED: std::sync::Once = std::sync::Once::new();
  WARNED.call_once(|| {
    let year = detect_ambient_texlive_year()
      .map(|y| y.to_string())
      .unwrap_or_else(|| "unknown".into());
    eprintln!(
      "[latexml-oxide] WARNING: no precompiled kernel dump found (TL{year}); \
       running in DEGRADED raw-load mode. Conversions will show many spurious \
       errors (expl3 catcode/group cascades). Build the dump with \
       `tools/make_formats.sh` before canvas/parity runs. (Set \
       LATEXML_NODUMP=1 to silence this if the raw path is intentional.)"
    );
  });
}

/// Versioned filename for the texlive stamp, e.g.
/// `version_filename(2025) == "texlive.2025.version"`.
pub fn version_filename(year: u32) -> String { format!("texlive.{}.version", year) }

/// Reverse of [`dump_filename`]: extract the year tag from a versioned
/// dump filename. Returns `None` for un-versioned legacy names.
pub fn parse_year_from_dump_filename(name: &str, kind: &str) -> Option<u32> {
  let prefix = format!("{}.", kind);
  let rest = name.strip_prefix(&prefix)?;
  let year_str = rest.strip_suffix(".dump.txt")?;
  parse_year_str(year_str)
}

/// The files a format dump is built from: `plain.tex`, or `latex.ltx` and the L3 kernel it loads
/// (`expl3-code.tex`, whose date `expl3.sty` checks against the format's, expl3.sty:64-78) — each
/// with the tree subpath it is looked up by. kpathsea searches `.` first, and the subpath keeps a
/// document's own copy (`./expl3-code.tex`) from standing for the tree's: kpathsea matches a
/// directory part as a suffix of the tree's directories.
pub fn format_sources(kind: &str) -> &'static [(&'static str, &'static str)] {
  if kind == "latex" {
    &[
      ("latex.ltx", "base/latex.ltx"),
      ("expl3-code.tex", "l3kernel/expl3-code.tex"),
    ]
  } else {
    &[("plain.tex", "plain/base/plain.tex")]
  }
}

/// One format source as a dump records it (`# source` header lines) and a TeX tree resolves it: its
/// name, size and CRC-32, and the path it was read from (informative: two trees holding the same
/// file agree). CRC-32 as the zip format sums files (`flate2::Crc`): a change detector, cheap enough
/// for every process to sum the 2 MB of `latex.ltx` and `expl3-code.tex` it starts from.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SourceStamp {
  pub name:     String,
  pub bytes:    u64,
  pub checksum: u32,
  pub path:     String,
}

const SOURCE_HEADER: &str = "# source\t";

impl SourceStamp {
  /// The stamp of the file at `path`, `None` when it cannot be read.
  pub fn of_file(name: &str, path: &str) -> Option<SourceStamp> {
    let data = std::fs::read(path).ok()?;
    Some(SourceStamp {
      name:     name.to_string(),
      bytes:    data.len() as u64,
      checksum: crc32(&data),
      path:     path.to_string(),
    })
  }

  /// The dump header line recording this stamp.
  pub fn header_line(&self) -> String {
    format!(
      "{SOURCE_HEADER}{}\t{}\t{:08x}\t{}",
      self.name, self.bytes, self.checksum, self.path
    )
  }

  fn parse_header_line(line: &str) -> Option<SourceStamp> {
    let mut fields = line.strip_prefix(SOURCE_HEADER)?.split('\t');
    Some(SourceStamp {
      name:     fields.next()?.to_string(),
      bytes:    fields.next()?.parse().ok()?,
      checksum: u32::from_str_radix(fields.next()?, 16).ok()?,
      path:     fields.next().unwrap_or_default().to_string(),
    })
  }

  fn same_file(&self, other: &SourceStamp) -> bool {
    self.name == other.name && self.bytes == other.bytes && self.checksum == other.checksum
  }
}

fn crc32(data: &[u8]) -> u32 {
  let mut crc = flate2::Crc::new();
  crc.update(data);
  crc.sum()
}

/// The format sources as this process's TeX tree resolves them, through the same kpathsea lookup
/// raw files load through; `None` when it resolves no `plain.tex`/`latex.ltx` (no TeX tree, so
/// nothing a dump could disagree with). Once per process: the tree does not change under it. The
/// lookups wait for kpathsea's tables to be warm (`prewarm_kpathsea`, which a session runs before its
/// first lookup anyway), so a file the tree has is not taken for missing — a missing `latex.ltx`
/// would let every dump pass.
pub fn runtime_source_stamps(kind: &str) -> Option<&'static [SourceStamp]> {
  static PLAIN: OnceLock<Option<Vec<SourceStamp>>> = OnceLock::new();
  static LATEX: OnceLock<Option<Vec<SourceStamp>>> = OnceLock::new();
  let cell = if kind == "latex" { &LATEX } else { &PLAIN };
  cell
    .get_or_init(|| {
      latexml_core::util::pathname::prewarm_kpathsea();
      let mut stamps = Vec::new();
      for (index, (name, query)) in format_sources(kind).iter().enumerate() {
        match latexml_core::util::pathname::kpsewhich(&[query]) {
          Some(path) => stamps.push(SourceStamp::of_file(name, &path)?),
          None if index == 0 => return None,
          None => {},
        }
      }
      Some(stamps)
    })
    .as_deref()
}

/// The source stamps a dump's header records, none for a dump written before dumps recorded them.
pub fn recorded_source_stamps(header: &str) -> Vec<SourceStamp> {
  header
    .lines()
    .take_while(|line| line.starts_with('#'))
    .filter_map(SourceStamp::parse_header_line)
    .collect()
}

/// Whether a dump (its header, or its whole text) was built from the format sources this TeX tree
/// has. A dump is the format, and a format built from one tree is wrong for another's packages:
/// `expl3.sty` refuses a format whose L3 kernel date differs from its own ("Mismatched LaTeX
/// support files", expl3.sty:64-78) — the 2609 release, whose dump was built from
/// `/usr/local/texlive/2025` and read with `/usr/share/texlive`'s packages, had 12,144 papers end
/// as Error (witnesses 2607.28725, 2609.40175). With no TeX tree there is nothing to disagree with; a dump that records no sources
/// cannot show that it matches.
pub fn dump_matches_tree(kind: &str, header: &str) -> bool {
  let Some(runtime) = runtime_source_stamps(kind) else {
    return true;
  };
  let recorded = recorded_source_stamps(header);
  recorded.len() == runtime.len()
    && runtime
      .iter()
      .all(|stamp| recorded.iter().any(|dumped| dumped.same_file(stamp)))
}

/// [`dump_matches_tree`] for the dump file at `path`, reading only its header. A dump built from
/// another tree is passed over, noted once per path.
pub fn dump_file_matches_tree(path: &Path, kind: &str) -> bool {
  use std::io::BufRead;
  let Ok(file) = std::fs::File::open(path) else {
    return false;
  };
  let header: String = std::io::BufReader::new(file)
    .lines()
    .map_while(Result::ok)
    .take_while(|line| line.starts_with('#'))
    .map(|line| line + "\n")
    .collect();
  let matches = dump_matches_tree(kind, &header);
  if !matches {
    note_other_tree_dump(&path.display().to_string(), kind, &header);
  }
  matches
}

/// Notes, once per dump, a dump passed over because it was built from another TeX tree, naming
/// the files that differ. (Format loading precedes a conversion's log, so the note goes to stderr
/// with the other format-load messages.)
pub fn note_other_tree_dump(label: &str, kind: &str, header: &str) {
  static NOTED: std::sync::Mutex<Vec<String>> = std::sync::Mutex::new(Vec::new());
  if let Ok(mut noted) = NOTED.lock() {
    if noted.iter().any(|seen| seen == label) {
      return;
    }
    noted.push(label.to_string());
  }
  let recorded = recorded_source_stamps(header);
  let runtime = runtime_source_stamps(kind).unwrap_or_default();
  let differing: Vec<String> = runtime
    .iter()
    .filter(|stamp| !recorded.iter().any(|dumped| dumped.same_file(stamp)))
    .map(|stamp| {
      let built_from = recorded
        .iter()
        .find(|dumped| dumped.name == stamp.name)
        .map_or("no record", |dumped| dumped.path.as_str());
      format!(
        "{} (built from {built_from}; this tree has {})",
        stamp.name, stamp.path
      )
    })
    .collect();
  let differing = if differing.is_empty() {
    String::from("a different set of format files")
  } else {
    differing.join(", ")
  };
  latexml_core::Info!(
    "dump",
    "other_tree",
    format!("{kind} dump {label} was built from another TeX tree: {differing}; not used")
  );
}

/// `LATEXML_DUMP_DIR_ONLY`: the dumps are looked for in `LATEXML_DUMP_PATH`/`LATEXML_DUMP_DIR` and
/// among those built for this tree only — not beside the executable, in the source tree, or
/// embedded — so an operator (or a test) can see that a dump comes from where they put it.
pub fn dump_dir_only() -> bool {
  static ONLY: OnceLock<bool> = OnceLock::new();
  *ONLY.get_or_init(|| std::env::var_os("LATEXML_DUMP_DIR_ONLY").is_some())
}

/// The format dumps built for this TeX tree (`latexml::format_dumps`), with their years, used
/// before every other dump location.
static REBUILT_PLAIN_DUMP: OnceLock<(PathBuf, u32)> = OnceLock::new();
static REBUILT_LATEX_DUMP: OnceLock<(PathBuf, u32)> = OnceLock::new();

fn rebuilt_dump_cell(kind: &str) -> &'static OnceLock<(PathBuf, u32)> {
  if kind == "latex" {
    &REBUILT_LATEX_DUMP
  } else {
    &REBUILT_PLAIN_DUMP
  }
}

/// Records the `kind` dump built for this TeX tree, once per process.
pub fn set_rebuilt_dump(kind: &str, path: PathBuf, year: u32) {
  let _ = rebuilt_dump_cell(kind).set((path, year));
}

/// [`set_rebuilt_dump`]'s `kind` dump, if one was built or found built.
pub fn rebuilt_dump(kind: &str) -> Option<(PathBuf, u32)> { rebuilt_dump_cell(kind).get().cloned() }

thread_local! {
  /// Set on the thread that builds a format dump in process (`latexml::format_dumps`), as
  /// `LATEXML_INI_MODE` is for `--init`: the format stops after its bootstrap.
  static BUILDING_FORMAT: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
}

/// Marks this thread as building a format dump.
pub fn set_building_format(on: bool) { BUILDING_FORMAT.with(|flag| flag.set(on)); }

/// Whether this thread builds a format dump.
pub fn building_format() -> bool { BUILDING_FORMAT.with(std::cell::Cell::get) }

/// Whether a `kind` dump built from this TeX tree is found where the format would load one from.
pub fn format_dump_available(kind: &str) -> bool {
  if kind == "latex" {
    crate::latex::latex_dump_available()
  } else {
    crate::plain_dump::plain_dump_available()
  }
}

/// All TL years for which a `<kind>.YYYY.dump.txt` file exists in `dir`,
/// sorted descending (most-recent first).
pub fn available_years_in_dir(dir: &Path, kind: &str) -> Vec<u32> {
  let mut years = Vec::new();
  let Ok(entries) = std::fs::read_dir(dir) else {
    return years;
  };
  for entry in entries.flatten() {
    let name = entry.file_name();
    let Some(name_str) = name.to_str() else {
      continue;
    };
    if let Some(y) = parse_year_from_dump_filename(name_str, kind) {
      years.push(y);
    }
  }
  years.sort_unstable_by(|a, b| b.cmp(a));
  years.dedup();
  years
}

/// Pick the best dump in `dir` for the given `kind` (`"plain"` /
/// `"latex"`):
///   - if `prefer` is `Some(y)` and `<kind>.y.dump.txt` exists, use it;
///   - else use the most-recent year present;
///   - else `None`.
///
/// A dump built from another TeX tree than this one ([`dump_file_matches_tree`]) is passed over.
pub fn resolve_versioned_in_dir(
  dir: &Path,
  kind: &str,
  prefer: Option<u32>,
) -> Option<(PathBuf, u32)> {
  let mut years = available_years_in_dir(dir, kind);
  if let Some(y) = prefer
    && let Some(index) = years.iter().position(|year| *year == y)
  {
    years.remove(index);
    years.insert(0, y);
  }
  years
    .into_iter()
    .map(|year| (dir.join(dump_filename(kind, year)), year))
    .find(|(path, _)| dump_file_matches_tree(path, kind))
}

/// Sibling stamp file for a dump path — e.g. `texlive.2025.version`
/// next to `latex.2025.dump.txt`.
pub fn stamp_path_for_dump(dump_path: &Path, year: u32) -> Option<PathBuf> {
  Some(dump_path.parent()?.join(version_filename(year)))
}

/// Staleness check for a loaded kernel dump, at TeX-Live-**year** granularity.
///
/// The dump is year-versioned (`latex.YYYY.dump.txt`) and selected by the
/// ambient TeX Live year, so the unit that decides whether the dump's macro set
/// matches the installation is the **year**, not the kpathsea patch level. An
/// earlier version compared the exact `kpathsea version X.Y.Z` stamp strings and
/// warned on a within-year patch bump — e.g. the release-build container's
/// `6.4.1` vs a user's shipped-TL2026 `6.4.2` — even though both are TL2026 with
/// the same macros. That was a false positive (issue #299). The kpathsea string
/// is also not a reliable cross-year discriminator (TL2023 and TL2025 report the
/// same string), so we never compare stamps directly.
///
/// Returns `Some(message)` to warn, `None` to stay silent. Warns **only** when
/// `ambient_year` is known AND differs from the loaded `dump_year` (no dump for
/// the installed TL year was bundled, so we fell back to a different year).
/// Silent when the years match, the ambient year is undetectable, or the dump
/// year is unknown (`0`).
///
/// `from_embedded` distinguishes the shipped standalone binary (embedded dump —
/// a user cannot regenerate it and has no `tools/` tree) from the dev/on-disk
/// tree (where regenerating the local dump is the actionable fix).
pub fn dump_year_mismatch_warning(
  dump_year: u32,
  ambient_year: Option<u32>,
  from_embedded: bool,
) -> Option<String> {
  let ambient = ambient_year?;
  if dump_year == 0 || ambient == dump_year {
    return None;
  }
  let detail = if from_embedded {
    // Standalone-binary user: no source tree, and the embedded dump can't be
    // regenerated — upgrading the binary (or setting the env var) is the honest
    // advice. Do NOT reference `tools/make_formats.sh` (issue #299).
    format!(
      ", and this binary bundles no TL{ambient} dump. A few macros may differ; \
       conversions use the closest bundled year and are usually unaffected. \
       Silence with LATEXML_SKIP_DUMP_STAMP_CHECK=1."
    )
  } else {
    ". A few macros may differ. Run `tools/make_formats.sh` to regenerate the \
     dump against the ambient TeX Live, or silence with \
     LATEXML_SKIP_DUMP_STAMP_CHECK=1."
      .to_string()
  };
  Some(format!(
    "loaded the TL{dump_year} kernel dump, but the ambient TeX Live is \
     {ambient}{detail}"
  ))
}

#[cfg(test)]
mod year_parse_tests {
  use super::{parse_year_from_version_banner, parse_year_str};

  #[test]
  fn texlive_banner() {
    assert_eq!(
      parse_year_from_version_banner("pdfTeX 3.141592653-2.6-1.40.29 (TeX Live 2026)"),
      Some(2026)
    );
    // Homebrew stamp variant.
    assert_eq!(
      parse_year_from_version_banner("pdfTeX 3.14 (TeX Live 2026/Homebrew)"),
      Some(2026)
    );
  }

  #[test]
  fn miktex_banner_maps_rolling_version_to_year() {
    // Verbatim from MiKTeX 25.12 on Windows (probe 2026-07-12); note
    // SELFAUTOPARENT is empty on MiKTeX, so this arm is the only signal.
    assert_eq!(
      parse_year_from_version_banner("MiKTeX-pdfTeX 4.23 (MiKTeX 25.12)"),
      Some(2025)
    );
  }

  #[test]
  fn unknown_banner_rejected() {
    assert_eq!(
      parse_year_from_version_banner("pdfTeX 3.14 (Web2C 2026)"),
      None
    );
    // A hypothetical 3-digit MiKTeX version must not parse as a year.
    assert_eq!(parse_year_from_version_banner("(MiKTeX 125.1)"), None);
  }

  #[test]
  fn vanilla_tl_year() {
    assert_eq!(parse_year_str("2025"), Some(2025));
    assert_eq!(parse_year_str("2026"), Some(2026));
  }

  #[test]
  fn basictex_suffixed_year() {
    // MacTeX/BasicTeX layout: /usr/local/texlive/2026basic
    assert_eq!(parse_year_str("2026basic"), Some(2026));
  }

  #[test]
  fn non_year_components_rejected() {
    assert_eq!(parse_year_str("texlive"), None); // brew Cellar layout
    assert_eq!(parse_year_str("basic2026"), None);
    assert_eq!(parse_year_str(""), None);
    assert_eq!(parse_year_str("1999"), None); // outside the sane range
    assert_eq!(parse_year_str("20269"), None); // 5-digit run is not a year
  }
}

#[cfg(test)]
mod stamp_check_tests {
  use super::dump_year_mismatch_warning;

  // Issue #299: the reporter's exact case — TL2026 dump loaded on a TL2026
  // install. The kpathsea *patch* level differed (6.4.1 build container vs
  // 6.4.2 shipped TL2026) but the YEAR matches, so there is NO macro-set
  // mismatch and the check must stay SILENT.
  #[test]
  fn same_year_is_silent() {
    assert_eq!(dump_year_mismatch_warning(2026, Some(2026), true), None);
    assert_eq!(dump_year_mismatch_warning(2026, Some(2026), false), None);
  }

  // A genuine year mismatch (installed TL year has no bundled dump, so we fell
  // back to a different year) DOES warn — and the standalone-binary message
  // names both years and never points at a `tools/` script the user lacks.
  #[test]
  fn genuine_year_mismatch_warns_without_script_hint() {
    let msg =
      dump_year_mismatch_warning(2022, Some(2019), true).expect("a real year mismatch must warn");
    assert!(msg.contains("2022"), "names the loaded dump year: {msg}");
    assert!(msg.contains("2019"), "names the ambient TL year: {msg}");
    assert!(
      !msg.contains("make_formats"),
      "standalone-binary message must not reference a source-tree script: {msg}"
    );
  }

  // The dev-tree / on-disk path (from_embedded == false) keeps the
  // regenerate-your-local-dump hint, which is actionable there.
  #[test]
  fn dev_tree_mismatch_keeps_regenerate_hint() {
    let msg =
      dump_year_mismatch_warning(2026, Some(2027), false).expect("a real year mismatch must warn");
    assert!(
      msg.contains("make_formats"),
      "dev-tree hint retained: {msg}"
    );
  }

  // No reliable year signal → no warning (fail toward silence, not a spurious
  // kpathsea-string mismatch).
  #[test]
  fn undetectable_ambient_year_is_silent() {
    assert_eq!(dump_year_mismatch_warning(2026, None, true), None);
  }

  // Unknown dump year (0 sentinel) → nothing to compare.
  #[test]
  fn unknown_dump_year_is_silent() {
    assert_eq!(dump_year_mismatch_warning(0, Some(2026), true), None);
  }
}
