//! Versioned dump filename conventions and ambient-TeXLive detection.
//!
//! All kernel dumps generated by `--init=plain.tex` and `--init=latex.ltx`
//! are tagged with the TeXLive release year of the ambient install:
//!
//! ```text
//! resources/dumps/plain.2025.dump.txt
//! resources/dumps/latex.2025.dump.txt
//! resources/dumps/texlive.2025.version
//! ```
//!
//! At runtime we detect the ambient year (via `kpsewhich
//! -var-value=SELFAUTOPARENT`, with `pdflatex --version` as fallback) and
//! pick the matching dump. If no exact match exists — or no TeXLive is
//! installed at all — we fall back to the most-recent year present.
//!
//! Why versioned: `latex.dump.txt` content reflects whatever raw `latex.ltx`
//! / `expl3-code.tex` shipped with the ambient TeXLive at `--init` time.
//! Cross-loading a dump from a different TL into a different TL silently
//! diverges. Tagging by year makes the relationship explicit and lets us
//! bundle multiple TL years into a single binary (see
//! [`embedded_dumps`](crate::embedded_dumps)).

use std::path::{Path, PathBuf};

/// Detect the ambient TeXLive release year. Returns `None` if no TeXLive
/// is installed (or detection fails for some other reason).
///
/// Strategy:
///   1. `kpsewhich -var-value=SELFAUTOPARENT` → e.g. `/usr/local/texlive/2025`.
///      Last path component, if it parses as a 4-digit year (2000..=2099),
///      wins.
///   2. `pdflatex --version` → first line typically contains `(TeX Live YYYY)`.
pub fn detect_ambient_texlive_year() -> Option<u32> {
  if let Some(year) = year_from_kpsewhich_selfautoparent() {
    return Some(year);
  }
  year_from_pdflatex_version()
}

fn year_from_kpsewhich_selfautoparent() -> Option<u32> {
  let out = std::process::Command::new("kpsewhich")
    .arg("-var-value=SELFAUTOPARENT")
    .output()
    .ok()?;
  if !out.status.success() {
    return None;
  }
  let s = String::from_utf8(out.stdout).ok()?;
  let trimmed = s.trim();
  let last = Path::new(trimmed).file_name()?.to_str()?;
  parse_year_str(last)
}

fn year_from_pdflatex_version() -> Option<u32> {
  let out = std::process::Command::new("pdflatex")
    .arg("--version")
    .output()
    .ok()?;
  if !out.status.success() {
    return None;
  }
  let s = String::from_utf8(out.stdout).ok()?;
  // Look for "TeX Live YYYY" in the first few lines.
  for line in s.lines().take(3) {
    if let Some(idx) = line.find("TeX Live ") {
      let tail = &line[idx + "TeX Live ".len()..];
      let candidate: String = tail.chars().take(4).collect();
      if let Some(y) = parse_year_str(&candidate) {
        return Some(y);
      }
    }
  }
  None
}

fn parse_year_str(s: &str) -> Option<u32> {
  // Accept a trailing non-digit suffix: MacTeX/BasicTeX name their TL root
  // with one (e.g. `/usr/local/texlive/2026basic`), so SELFAUTOPARENT's
  // final component carries the year + "basic". Parse the leading digit
  // run; a string that doesn't START with the year (e.g. "texlive") still
  // fails over to the `pdflatex --version` detection.
  let digits = &s[..s.find(|c: char| !c.is_ascii_digit()).unwrap_or(s.len())];
  let y: u32 = digits.parse().ok()?;
  if (2000..=2099).contains(&y) {
    Some(y)
  } else {
    None
  }
}

#[cfg(test)]
mod year_parse_tests {
  use super::parse_year_str;

  #[test]
  fn vanilla_tl_year() {
    assert_eq!(parse_year_str("2025"), Some(2025));
    assert_eq!(parse_year_str("2026"), Some(2026));
  }

  #[test]
  fn basictex_suffixed_year() {
    // MacTeX/BasicTeX layout: /usr/local/texlive/2026basic
    assert_eq!(parse_year_str("2026basic"), Some(2026));
  }

  #[test]
  fn non_year_components_rejected() {
    assert_eq!(parse_year_str("texlive"), None); // brew Cellar layout
    assert_eq!(parse_year_str("basic2026"), None);
    assert_eq!(parse_year_str(""), None);
    assert_eq!(parse_year_str("1999"), None); // outside the sane range
    assert_eq!(parse_year_str("20269"), None); // 5-digit run is not a year
  }
}

/// Versioned filename for a kernel dump, e.g.
/// `dump_filename("plain", 2025) == "plain.2025.dump.txt"`.
pub fn dump_filename(kind: &str, year: u32) -> String {
  format!("{}.{}.dump.txt", kind, year)
}

/// Versioned filename for the texlive stamp, e.g.
/// `version_filename(2025) == "texlive.2025.version"`.
pub fn version_filename(year: u32) -> String {
  format!("texlive.{}.version", year)
}

/// Reverse of [`dump_filename`]: extract the year tag from a versioned
/// dump filename. Returns `None` for un-versioned legacy names.
pub fn parse_year_from_dump_filename(name: &str, kind: &str) -> Option<u32> {
  let prefix = format!("{}.", kind);
  let rest = name.strip_prefix(&prefix)?;
  let year_str = rest.strip_suffix(".dump.txt")?;
  parse_year_str(year_str)
}

/// All TL years for which a `<kind>.YYYY.dump.txt` file exists in `dir`,
/// sorted descending (most-recent first).
pub fn available_years_in_dir(dir: &Path, kind: &str) -> Vec<u32> {
  let mut years = Vec::new();
  let Ok(entries) = std::fs::read_dir(dir) else {
    return years;
  };
  for entry in entries.flatten() {
    let name = entry.file_name();
    let Some(name_str) = name.to_str() else {
      continue;
    };
    if let Some(y) = parse_year_from_dump_filename(name_str, kind) {
      years.push(y);
    }
  }
  years.sort_unstable_by(|a, b| b.cmp(a));
  years.dedup();
  years
}

/// Pick the best dump in `dir` for the given `kind` (`"plain"` /
/// `"latex"`):
///   - if `prefer` is `Some(y)` and `<kind>.y.dump.txt` exists, use it;
///   - else use the most-recent year present;
///   - else `None`.
pub fn resolve_versioned_in_dir(dir: &Path, kind: &str, prefer: Option<u32>) -> Option<(PathBuf, u32)> {
  if let Some(y) = prefer {
    let p = dir.join(dump_filename(kind, y));
    if p.is_file() {
      return Some((p, y));
    }
  }
  let years = available_years_in_dir(dir, kind);
  let chosen = years.first().copied()?;
  Some((dir.join(dump_filename(kind, chosen)), chosen))
}

/// Sibling stamp file for a dump path — e.g. `texlive.2025.version`
/// next to `latex.2025.dump.txt`.
pub fn stamp_path_for_dump(dump_path: &Path, year: u32) -> Option<PathBuf> {
  Some(dump_path.parent()?.join(version_filename(year)))
}
