//! Loading the LaTeX format on demand — the eager trigger list's safety net.
//!
//! `TeX.pool` installs the Perl-faithful autoload triggers (`TeX.pool.ltxml`
//! L33-56: `\documentclass`, `\newcommand`, `\begin`, …), each a macro that
//! expands to `\@load@latex@pool <trigger>`. Those fire *eagerly*, on a
//! legitimate use, before any error is raised — and they stay exactly as Perl
//! writes them.
//!
//! But a curated list is incomplete by construction: real LaTeX has no "before
//! the kernel" (`latex.ltx` *is* the format), so a document may legitimately
//! open with any kernel command. Anything not on the list was simply undefined
//! — stubbed as `<ltx:ERROR/>`, with the document derailing from there. The
//! canonical witness is the "use this class if installed" idiom
//!
//! ```tex
//! \IfFileExists{proc-l.cls}{\documentclass{proc-l}}{\documentclass{amsproc}}
//! ```
//!
//! (arXiv 2605.25877 line 4, 2606.06905, 2606.09693, 2606.16723): with
//! `\IfFileExists` undefined the conditional collapses, *no class is ever
//! selected*, and the run cascades into `Fatal:TooManyErrors`. Same-host Perl
//! LaTeXML fails identically — see `docs/parity/KNOWN_PERL_ERRORS.md`.
//!
//! [`autoload_latex_kernel`] closes the gap generally: registered into
//! `latexml_core::binding::kernel_autoload`, it is consulted at the two
//! undefined-CS paths (gullet `read_x_token`, stomach `invoke_token_undefined`)
//! *instead of* erroring, and answers "is this a LaTeX kernel command?" — if so
//! the format loads and the token is retried. It subsumes the two Rust-only,
//! witness-driven trigger accretions that used to sit in `tex.rs`'s list:
//! `\UseRawInputEncoding` (witness 2403.19280) and `\DocumentMetadata`
//! (witness 2305.08034), which are now just two instances of "a kernel CS used
//! before the format loaded".
//!
//! # The membership oracle is the DUMP, not `latex.ltx`
//!
//! The question that has to be answered *before* committing to a load is "what
//! will be defined **after** `LaTeX.pool` loads?" — because "load it and see if
//! that helped" would drag the kernel into genuinely plain-TeX documents on
//! their first undefined CS.
//!
//! The right oracle for that is `latex.YYYY.dump.txt`, and deliberately **not**
//! the host's `latex.ltx`. The dump is not a "YYYY artifact": it is generated by
//! *our current code* inside a pinned TL-YYYY container, and it is the
//! **executed** result of that bootstrap — the state delta this engine actually
//! reaches. `latex.ltx` is source text, so answering the same question from it
//! would mean re-deciding every `\def` / `\let` / `\csname` / `\@namedef` /
//! `\ifx` in the file, i.e. re-running the load we are trying to avoid. It is
//! also the very artifact `LaTeX.pool` goes on to replay, so a catalogue built
//! from it cannot disagree with what the load installs.
//! **Do not "correct" this to `latex.ltx`.**
//!
//! Only the backward direction exists. A control sequence newer than the
//! ambient dump year is out of scope by design — we cannot predict a TeX Live
//! that has not shipped, and the host TeX Live of that age does not have the
//! command either, so reporting it undefined is correct. There is no
//! forward-compat seam and none is wanted.
//!
//! # Degraded (no-dump) branch
//!
//! `LoadFormat('latex')` has two mutually exclusive branches (CLAUDE.md durable
//! parity rule 1). On the degraded one — `$LATEXML_NODUMP`, or no dump
//! reachable at all — there is no key set to test against, so
//! [`latex_kernel_defines`] is always `false` and this mechanism never fires.
//! Behaviour there is bit-identical to before: the Perl `TeX.pool` L33-56
//! trigger list remains the only mechanism.

use std::cell::OnceCell;

use once_cell::sync::Lazy;
use rustc_hash::FxHashSet;

use crate::prelude::*;

// Process-once cached env var (see WISDOM #56 — getenv hot-path race).
static INI_MODE: Lazy<bool> = Lazy::new(|| std::env::var_os("LATEXML_INI_MODE").is_some());

/// Per-session flag: the kernel autoload has already been attempted.
///
/// Necessary and not redundant with `LaTeX.pool_loaded`, which
/// `input_definitions` only sets *after* the pool body has run — so without
/// this the load could re-enter itself through its own undefined CSes. It is a
/// State value, so it resets with the session (a test binary runs many
/// conversions on one thread) while surviving group pops (assigned globally).
const AUTOLOAD_ATTEMPTED: &str = "LaTeX.pool_autoload_attempted";

thread_local! {
  /// Control-sequence names the ambient kernel dump defines. Built at most once
  /// per process, and only on the cold path below — never at startup, so the
  /// ~161 ms per-process bootstrap is untouched. ~22k boxed names (<1 MB) that
  /// only ever materialise in a session that reached an undefined CS with no
  /// LaTeX format loaded.
  static KERNEL_CS: OnceCell<FxHashSet<Box<str>>> = const { OnceCell::new() };
}

/// Load `LaTeX.pool`, the way the `\@load@latex@pool` trigger primitive does.
///
/// Single definition of "pull the LaTeX format in", shared by that primitive
/// and by [`autoload_latex_kernel`], so the post-load fixups can never diverge
/// between the eager and the on-undefined route.
pub fn load_latex_pool() -> Result<()> {
  input_definitions("LaTeX", InputDefinitionOptions {
    extension: Some(Cow::Borrowed("pool")),
    ..InputDefinitionOptions::default()
  })?;
  // Restore our `\documentstyle` impl after the LaTeX pool load. The
  // latex_dump unconditionally redefines `\documentstyle` to the
  // kernel-style `\input{latex209.def}\documentclass`; in Perl that's
  // overridden by latex_constructs.pool.ltxml's DefConstructor, but
  // our latex_constructs.rs port doesn't redefine it. Re-Let to our
  // backup to win. See tex_job.rs `\lx@documentstyle@impl` for the
  // full diagnostic context (hep-th9912229 witness).
  Let!("\\documentstyle", "\\lx@documentstyle@impl");
  Ok(())
}

/// Does loading `LaTeX.pool` define `cs`? See the module docs for why the
/// ambient kernel dump is the oracle. `false` on the degraded no-dump branch.
pub fn latex_kernel_defines(cs: &str) -> bool {
  KERNEL_CS.with(|cell| cell.get_or_init(build_kernel_catalogue).contains(cs))
}

fn build_kernel_catalogue() -> FxHashSet<Box<str>> {
  // Same resolver `latex_dump::load_definitions` uses (env overrides, ambient
  // year, embedded fallback), so the catalogue can never name a CS from a
  // different dump than the one the pool would load. Key scan only — no record
  // is parsed and no State is touched.
  match crate::latex_dump::resolve_dump_text() {
    Some((content, _label, _year, _from_embedded)) => dump_reader::collect_meaning_keys(&content),
    None => FxHashSet::default(),
  }
}

/// The `latexml_core::binding::kernel_autoload` hook: `true` means the LaTeX
/// format was just loaded *and* `token` now has a meaning, so the caller must
/// retry it; `false` means take the ordinary bounded `Error:undefined` path.
pub fn autoload_latex_kernel(token: &Token) -> bool {
  if token.get_catcode() != Catcode::CS {
    return false;
  }
  // Dump-build (`--init=plain.tex` / `--init=latex.ltx`) raw-loads a format
  // file against a deliberately minimal state and writes the delta. Pulling
  // `LaTeX.pool` in from an undefined CS there would put the whole pool into
  // the snapshot — i.e. a previous run's dump would leak into the next one.
  // The dump must be built from the format file alone.
  if *INI_MODE {
    return false;
  }
  // The caller has declared that undefined CSes in this stretch are expected
  // forward references that later fixups resolve (expl3-code.tex and friends).
  // Acting on one would load the format on a name that is about to be defined
  // anyway. Same gate the undefined-CS `Error!` sites use.
  if lookup_bool("SUPPRESS_UNDEFINED_ERRORS") {
    return false;
  }
  // Once the format is in, the question is moot: the CS is either defined or
  // genuinely undefined.
  if lookup_bool("LaTeX.pool_loaded") {
    return false;
  }
  if lookup_bool(AUTOLOAD_ATTEMPTED) {
    return false;
  }
  if !token.with_cs_name(latex_kernel_defines) {
    return false;
  }
  // Claim the single attempt BEFORE loading. The pool load runs arbitrary
  // definition code that can itself reach an undefined CS, and re-entering
  // here would recurse; a trigger that re-emits itself spins the gullet
  // forever, silently, with no error for `too_many_errors` to cap (witness
  // 2606.21610, see the `def_autoload` closure in `tex.rs`).
  assign_value(AUTOLOAD_ATTEMPTED, true, Some(Scope::Global));
  let cs_name = token.with_cs_name(|cs| cs.to_string());
  Info!(
    "autoload",
    "LaTeX",
    s!("{cs_name} is a LaTeX kernel command — loading LaTeX.pool")
  );
  // Hoist whatever the load installs at the current frame up to global: this
  // can fire at any group depth (unlike the eager triggers, which in practice
  // fire at top level), and definitions popped by the enclosing `}` would
  // leave `LaTeX.pool_loaded` set with the format gone. Same guard
  // `def_autoload` uses in `tex.rs`.
  let pre_keys = snapshot_top_frame_meaning_keys();
  if let Err(e) = load_latex_pool() {
    Warn!(
      "autoload",
      "LaTeX",
      s!("failed to load LaTeX.pool for {cs_name}: {e}")
    );
    return false;
  }
  hoist_top_frame_meaning_delta(&pre_keys);
  // The format may still not define it (e.g. a dump key our own LaTeX pool
  // later clears). Then this was a no-op and the caller reports it undefined,
  // exactly as before.
  has_meaning(token)
}
