//! Precompiled LaTeX kernel dump (auto-generated by build.rs).
//!
//! Embeds the latex.ltx format dump as text data and loads it at runtime
//! via `dump_reader::load_from_str()`. Avoids 350K-line compiled Rust overhead.
//!
//! Regenerated automatically when TeX Live installation changes.
//! Manual regeneration: `cargo clean -p latexml_package && cargo build`

// The loader below is machine-generated by build.rs into $OUT_DIR and `include!`d
// here, so clippy lints its tokens as if hand-written. No human edits it, and
// chasing the generator's emitted control flow per-lint (e.g. collapsible_if)
// is brittle, so exempt this generated module. The hand-written sibling
// `plain_dump.rs` mirrors the same logic and stays fully linted.
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/latex_dump_loader.rs"));
