//! Precompiled LaTeX kernel dump (auto-generated by build.rs).
//!
//! Embeds the latex.ltx format dump as text data and loads it at runtime
//! via `dump_reader::load_from_str()`. Avoids 350K-line compiled Rust overhead.
//!
//! Regenerated automatically when TeX Live installation changes.
//! Manual regeneration: `cargo clean -p latexml_package && cargo build`

include!(concat!(env!("OUT_DIR"), "/latex_dump_loader.rs"));
