var sourcesIndex = JSON.parse('{\
"rtx":["",[["util",[],["test.rs"]]],["converter.rs","core_interface.rs","lib.rs","util.rs"]],\
"rtx_codegen":["",[],["constructable.rs","lib.rs","modelable.rs","parametrizeable.rs","testable.rs","tokenizeable.rs"]],\
"rtx_contrib":["",[],["lib.rs","mytemplate_sty.rs","scopemacro_sty.rs"]],\
"rtx_core":["",[["alignment",[],["template.rs"]],["binding",[["counter",[],["dialect.rs"]],["def",[],["dialect.rs","macros.rs","traits.rs"]]],["content.rs","counter.rs","def.rs"]],["common",[["font",[],["standard_metrics.rs"]]],["arena.rs","cleaners.rs","def_parser.rs","dimension.rs","error.rs","float.rs","font.rs","glue.rs","ligature.rs","locator.rs","model.rs","mudimension.rs","muglue.rs","number.rs","numeric_ops.rs","object.rs","relaxng.rs","store.rs","xml.rs"]],["definition",[],["argument.rs","conditional.rs","constructor.rs","expandable.rs","math_primitive.rs","primitive.rs","register.rs"]],["document",[],["helpers.rs","resource.rs","tag.rs"]],["util",[],["logger.rs","pathname.rs","radix.rs","text.rs"]]],["alignment.rs","aux_macros.rs","binding.rs","comment.rs","common.rs","definition.rs","digested.rs","document.rs","gullet.rs","keyval.rs","keyvals.rs","lib.rs","ligature.rs","list.rs","mouth.rs","parameter.rs","rewrite.rs","state.rs","stomach.rs","tbox.rs","token.rs","tokens.rs","util.rs","whatsit.rs"]],\
"rtx_math_parser":["",[["grammar",[],["builder.rs","macros.rs"]],["semantics",[],["curry.rs","from.rs","metadata.rs","tree.rs"]]],["data.rs","grammar.rs","lib.rs","parser.rs","pragmatics.rs","semantics.rs","syntax.rs","util.rs"]],\
"rtx_package":["",[["package",[],["alltt_sty.rs","amsmath_sty.rs","amsthm_sty.rs","article_cls.rs","cite_sty.rs","comment_sty.rs","etex.rs","etoolbox_sty.rs","fontenc_sty.rs","hyperref_sty.rs","ieeetran_cls.rs","inputenc_sty.rs","latex.rs","latex_ch10_array_and_tabular.rs","latex_ch10_tabbing_environment.rs","latex_ch11_index_and_glossary.rs","latex_ch11_moving_information.rs","latex_ch11_splitting_the_input.rs","latex_ch11_terminal_io.rs","latex_ch12_line_and_page_breaking.rs","latex_ch13_boxes.rs","latex_ch14_pictures_and_color.rs","latex_ch15_font_selection.rs","latex_ch15_special_symbol.rs","latex_ch1_break_command.rs","latex_ch1_documentclass.rs","latex_ch1_environments.rs","latex_ch1_fragile_commands.rs","latex_ch2_document.rs","latex_ch3_sentences_and_paragraphs.rs","latex_ch4_sectioning_and_toc.rs","latex_ch5_packages.rs","latex_ch5_page_styles.rs","latex_ch5_title_page_and_abstract.rs","latex_ch6_displayed_paragraphs.rs","latex_ch6_list_and_trivlist_environments.rs","latex_ch6_list_making_environments.rs","latex_ch6_quotations_and_verse.rs","latex_ch6_verbatim.rs","latex_ch7_math_common_delimiters.rs","latex_ch7_math_common_structures.rs","latex_ch7_math_mode_changing_style.rs","latex_ch7_math_mode_environments.rs","latex_ch8_defining_commands.rs","latex_ch8_defining_environments.rs","latex_ch8_numbering.rs","latex_ch8_theoremlike_environments.rs","latex_ch9_figures_and_tables.rs","latex_ch9_marginal_notes.rs","latex_delimiters.rs","latex_functions.rs","latex_hook.rs","latex_other_in_appendices.rs","latex_semi_undocumented.rs","latex_tables_3.rs","latexml_sty.rs","multido_sty.rs","pdftex.rs","setup_binding_language.rs","t1_fontmap.rs","t1enc_def.rs","t1enc_sty.rs","tex.rs","tex_accents.rs","tex_alignment.rs","tex_appendix_b_p350_to_p355.rs","tex_appendix_b_p356.rs","tex_appendix_b_p357.rs","tex_appendix_b_p358.rs","tex_appendix_b_p359.rs","tex_appendix_b_p360.rs","tex_appendix_b_p361.rs","tex_appendix_b_p362.rs","tex_appendix_b_p363.rs","tex_appendix_b_p364.rs","tex_appendix_b_to_p349.rs","tex_assignment.rs","tex_boxes.rs","tex_ch24_primitives.rs","tex_ch25_primitives.rs","tex_expandable_primitives.rs","tex_fonts.rs","tex_frontmatter.rs","tex_functions.rs","tex_math_accents.rs","tex_math_mode.rs","tex_math_style.rs","tex_para.rs","tex_registers.rs","tex_rtx_specific.rs","tex_scripts.rs","tex_setup.rs","tex_special_chars.rs","tex_stray_math_style.rs","textcase_sty.rs","textcomp_sty.rs","url_sty.rs","utf8_def.rs","verbatim_sty.rs"]]],["lib.rs","macros.rs","package.rs"]],\
"rtxmath":["",[],["rtx_math.rs"]]\
}');
createSourceSidebar();
