//! Writer for Rust-native kernel dump files.
//!
//! Serializes the State diff (from snapshot/diff_from_snapshot) into a
//! compact text format that can be loaded back efficiently.
//!
//! This is the "DumpFile" equivalent from Perl's TeX_Job.pool.ltxml.
//! The workflow follows Perl's Makefile.PL "make formats" scaffold:
//!   1. take_snapshot() — before processing latex.ltx
//!   2. Process latex.ltx through the engine
//!   3. diff_snapshot() — find what changed
//!   4. write_dump() — serialize the diff
//!   5. At runtime: load_dump() restores the state

use std::io::Write;
use std::path::Path;

use rustc_hash::FxHashMap as HashMap;

use crate::common::arena;
use crate::common::numeric_ops::NumericOps;
use crate::common::store::Stored;
use crate::definition::Definition; // trait for get_expansion(), get_cs(), etc.
use crate::state::TableName;

/// Write a state diff to a dump file.
/// Returns the number of entries successfully written.
///
/// Writes in three ordered sections, matching Perl's
/// `TeX_Job.pool.ltxml::DumpFile` which separates
/// `@cmds_early` / `@cmds` / `@cmds_late`:
///
///   1. **cmds_early** — M:PA / M:MPA let-aliases whose **target pre-existed** in the bootstrap
///      snapshot (e.g. `\tex_let:D → \let`, `\tex_def:D → \def`). Applied first because their
///      targets are always available (they're in the bootstrap pool we loaded unconditionally
///      before this dump).
///   2. **cmds** (regular) — V / M:E / M:T / R / C / LC / UC / SC / MC / DC entries: data,
///      expandable definitions, registers, codes.
///   3. **cmds_late** — M:PA / M:MPA let-aliases whose **target is defined by this dump**. Applied
///      last so the target is installed before the alias fires.
///
/// The early/late split requires the caller (ini_tex) to have staged a
/// snapshot via `state::stage_snapshot("bootstrap")`. If no snapshot is
/// available, all aliases are emitted as `late` (safe — they just wait
/// until after regular entries).
pub fn write_dump(
  path: &Path,
  entries: &[(TableName, crate::common::arena::SymStr, Stored)],
) -> Result<usize, String> {
  let mut file =
    std::fs::File::create(path).map_err(|e| format!("Failed to create dump file: {}", e))?;

  writeln!(file, "# latexml-oxide kernel dump v3").ok();
  writeln!(
    file,
    "# Generated by dump_writer, {} entries",
    entries.len()
  )
  .ok();
  writeln!(file, "# Format: <table>\\t<key>\\t<data>").ok();
  writeln!(file, "#   <table> = M | V | C | LC | UC | SC | MC | DC").ok();
  writeln!(file, "#   <data> depends on <table>:").ok();
  writeln!(
    file,
    "#     M/E:   E\\t<cs>\\t<nargs>\\t<flags>\\t<body>\\t<proto>\\t<v3_params>"
  )
  .ok();
  writeln!(
    file,
    "#            v3_params encodes each Parameter structurally so Until:/Match:"
  )
  .ok();
  writeln!(
    file,
    "#            delimiter tokens round-trip (see docs/DUMP_FORMAT_PERL_ANALYSIS_2026-04-30.md)."
  )
  .ok();
  writeln!(
    file,
    "#     M/PA:  PA\\t<target_cs>   (MPA for math primitives)"
  )
  .ok();
  writeln!(file, "#     M/T:   T\\t<meaning_token>").ok();
  writeln!(
    file,
    "#     M/R:   R\\t<cs>\\t<rtype>\\t<value>[\\t<mathglyph>]"
  )
  .ok();
  writeln!(
    file,
    "#     M/N:   N                     (None-meaning sentinel)"
  )
  .ok();
  writeln!(
    file,
    "#     V:     <type>\\t<value>       (B,I,S,CH,T,TK,N,F,G,MG,D,MD,VD)"
  )
  .ok();
  writeln!(file, "#     C:                  CC\\t<u8>   (catcode)").ok();
  writeln!(
    file,
    "#     DC/LC/UC/SC/MC:     CH\\t<u32>  (char-indexed table entries)"
  )
  .ok();
  writeln!(file, "#   <flags> = subset of {{L, P}} (long, protected)").ok();
  writeln!(
    file,
    "#   All keys and proto are url-encoded (%09 for tab etc.); token body"
  )
  .ok();
  writeln!(
    file,
    "#   tokens use the form <catcode_int>:<url_encoded_text> joined by commas."
  )
  .ok();

  // Read the bootstrap snapshot so we can classify each alias's target
  // as pre-existing (→ early) or defined-during-load (→ late).
  let bootstrap_snap = crate::state::get_staged_snapshot("bootstrap");

  // Pre-serialize + partition. Skipped keys (ver@..., unserializable
  // values) fall out naturally.
  let mut early_aliases: Vec<(String, String, String)> = Vec::new();
  let mut regular: Vec<(String, String, String)> = Vec::new();
  let mut late_aliases: Vec<(String, String, String)> = Vec::new();
  let mut skipped = 0usize;

  // expl3 implements intarrays by stashing values in `\fontdimen<idx>\<font>`
  // slots, picking `cmr10` at various tiny `at <N>sp` instantiations to
  // get one font instance per intarray. Each slot is normally written as
  // an individual `V\tfontdimen_fontinfo_<font> at <Nsp>_<idx>\tD\t<val>`
  // record; that produces ~89k V-records (≈40% of the dump) for an
  // initialized expl3 + LaTeX kernel. We group them by (font,size) and
  // emit a single `IA` record per intarray with the values RLE-encoded
  // — same in-memory state after replay, ~10× smaller on disk.
  // See `docs/archive/PERL_LOADFORMAT_AUDIT.md` ("Fontdimen/intarray storage").
  let mut fontdimen_groups: HashMap<String, Vec<(u32, i64)>> = HashMap::default();

  for (table, key, value) in entries {
    let table_code = table_to_code(*table);
    let key_str = arena::with(*key, |s| s.to_string());

    // Skip \ver@ package version markers (runtime metadata, not definitions)
    if key_str.starts_with("\\ver@") {
      skipped += 1;
      continue;
    }

    // Skip MAX_ERRORS — `ini_tex.rs:189` raises it to 1_000_000 during
    // dump-build (so raw latex.ltx + expl3-code.tex can run through
    // transient errors). It must NOT leak into runtime conversions:
    // a 1M cap lets runaway error cascades (e.g. AmS-TeX `\cases` mis-
    // parse → 1M `\hbox`/`&` per paper, math0205073) bypass the
    // 10000 default. dump_reader has a parallel filter for the
    // already-shipped dumps; this filter keeps future regenerations
    // clean.
    if matches!(*table, TableName::Value) && key_str == "MAX_ERRORS" {
      skipped += 1;
      continue;
    }

    // Skip \@currname / \@currext file-IO bookkeeping. These are
    // assigned per-document during `\input` by `read_input_file_recursive`
    // (see `binding/content.rs:262-263`) to the literal filename's
    // tokens, so the snapshot captures the LAST opened file's name
    // ("plain.tex" / "latex.ltx"). Perl's `TeX_FileIO.pool.ltxml:28-29`
    // initializes them via `Let('\@currname','\lx@empty')` before any
    // file load, and Perl's plain_dump.pool.ltxml omits them — so
    // post-dump they remain at the `\lx@empty` baseline. Matching that
    // behavior here keeps us file-IO-state-agnostic in the dump.
    if matches!(*table, TableName::Meaning) && (key_str == "\\@currname" || key_str == "\\@currext")
    {
      skipped += 1;
      continue;
    }

    // Skip token-list register VALUES whose body contains a self-`\the`
    // reference. latex.ltx L10564-10580 sets `\frozen@everymath` =
    // `{... \the\everymath}` then allocates a NEW `\everymath` via
    // `\newtoks`. Our `\newtoks` doesn't fully detach the new register's
    // slot from the frozen alias's, so the body lands on `\everymath`'s
    // value slot — `\the\everymath` then expands recursively at math
    // entry, blowing the token limit. Until the `\newtoks`/`\let`
    // slot-aliasing is fixed at the dialect level, the safest cure is
    // to drop the corrupted self-referential capture; runtime
    // re-evaluation of latex.ltx's hook chain (or LaTeXML's own
    // `\everymath`/`\everydisplay` setup) repopulates correctly.
    if matches!(*table, TableName::Value)
      && matches!(
        key_str.as_str(),
        "\\everymath"
          | "\\everydisplay"
          | "\\everyhbox"
          | "\\everyvbox"
          | "\\everycr"
          | "\\everyjob"
          | "\\everypar"
          | "\\everyeof"
      )
    {
      // Confirm the loop pattern before dropping (don't suppress
      // valid hook contributions on engines with sound aliasing).
      if let Stored::Tokens(tks) = value {
        let body = tks.unlist_ref();
        let needle_cs = key_str.clone();
        let has_self_the = body.iter().any(|t| t.with_str(|s| s == "\\the"))
          && body.iter().any(|t| t.with_str(|s| s == needle_cs));
        if has_self_the {
          skipped += 1;
          continue;
        }
      }
    }

    // Perl #2771 (2026-03-13) + upstream IGNORED_SYMBOLS: these are
    // runtime-only Value entries — control-flow counters, and large
    // registered-rule tables that can't meaningfully round-trip through
    // the dump (they hold closures, cross-refs, or re-populate during
    // engine init anyway). Match Perl's TeX_Job.pool.ltxml list.
    if matches!(*table, TableName::Value)
      && matches!(
        key_str.as_str(),
        "if_count"
          | "absorb_count"
          | "if_stack"
          | "DOCUMENT_REWRITE_RULES"
          | "PARAMETER_TYPES"
          | "TAG_PROPERTIES"
          | "MATH_LIGATURES"
          | "TEXT_LIGATURES"
      )
    {
      skipped += 1;
      continue;
    }

    // Perl IGNORED_SYMBOLS: meaning:\lnot, meaning:\to are skipped because
    // pre-2017 TeXlive let-aliased \lnot → \neg and \to → \rightarrow,
    // which would gratuitously diverge tests across TL versions.
    // Mirror Perl `TeX_Job.pool.ltxml` IGNORED_SYMBOLS L104-107.
    if matches!(*table, TableName::Meaning) && matches!(key_str.as_str(), "\\lnot" | "\\to") {
      skipped += 1;
      continue;
    }

    // Intarray slot consolidation — see fontdimen_groups comment above.
    if matches!(*table, TableName::Value) {
      if let Some((prefix, idx)) = parse_fontdimen_key(&key_str) {
        if let Stored::Dimension(d) = value {
          fontdimen_groups
            .entry(prefix.to_string())
            .or_default()
            .push((idx, d.0));
          continue;
        }
      }
    }

    let Some(serialized) = serialize_stored(value) else {
      skipped += 1;
      continue;
    };

    // A let-alias entry is an M row whose serialized form starts with
    // `PA\t` or `MPA\t`. Nothing else produces those prefixes.
    let is_alias = matches!(*table, TableName::Meaning)
      && (serialized.starts_with("PA\t") || serialized.starts_with("MPA\t"));

    let row = (table_code.to_string(), url_encode(&key_str), serialized);
    if is_alias {
      // Extract the target CS from "PA\t<target>" / "MPA\t<target>"
      // (we already filtered self-aliases in serialize_stored, so the
      //  target is always a different CS than the key).
      let target_raw = row.2.split('\t').nth(1).unwrap_or("");
      let target = crate::dump_reader::url_decode(target_raw);
      let target_sym = arena::pin(&target);
      // Target pre-existed iff it was in the bootstrap meaning table.
      let pre_existed = bootstrap_snap
        .as_ref()
        .is_some_and(|snap| snap.contains_key(&(TableName::Meaning, target_sym)));
      if pre_existed {
        early_aliases.push(row);
      } else {
        late_aliases.push(row);
      }
    } else {
      regular.push(row);
    }
  }

  // Emit one IA record per intarray group. Fall back to individual V
  // records for any non-dense group (defensive: dump_reader only knows
  // how to expand contiguous 1..N runs).
  let mut ia_count = 0usize;
  let mut ia_fallback_v = 0usize;
  for (prefix, mut slots) in fontdimen_groups.into_iter() {
    slots.sort_by_key(|s| s.0);
    let dense = slots
      .iter()
      .enumerate()
      .all(|(i, (idx, _))| *idx == (i as u32 + 1));
    if !dense {
      eprintln!(
        "[dump_writer] non-dense intarray {:?} ({} slots) — emitting as individual V records",
        prefix,
        slots.len()
      );
      for (idx, val) in &slots {
        let key = format!("{}_{}", prefix, idx);
        regular.push(("V".to_string(), url_encode(&key), format!("D\t{}", val)));
        ia_fallback_v += 1;
      }
      continue;
    }
    let values: Vec<i64> = slots.into_iter().map(|(_, v)| v).collect();
    let rle = rle_encode_i64(&values);
    let body = format!("{}\t{}", values.len(), rle);
    regular.push(("IA".to_string(), url_encode(&prefix), body));
    ia_count += 1;
  }
  if ia_count > 0 || ia_fallback_v > 0 {
    eprintln!(
      "[dump_writer] intarray consolidation: {} IA records, {} V fallbacks",
      ia_count, ia_fallback_v
    );
  }

  writeln!(
    file,
    "# Section 0: early let-aliases ({}) — target in bootstrap",
    early_aliases.len()
  )
  .ok();
  for (t, k, v) in &early_aliases {
    writeln!(file, "{}\t{}\t{}", t, k, v).map_err(|e| format!("Write error: {}", e))?;
  }
  writeln!(file, "# Section 1: regular entries ({})", regular.len()).ok();
  for (t, k, v) in &regular {
    writeln!(file, "{}\t{}\t{}", t, k, v).map_err(|e| format!("Write error: {}", e))?;
  }
  writeln!(
    file,
    "# Section 2: late let-aliases ({}) — target in Section 1",
    late_aliases.len()
  )
  .ok();
  for (t, k, v) in &late_aliases {
    writeln!(file, "{}\t{}\t{}", t, k, v).map_err(|e| format!("Write error: {}", e))?;
  }

  let count = early_aliases.len() + regular.len() + late_aliases.len();
  writeln!(file, "# Written: {}, Skipped: {}", count, skipped).ok();
  eprintln!(
    "[dump_writer] Wrote {} entries to {} ({} skipped; {} early + {} regular + {} late)",
    count,
    path.display(),
    skipped,
    early_aliases.len(),
    regular.len(),
    late_aliases.len(),
  );

  Ok(count)
}

fn table_to_code(t: TableName) -> &'static str {
  match t {
    TableName::Meaning => "M",
    TableName::Value => "V",
    TableName::Catcode => "C",
    TableName::Mathcode => "MC",
    TableName::Sfcode => "SC",
    TableName::Lccode => "LC",
    TableName::Uccode => "UC",
    TableName::Delcode => "DC",
    TableName::Stash => "ST",
    TableName::StashActive => "SA",
  }
}

/// Serialize a Stored value to a type-tag + data string.
/// Returns None if the value can't be serialized.
fn serialize_stored(stored: &Stored) -> Option<String> {
  match stored {
    Stored::None => Some("N".to_string()),
    Stored::Bool(b) => Some(format!("B\t{}", if *b { "1" } else { "0" })),
    Stored::Int(i) => Some(format!("I\t{}", i)),
    Stored::String(s) => Some(format!(
      "S\t{}",
      url_encode(&arena::with(*s, |s| s.to_string()))
    )),
    Stored::Charcode(c) => Some(format!("CH\t{}", c)),
    Stored::Catcode(cc) => Some(format!("CC\t{}", u8::from(*cc))),
    Stored::Token(t) => Some(format!("T\t{}", serialize_token(t))),
    Stored::Tokens(tks) => {
      let tok_strs: Vec<String> = tks.unlist_ref().iter().map(serialize_token).collect();
      Some(format!("TK\t{}", tok_strs.join(",")))
    },
    Stored::Expandable(exp) => {
      use crate::common::object::Object;
      let cs_name = exp.get_cs().with_str(url_encode);
      let nargs = exp.get_num_args();
      let mut flags = String::new();
      if exp.is_long {
        flags.push('L');
      }
      if exp.is_protected() {
        flags.push('P');
      }
      // Two parallel parameter encodings:
      //
      //   - `proto` (v2, 5th field) — `Parameters::stringify()`, a flat space-separated prototype
      //     string. Round-trips simple specs but not `Until:\end{verbatim}` or other
      //     brace-in-delimiter forms.
      //   - `v3_params` (v3, 6th field) — per-Parameter structured record carrying (name, spec,
      //     flags, extras). Modeled on Perl's `P(type, spec, extra=>[T(...)])`; see
      //     `docs/DUMP_FORMAT_PERL_ANALYSIS_2026-04-30.md`. Bypasses `parse_parameters` at load time so
      //     delimited params round-trip intact.
      //
      // We emit both so older readers still work, and newer readers can
      // prefer v3 transparently.
      let proto = exp
        .get_parameters()
        .map(|p| p.stringify())
        .unwrap_or_default();
      let proto_encoded = url_encode(&proto);
      let v3_params = exp
        .get_parameters()
        .map(serialize_parameters_v3)
        .unwrap_or_default();
      match exp.get_expansion() {
        Some(crate::definition::ExpansionBody::Tokens(tks)) => {
          let tok_strs: Vec<String> = tks.unlist_ref().iter().map(serialize_token).collect();
          Some(format!(
            "E\t{}\t{}\t{}\t{}\t{}\t{}",
            cs_name,
            nargs,
            flags,
            tok_strs.join(","),
            proto_encoded,
            v3_params
          ))
        },
        // No body at all (e.g. `DefMacro!("\\@gobble{}", None)`): serializes
        // as an E-entry with empty token body. The reader reconstructs an
        // Expandable with empty Tokens + the original paramlist, which at
        // expansion time reads and discards its arguments — semantically
        // identical to the no-body form's runtime behavior (expandable.rs
        // `invoke` matches `None` → reads args, returns NO_TOKENS).
        None => Some(format!(
          "E\t{}\t{}\t{}\t\t{}\t{}",
          cs_name, nargs, flags, proto_encoded, v3_params
        )),
        // Closure-based body — can't serialize the closure itself, BUT
        // if the dump entry is a `\let`-alias to a closure-Expandable
        // primitive (e.g. `\let \tex_expandafter:D \expandafter`), we
        // CAN capture it via PA. Mirrors the `Stored::Primitive` /
        // `Stored::Conditional` arms below. Without this, every
        // `\let \X \expandafter`-style alias is silently dropped from
        // the dump — the cause of `\tex_expandafter:D`,
        // `\tex_unexpanded:D`, `\tex_the:D` being missing in
        // `latex.dump.txt` even though expl3-code.tex L357+ aliases them.
        //
        // The dump_reader's add-only policy at load-time skips entries
        // whose key is already defined (the canonical CS lives in the
        // compiled engine), so self-aliases are no-ops. Real let-aliases
        // (key != cs) replay via `state::let_i`.
        Some(crate::definition::ExpansionBody::Closure(_)) => Some(format!("PA\t{}", cs_name)),
      }
    },
    // Closure-based primitives can't be serialized directly — but if the entry's
    // CS differs from the primitive's own CS, it's a `\let`-alias, and we CAN
    // capture the alias so the dump reader can replay `\let <key> <target>` at
    // load time. This is how `\tex_let:D`, `\tex_def:D`, and hundreds of other
    // expl3-renamed primitives stay reachable across dump boundaries (the
    // defining assignment `\let \tex_let:D \let` in expl3-code.tex needs to
    // survive the dump for `\usepackage{expl3}`'s guard `\ifx\csname
    // tex_let:D\endcsname\relax` to short-circuit).
    //
    // NOTE: the KEY we're saving IS the dump entry's first column; the VALUE
    // we write is the primitive's OWN CS name. Dump reader compares these:
    // if equal, it's the "primary" primitive (already in bindings) and skipped;
    // if different, it's an alias — replay `\let` at load time.
    Stored::Primitive(p) => {
      // Perl `Core/Dumper.pm::dump_primitive` (L383-389): if a primitive has
      // a `font` directive AND no replacement closure (i.e. defined by `\font`),
      // emit `FD(<cs>, <fontID>)` instead of generic Primitive serialization.
      // `font_id` is set on `\font`-defined primitives by `engine/tex_fonts.rs`'s
      // post-define hook (the Rust path) — it carries the value-table key under
      // which the Stored::Font lives. The reader installs a synthesized
      // Primitive whose before_digest looks up that font and merges, mirroring
      // `LaTeXML::Core::Definition::FontDef::invoke` (FontDef.pm L38-45).
      if let Some(fid) = p.font_id {
        let fid_str = arena::with(fid, |s| s.to_string());
        return Some(format!("FD\t{}", url_encode(&fid_str)));
      }
      let target_cs = p.cs.with_str(url_encode);
      Some(format!("PA\t{}", target_cs))
    },
    Stored::Font(f) => {
      // Perl `dump_font` (Core/Dumper.pm L281-284) emits `F(... components ...)`.
      // Rust's `Font` is a flat options struct, so we serialize the non-None
      // fields as `key=value` pairs separated by `\x1f` (unit-separator), with
      // values url-encoded for tab/newline-safety. Reader inverts in dump_reader.rs.
      let mut parts = Vec::with_capacity(8);
      if let Some(ref name) = f.name {
        parts.push(format!("name={}", url_encode(name)));
      }
      if let Some(size) = f.size {
        parts.push(format!("size={}", size));
      }
      if let Some(ref family) = f.family {
        parts.push(format!("family={}", url_encode(family)));
      }
      if let Some(ref series) = f.series {
        parts.push(format!("series={}", url_encode(series)));
      }
      if let Some(ref shape) = f.shape {
        parts.push(format!("shape={}", url_encode(shape)));
      }
      if let Some(ref encoding) = f.encoding {
        parts.push(format!("encoding={}", url_encode(encoding)));
      }
      if let Some(ref language) = f.language {
        parts.push(format!("language={}", url_encode(language)));
      }
      if let Some(ref mathstyle) = f.mathstyle {
        parts.push(format!("mathstyle={}", url_encode(mathstyle)));
      }
      if let Some(ref opacity) = f.opacity {
        parts.push(format!("opacity={}", url_encode(opacity)));
      }
      if let Some(scale) = f.scale {
        parts.push(format!("scale={}", scale));
      }
      if let Some(b) = f.emph {
        parts.push(format!("emph={}", if b { 1 } else { 0 }));
      }
      if let Some(b) = f.scripted {
        parts.push(format!("scripted={}", if b { 1 } else { 0 }));
      }
      if let Some(step) = f.mathstylestep {
        parts.push(format!("mathstylestep={}", step));
      }
      if let Some(flags) = f.flags {
        parts.push(format!("flags={}", flags));
      }
      Some(format!("F\t{}", parts.join("\x1f")))
    },
    Stored::MathPrimitive(p) => {
      let target_cs = p.cs.with_str(url_encode);
      Some(format!("MPA\t{}", target_cs))
    },
    // Conditionals — same logic as Primitives. \ifx, \ifnum, \if etc. are
    // stored as Stored::Conditional with their canonical CS field. When
    // expl3-code.tex does `\let \if_meaning:w \ifx`, the new entry shares
    // the same Conditional Rc, with cs = \ifx. Capturing this as a PA
    // alias lets the dump reader replay `\let \if_meaning:w \ifx` at load
    // time. Without this, every expl3 conditional alias is silently lost
    // from the dump and `\if_meaning:w`-style invocations fail at runtime.
    Stored::Conditional(c) => {
      let target_cs = c.cs.with_str(url_encode);
      Some(format!("PA\t{}", target_cs))
    },
    // Constructors — `\cr`, `\noalign`, `\mathchoice`, etc. defined via
    // `DefConstructor!` carry replacement / before_digest / after_digest
    // closures that the dump format can't serialize. But the canonical
    // CS lives in the compiled engine, so a `\let \tex_cr:D \cr`-style
    // alias can round-trip as `PA\t<cs>` and replay via `state::let_i`.
    // Self-aliases are no-ops at load (key already defined).
    Stored::Constructor(c) => {
      let target_cs = c.cs.with_str(url_encode);
      Some(format!("PA\t{}", target_cs))
    },
    Stored::Register(reg) => {
      // Register: serialize as R\tCS\tTYPE\tVALUE[\tMATHGLYPH]
      //
      // Closure-backed registers can't be serialized directly — but if the
      // dump entry is a `\let`-alias to a closure-Register primitive
      // (e.g. `\let \tex_dimexpr:D \dimexpr`), we CAN capture it via PA.
      // Mirrors the `Stored::Primitive` / closure-`Expandable` arms above.
      // Without this every `\let \tex_dimexpr:D \dimexpr`-style alias is
      // silently dropped from the dump — the cause of `\tex_dimexpr:D`,
      // `\tex_cr:D`, `\tex_dp:D`, `\tex_ht:D`, `\tex_wd:D` (and ~430
      // engine-specific others) being missing in `latex.dump.txt` even
      // though expl3-code.tex L280-700 aliases them. The dump_reader's
      // add-only policy at load-time skips entries whose key is already
      // defined (the canonical CS lives in the compiled engine), so
      // self-aliases are no-ops. Real let-aliases (key != cs) replay via
      // `state::let_i` — so the engine-only register's behavior follows.
      if reg.getter.is_some() || reg.setter.is_some() {
        let target_cs = reg.cs.with_str(url_encode);
        return Some(format!("PA\t{}", target_cs));
      }
      let cs_name = reg.cs.with_str(url_encode);
      let rtype = match reg.register_type {
        crate::definition::register::RegisterType::Number => "N",
        crate::definition::register::RegisterType::Dimension => "D",
        crate::definition::register::RegisterType::Glue => "G",
        crate::definition::register::RegisterType::MuGlue => "MG",
        crate::definition::register::RegisterType::Tokens => "TK",
        crate::definition::register::RegisterType::CharDef => "CD",
        _ => return Option::None,
      };
      let value_str = match &reg.value {
        Some(crate::definition::register::RegisterValue::Number(n)) => n.value_of().to_string(),
        Some(crate::definition::register::RegisterValue::Dimension(d)) => d.value_of().to_string(),
        Some(crate::definition::register::RegisterValue::Glue(g)) => {
          let mut s = g.skip.to_string();
          if let Some(p) = g.plus {
            s.push_str(&format!(",p{}", p));
          }
          if let Some(ref pf) = g.pfill {
            s.push_str(&format!(",pf{}", fillcode_index(pf)));
          }
          if let Some(m) = g.minus {
            s.push_str(&format!(",m{}", m));
          }
          if let Some(ref mf) = g.mfill {
            s.push_str(&format!(",mf{}", fillcode_index(mf)));
          }
          s
        },
        Some(crate::definition::register::RegisterValue::Tokens(tks)) => {
          let tok_strs: Vec<String> = tks.unlist_ref().iter().map(serialize_token).collect();
          tok_strs.join(",")
        },
        _ => "0".to_string(),
      };
      // Serialize address if different from cs name. Allocated registers
      // (`\newcount\m@ne`/`\newdimen\p@`/etc.) point at low-level `\count<n>`/
      // `\dimen<n>` slots whose runtime values live there, NOT at the alias
      // CS name. Without the address, dump_reader would `assign_internal` at
      // the CS name's slot (default value), and `\the\m@ne` would yield 0
      // instead of -1. Mirror Perl's `R(C(...),undef,...,address=>'\\count22')`
      // serialization (LaTeXML/Core/Dumper.pm). Format extension:
      // `R\t<cs>\t<rtype>\t<value>\t<mathglyph_or_empty>\t<address>`.
      // If address == cs_name we still serialize an empty 6th field for
      // forward-compat parsers; the reader accepts both 4/5/6-field forms.
      let mut s = format!("R\t{}\t{}\t{}", cs_name, rtype, value_str);
      let mathglyph_str = match reg.mathglyph {
        Some(glyph) => format!("{}", glyph as u32),
        None => String::new(),
      };
      let cs_decoded = arena::with(reg.cs.get_sym(), |s| s.to_string());
      let address_field = if reg.address.is_empty() || reg.address == cs_decoded {
        String::new()
      } else {
        url_encode(&reg.address)
      };
      // Only emit extended fields when needed (keep current format size for
      // the common case)
      if !mathglyph_str.is_empty() || !address_field.is_empty() {
        s.push_str(&format!("\t{}", mathglyph_str));
      }
      if !address_field.is_empty() {
        s.push_str(&format!("\t{}", address_field));
      }
      Some(s)
    },
    // "Nm" (Number) — distinct from "I" (raw Int) so the reader knows
    // to install Stored::Number, matching the type expected by register
    // slots. Round-tripping Number through "I" silently downgraded
    // values to Stored::Int and broke `\count` register reads.
    Stored::Number(n) => Some(format!("Nm\t{}", n.value_of())),
    Stored::Float(f) => Some(format!("F\t{}", f.0)),
    Stored::Dimension(d) => Some(format!("D\t{}", d.0)),
    Stored::Glue(g) => {
      let mut s = format!("G\t{}", g.skip);
      if let Some(p) = g.plus {
        s.push_str(&format!(",p{}", p));
      }
      if let Some(ref pf) = g.pfill {
        s.push_str(&format!(",pf{}", fillcode_index(pf)));
      }
      if let Some(m) = g.minus {
        s.push_str(&format!(",m{}", m));
      }
      if let Some(ref mf) = g.mfill {
        s.push_str(&format!(",mf{}", fillcode_index(mf)));
      }
      Some(s)
    },
    Stored::MuDimension(d) => Some(format!("MD\t{}", d.0)),
    Stored::MuGlue(g) => {
      let mut s = format!("MG\t{}", g.skip);
      if let Some(p) = g.plus {
        s.push_str(&format!(",p{}", p));
      }
      if let Some(ref pf) = g.pfill {
        s.push_str(&format!(",pf{}", fillcode_index(pf)));
      }
      if let Some(m) = g.minus {
        s.push_str(&format!(",m{}", m));
      }
      if let Some(ref mf) = g.mfill {
        s.push_str(&format!(",mf{}", fillcode_index(mf)));
      }
      Some(s)
    },
    Stored::VecDequeStored(vd) if vd.is_empty() => Some("VD\t".to_string()),
    _ => Option::None,
  }
}

fn fillcode_index(fc: &crate::common::glue::FillCode) -> usize {
  use crate::common::glue::FillCode::*;
  match fc {
    Fil => 1,
    Fill => 2,
    Filll => 3,
  }
}

fn serialize_token(t: &crate::token::Token) -> String {
  let cc: u8 = t.get_catcode().into();
  let text = t.with_str(url_encode);
  format!("{}:{}", cc, text)
}

/// Serialize a `Parameters` list in the v3 structured format.
///
/// Layout (ASCII control-byte delimited so nothing collides with
/// url-encoded printable content):
/// - `\x1e` between Parameters (RS, Record Separator)
/// - `\x1f` between fields of a single Parameter (US, Unit Separator)
/// - `\x1d` between Tokens lists inside `extras` (GS, Group Separator)
///
/// Per-parameter fields: `<name>\x1f<spec>\x1f<flags>\x1f<extras>`
///   - `<name>` — `Parameter.name` (Perl's `type`), url-encoded.
///   - `<spec>` — `Parameter.spec`, url-encoded.
///   - `<flags>` — semicolon-separated `n=1` (novalue) / `o=1` (optional).
///   - `<extras>` — `<Tokens1>\x1d<Tokens2>…` where each `<TokensN>` is the same comma-joined
///     `<catcode>:<text>` encoding used for E-entry bodies. Empty extras → empty field.
///
/// The reader (`dump_reader::parse_parameters_v3`) hands the decoded
/// `(name, spec, Some(extras))` triple directly to `Parameter::new`,
/// bypassing `parse_parameters` entirely — so `Until:\end{verbatim}`
/// and `Match:…` round-trip with their catcoded delimiter tokens intact.
pub(crate) fn serialize_parameters_v3(params: &crate::parameter::Parameters) -> String {
  let mut out = String::new();
  for (i, p) in params.get_parameters().iter().enumerate() {
    if i > 0 {
      out.push('\x1e');
    }
    let name = arena::with(p.name, url_encode);
    let spec = arena::with(p.spec, url_encode);
    let mut flags = String::new();
    if p.novalue {
      flags.push_str("n=1");
    }
    if p.optional {
      if !flags.is_empty() {
        flags.push(';');
      }
      flags.push_str("o=1");
    }
    let extras = p
      .extra
      .iter()
      .map(|tks| {
        tks
          .clone()
          .unlist()
          .iter()
          .map(serialize_token)
          .collect::<Vec<_>>()
          .join(",")
      })
      .collect::<Vec<_>>()
      .join("\x1d");
    out.push_str(&name);
    out.push('\x1f');
    out.push_str(&spec);
    out.push('\x1f');
    out.push_str(&flags);
    out.push('\x1f');
    out.push_str(&extras);
  }
  out
}

fn url_encode(s: &str) -> String {
  let mut result = String::with_capacity(s.len());
  for ch in s.chars() {
    match ch {
      '\t' => result.push_str("%09"),
      '\n' => result.push_str("%0A"),
      '\r' => result.push_str("%0D"),
      '%' => result.push_str("%25"),
      ',' => result.push_str("%2C"),
      _ if ch.is_ascii_control() => {
        result.push_str(&format!("%{:02X}", ch as u8));
      },
      _ => result.push(ch),
    }
  }
  result
}

/// Recognize expl3's intarray-as-fontdimen storage keys, e.g.
/// `fontdimen_fontinfo_cmr10 at 15sp_12737` → ("fontdimen_fontinfo_cmr10 at 15sp", 12737).
/// Returns None for other Value keys (so the regular V-record path applies).
fn parse_fontdimen_key(key: &str) -> Option<(&str, u32)> {
  // Cheap gate first to keep the hot path fast on non-fontdimen keys.
  if !key.starts_with("fontdimen_fontinfo_") {
    return None;
  }
  // The last `_<digits>` tail is the slot index; everything before is the
  // per-intarray prefix. Be defensive: an all-letter tail (e.g. a future
  // non-indexed `fontdimen_fontinfo_*` key) should not match.
  let last_us = key.rfind('_')?;
  let (prefix, tail) = (&key[..last_us], &key[last_us + 1..]);
  let index: u32 = tail.parse().ok()?;
  Some((prefix, index))
}

/// Run-length encode a slice of i64 values as a comma-separated list:
/// each run is either `<v>` (single) or `<v>x<n>` (count ≥ 2). Decoder
/// in `dump_reader::rle_decode_i64` is the inverse.
fn rle_encode_i64(values: &[i64]) -> String {
  let mut out = String::new();
  let mut i = 0;
  while i < values.len() {
    let v = values[i];
    let mut count = 1usize;
    while i + count < values.len() && values[i + count] == v {
      count += 1;
    }
    if !out.is_empty() {
      out.push(',');
    }
    if count == 1 {
      out.push_str(&v.to_string());
    } else {
      out.push_str(&format!("{}x{}", v, count));
    }
    i += count;
  }
  out
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::parameter::{Parameter, Parameters};
  use crate::token::{Catcode, Token};
  use crate::tokens::Tokens;

  /// Construct a Parameter without calling `init()` — `init()` needs live
  /// state (PARAMETER_TYPES table), which we don't set up in unit tests.
  /// The full test suite exercises the `init()` path via dump load.
  fn raw_param(name: &str, spec: &str, extra: Vec<Tokens>) -> Parameter {
    Parameter {
      name: arena::pin(name),
      spec: arena::pin(spec),
      extra,
      ..Parameter::default()
    }
  }

  /// A Parameters list with two `Plain {}` args encodes as two records
  /// separated by RS, each `Plain<US>{}<US><US>`. Verifies baseline layout.
  #[test]
  fn v3_encoding_plain() {
    let ps = Parameters::new(vec![
      raw_param("Plain", "{}", vec![]),
      raw_param("Plain", "{}", vec![]),
    ]);
    let s = serialize_parameters_v3(&ps);
    assert_eq!(s, "Plain\x1f{}\x1f\x1f\x1ePlain\x1f{}\x1f\x1f");
  }

  /// `Until:<delim>` with a brace-containing delimiter. The test covers
  /// the case that livelocked 00_tokenize under v2: the delimiter tokens
  /// must serialize as catcoded tokens (not as the raw spec string), so
  /// `{`/`}` survive as CC_BEGIN / CC_END rather than being re-parsed as
  /// spec-level braces.
  #[test]
  fn v3_encoding_until_with_braces() {
    let delim = Tokens::new(vec![
      Token {
        text: arena::pin("\\end"),
        code: Catcode::CS,
      #[cfg(feature = "token-locators")] loc: 0
    },
      Token {
        text: arena::pin("{"),
        code: Catcode::BEGIN,
        #[cfg(feature = "token-locators")] loc: 0,
      },
      Token {
        text: arena::pin("verbatim"),
        code: Catcode::LETTER,
      #[cfg(feature = "token-locators")] loc: 0
    },
      Token {
        text: arena::pin("}"),
        code: Catcode::END,
        #[cfg(feature = "token-locators")] loc: 0,
      },
    ]);
    let ps = Parameters::new(vec![raw_param("Until", "Until:\\end{verbatim}", vec![
      delim,
    ])]);
    let s = serialize_parameters_v3(&ps);
    // Expected: Until<US>Until:\end{verbatim}<US><US>16:\end,1:{,11:verbatim,2:}
    assert!(s.starts_with("Until\x1fUntil:\\end{verbatim}\x1f\x1f"));
    assert!(s.contains("16:\\end,1:{,11:verbatim,2:}"));
  }

  /// `novalue` flag encodes as `n=1` in the flags field.
  #[test]
  fn v3_encoding_novalue_flag() {
    let mut p = raw_param("Match", "Match:abc", vec![]);
    p.novalue = true;
    let ps = Parameters::new(vec![p]);
    let s = serialize_parameters_v3(&ps);
    assert_eq!(s, "Match\x1fMatch:abc\x1fn=1\x1f");
  }

  /// `optional` flag encodes as `o=1`; both flags together as `n=1;o=1`.
  #[test]
  fn v3_encoding_both_flags() {
    let mut p = raw_param("OptionalMatch", "OptionalMatch:x", vec![]);
    p.novalue = true;
    p.optional = true;
    let ps = Parameters::new(vec![p]);
    let s = serialize_parameters_v3(&ps);
    assert_eq!(s, "OptionalMatch\x1fOptionalMatch:x\x1fn=1;o=1\x1f");
  }

  /// Empty Parameters serializes to empty string.
  #[test]
  fn v3_encoding_empty() {
    let ps = Parameters::new(vec![]);
    assert_eq!(serialize_parameters_v3(&ps), "");
  }

  /// Multiple Tokens inside `extras` (as in `Match` with multiple choices)
  /// are separated by GS. Verifies the three-level delimiter scheme.
  #[test]
  fn v3_encoding_multiple_extra_tokens() {
    let t1 = Tokens::new(vec![Token {
      text: arena::pin("a"),
      code: Catcode::LETTER,
      #[cfg(feature = "token-locators")] loc: 0
    }]);
    let t2 = Tokens::new(vec![Token {
      text: arena::pin("b"),
      code: Catcode::LETTER,
      #[cfg(feature = "token-locators")] loc: 0
    }]);
    let ps = Parameters::new(vec![raw_param("Match", "Match:ab", vec![t1, t2])]);
    let s = serialize_parameters_v3(&ps);
    // Expected extras field: "11:a<GS>11:b"
    assert_eq!(s, "Match\x1fMatch:ab\x1f\x1f11:a\x1d11:b");
  }

  // --- RLE encoder tests (intarray consolidation) ---

  #[test]
  fn rle_empty_slice() {
    assert_eq!(rle_encode_i64(&[]), "");
  }

  #[test]
  fn rle_single_value() {
    assert_eq!(rle_encode_i64(&[5]), "5");
  }

  #[test]
  fn rle_two_distinct() {
    assert_eq!(rle_encode_i64(&[1, 2]), "1,2");
  }

  #[test]
  fn rle_run_of_two() {
    assert_eq!(rle_encode_i64(&[5, 5]), "5x2");
  }

  #[test]
  fn rle_long_run() {
    assert_eq!(rle_encode_i64(&[218; 10000]), "218x10000");
  }

  #[test]
  fn rle_mixed_runs() {
    assert_eq!(rle_encode_i64(&[1, 2, 2, 3, 3, 3, 1]), "1,2x2,3x3,1");
  }

  #[test]
  fn rle_negative() {
    assert_eq!(rle_encode_i64(&[-5]), "-5");
    assert_eq!(rle_encode_i64(&[-5, -5, -5]), "-5x3");
  }

  #[test]
  fn rle_extreme_values() {
    assert_eq!(rle_encode_i64(&[i64::MIN]), i64::MIN.to_string());
    assert_eq!(rle_encode_i64(&[i64::MAX]), i64::MAX.to_string());
    assert_eq!(rle_encode_i64(&[0; 3]), "0x3");
  }

  // --- parse_fontdimen_key tests ---

  #[test]
  fn fontdimen_key_standard() {
    assert_eq!(
      parse_fontdimen_key("fontdimen_fontinfo_cmr10 at 15sp_12737"),
      Some(("fontdimen_fontinfo_cmr10 at 15sp", 12737))
    );
  }

  #[test]
  fn fontdimen_key_index_one() {
    assert_eq!(
      parse_fontdimen_key("fontdimen_fontinfo_cmr10 at 5sp_1"),
      Some(("fontdimen_fontinfo_cmr10 at 5sp", 1))
    );
  }

  #[test]
  fn fontdimen_key_non_fontdimen() {
    assert_eq!(parse_fontdimen_key("count@"), None);
    assert_eq!(parse_fontdimen_key("\\@oddpage"), None);
  }

  #[test]
  fn fontdimen_key_wrong_prefix() {
    // Missing the `_fontinfo_` segment — must not match.
    assert_eq!(parse_fontdimen_key("fontdimen_cmr10_15"), None);
  }

  #[test]
  fn fontdimen_key_non_numeric_tail() {
    // No trailing digits after last `_` ⇒ no index ⇒ no match.
    assert_eq!(parse_fontdimen_key("fontdimen_fontinfo_cmr10 at 15sp_abc"), None);
  }

  #[test]
  fn fontdimen_key_empty_tail() {
    // Trailing underscore with no digits ⇒ no match.
    assert_eq!(parse_fontdimen_key("fontdimen_fontinfo_cmr10 at 15sp_"), None);
  }
}
