//! Writer for Rust-native kernel dump files.
//!
//! Serializes the State diff (from snapshot/diff_from_snapshot) into a
//! compact text format that can be loaded back efficiently.
//!
//! This is the "DumpFile" equivalent from Perl's TeX_Job.pool.ltxml.
//! The workflow follows Perl's Makefile.PL "make formats" scaffold:
//!   1. take_snapshot() — before processing latex.ltx
//!   2. Process latex.ltx through the engine
//!   3. diff_snapshot() — find what changed
//!   4. write_dump() — serialize the diff
//!   5. At runtime: load_dump() restores the state

use std::io::Write;
use std::path::Path;

use crate::common::arena;
use crate::common::store::Stored;
use crate::definition::Definition; // trait for get_expansion(), get_cs(), etc.
use crate::state::TableName;
use crate::token::Token;

/// Write a state diff to a dump file.
/// Returns the number of entries successfully written.
pub fn write_dump(
  path: &Path,
  entries: &[(TableName, crate::common::arena::SymStr, Stored)],
) -> Result<usize, String> {
  let mut file = std::fs::File::create(path)
    .map_err(|e| format!("Failed to create dump file: {}", e))?;

  writeln!(file, "# latexml-oxide kernel dump v1").ok();
  writeln!(file, "# Generated by dump_writer, {} entries", entries.len()).ok();

  let mut count = 0;
  let mut skipped = 0;
  for (table, key, value) in entries {
    let table_code = table_to_code(*table);
    let key_str = arena::with(*key, |s| s.to_string());

    // Skip \ver@ package version markers (runtime metadata, not definitions)
    if key_str.starts_with("\\ver@") {
      skipped += 1;
      continue;
    }
    if let Some(serialized) = serialize_stored(value) {
      writeln!(file, "{}\t{}\t{}", table_code, url_encode(&key_str), serialized)
        .map_err(|e| format!("Write error: {}", e))?;
      count += 1;
    } else {
      skipped += 1;
    }
  }

  writeln!(file, "# Written: {}, Skipped: {}", count, skipped).ok();
  eprintln!(
    "[dump_writer] Wrote {} entries to {} ({} skipped)",
    count,
    path.display(),
    skipped
  );

  Ok(count)
}

fn table_to_code(t: TableName) -> &'static str {
  match t {
    TableName::Meaning => "M",
    TableName::Value => "V",
    TableName::Catcode => "C",
    TableName::Mathcode => "MC",
    TableName::Sfcode => "SC",
    TableName::Lccode => "LC",
    TableName::Uccode => "UC",
    TableName::Delcode => "DC",
    TableName::Stash => "ST",
    TableName::StashActive => "SA",
  }
}

/// Serialize a Stored value to a type-tag + data string.
/// Returns None if the value can't be serialized.
fn serialize_stored(stored: &Stored) -> Option<String> {
  match stored {
    Stored::None => Some("N".to_string()),
    Stored::Bool(b) => Some(format!("B\t{}", if *b { "1" } else { "0" })),
    Stored::Int(i) => Some(format!("I\t{}", i)),
    Stored::String(s) => Some(format!("S\t{}", url_encode(&arena::with(*s, |s| s.to_string())))),
    Stored::Charcode(c) => Some(format!("CH\t{}", c)),
    Stored::Catcode(cc) => Some(format!("CC\t{}", u8::from(*cc))),
    Stored::Token(t) => Some(format!("T\t{}", serialize_token(t))),
    Stored::Tokens(tks) => {
      let tok_strs: Vec<String> = tks.clone().unlist().iter().map(serialize_token).collect();
      Some(format!("TK\t{}", tok_strs.join(",")))
    }
    Stored::Expandable(exp) => {
      if let Some(crate::definition::ExpansionBody::Tokens(tks)) = exp.get_expansion() {
        let cs_name = exp.get_cs().with_str(|s| url_encode(s));
        let tok_strs: Vec<String> = tks.clone().unlist().iter().map(serialize_token).collect();
        let nargs = exp.get_num_args();
        let mut flags = String::new();
        if exp.is_long { flags.push('L'); }
        if exp.is_protected() { flags.push('P'); }
        Some(format!(
          "E\t{}\t{}\t{}\t{}",
          cs_name, nargs, flags, tok_strs.join(",")
        ))
      } else {
        Option::None // Closure-based, can't serialize
      }
    }
    Stored::Dimension(d) => Some(format!("D\t{}", d.0)),
    Stored::Glue(g) => {
      let mut s = format!("G\t{}", g.skip);
      if let Some(p) = g.plus { s.push_str(&format!(",p{}", p)); }
      if let Some(ref pf) = g.pfill { s.push_str(&format!(",pf{}", fillcode_index(pf))); }
      if let Some(m) = g.minus { s.push_str(&format!(",m{}", m)); }
      if let Some(ref mf) = g.mfill { s.push_str(&format!(",mf{}", fillcode_index(mf))); }
      Some(s)
    }
    Stored::MuDimension(d) => Some(format!("MD\t{}", d.0)),
    Stored::MuGlue(g) => {
      let mut s = format!("MG\t{}", g.skip);
      if let Some(p) = g.plus { s.push_str(&format!(",p{}", p)); }
      if let Some(ref pf) = g.pfill { s.push_str(&format!(",pf{}", fillcode_index(pf))); }
      if let Some(m) = g.minus { s.push_str(&format!(",m{}", m)); }
      if let Some(ref mf) = g.mfill { s.push_str(&format!(",mf{}", fillcode_index(mf))); }
      Some(s)
    }
    Stored::VecDequeStored(vd) if vd.is_empty() => Some("VD\t".to_string()),
    _ => Option::None,
  }
}

fn fillcode_index(fc: &crate::common::glue::FillCode) -> usize {
  use crate::common::glue::FillCode::*;
  match fc { Fil => 1, Fill => 2, Filll => 3 }
}

fn serialize_token(t: &crate::token::Token) -> String {
  let cc: u8 = t.get_catcode().into();
  let text = t.with_str(|s| url_encode(s));
  format!("{}:{}", cc, text)
}

fn url_encode(s: &str) -> String {
  let mut result = String::with_capacity(s.len());
  for ch in s.chars() {
    match ch {
      '\t' => result.push_str("%09"),
      '\n' => result.push_str("%0A"),
      '\r' => result.push_str("%0D"),
      '%' => result.push_str("%25"),
      ',' => result.push_str("%2C"),
      _ if ch.is_ascii_control() => {
        result.push_str(&format!("%{:02X}", ch as u8));
      }
      _ => result.push(ch),
    }
  }
  result
}
