//! Writer for Rust-native kernel dump files.
//!
//! Serializes the State diff (from snapshot/diff_from_snapshot) into a
//! compact text format that can be loaded back efficiently.
//!
//! This is the "DumpFile" equivalent from Perl's TeX_Job.pool.ltxml.
//! The workflow follows Perl's Makefile.PL "make formats" scaffold:
//!   1. take_snapshot() — before processing latex.ltx
//!   2. Process latex.ltx through the engine
//!   3. diff_snapshot() — find what changed
//!   4. write_dump() — serialize the diff
//!   5. At runtime: load_dump() restores the state

use std::io::Write;
use std::path::Path;

use crate::common::arena;
use crate::common::numeric_ops::NumericOps;
use crate::common::store::Stored;
use crate::definition::Definition; // trait for get_expansion(), get_cs(), etc.
use crate::state::TableName;

/// Write a state diff to a dump file.
/// Returns the number of entries successfully written.
///
/// Writes in three ordered sections, matching Perl's
/// `TeX_Job.pool.ltxml::DumpFile` which separates
/// `@cmds_early` / `@cmds` / `@cmds_late`:
///
///   1. **regular** — V / M:E / M:T / R / C / LC / UC / SC / MC / DC
///      entries (data, expandable definitions, registers, codes).
///   2. **let-aliases** — M:PA / M:MPA entries (`\let <key> <target>`).
///      Emitted last so that by the time the reader processes an alias,
///      its target has been installed either by `_base.rs` at runtime or
///      by a regular entry earlier in this dump.
///
/// This ordering matters for Perl-parity let-alias chains (`\tex_let:D →
/// \let`, `\tex_def:D → \def`, …). Without it, the reader might try to
/// alias against a target that's still undefined. See SYNC_STATUS D0
/// (d.2).
pub fn write_dump(
  path: &Path,
  entries: &[(TableName, crate::common::arena::SymStr, Stored)],
) -> Result<usize, String> {
  let mut file = std::fs::File::create(path)
    .map_err(|e| format!("Failed to create dump file: {}", e))?;

  writeln!(file, "# latexml-oxide kernel dump v1").ok();
  writeln!(file, "# Generated by dump_writer, {} entries", entries.len()).ok();

  // Pre-serialize + partition into (regular, let-aliases). Skipped keys
  // (ver@..., unserializable values) fall out naturally.
  let mut regular: Vec<(String, String, String)> = Vec::new();
  let mut aliases: Vec<(String, String, String)> = Vec::new();
  let mut skipped = 0usize;

  for (table, key, value) in entries {
    let table_code = table_to_code(*table);
    let key_str = arena::with(*key, |s| s.to_string());

    // Skip \ver@ package version markers (runtime metadata, not definitions)
    if key_str.starts_with("\\ver@") {
      skipped += 1;
      continue;
    }

    let Some(serialized) = serialize_stored(value) else {
      skipped += 1;
      continue;
    };

    // A let-alias entry is an M row whose serialized form starts with
    // `PA\t` or `MPA\t`. Nothing else produces those prefixes.
    let is_alias = matches!(*table, TableName::Meaning)
      && (serialized.starts_with("PA\t") || serialized.starts_with("MPA\t"));

    let row = (table_code.to_string(), url_encode(&key_str), serialized);
    if is_alias {
      aliases.push(row);
    } else {
      regular.push(row);
    }
  }

  writeln!(file, "# Section 1: regular entries ({})", regular.len()).ok();
  for (t, k, v) in &regular {
    writeln!(file, "{}\t{}\t{}", t, k, v)
      .map_err(|e| format!("Write error: {}", e))?;
  }
  writeln!(file, "# Section 2: let-aliases ({}) — applied after regular",
    aliases.len()).ok();
  for (t, k, v) in &aliases {
    writeln!(file, "{}\t{}\t{}", t, k, v)
      .map_err(|e| format!("Write error: {}", e))?;
  }

  let count = regular.len() + aliases.len();
  writeln!(file, "# Written: {}, Skipped: {}", count, skipped).ok();
  eprintln!(
    "[dump_writer] Wrote {} entries to {} ({} skipped; {} regular + {} let-aliases)",
    count,
    path.display(),
    skipped,
    regular.len(),
    aliases.len(),
  );

  Ok(count)
}

fn table_to_code(t: TableName) -> &'static str {
  match t {
    TableName::Meaning => "M",
    TableName::Value => "V",
    TableName::Catcode => "C",
    TableName::Mathcode => "MC",
    TableName::Sfcode => "SC",
    TableName::Lccode => "LC",
    TableName::Uccode => "UC",
    TableName::Delcode => "DC",
    TableName::Stash => "ST",
    TableName::StashActive => "SA",
  }
}

/// Serialize a Stored value to a type-tag + data string.
/// Returns None if the value can't be serialized.
fn serialize_stored(stored: &Stored) -> Option<String> {
  match stored {
    Stored::None => Some("N".to_string()),
    Stored::Bool(b) => Some(format!("B\t{}", if *b { "1" } else { "0" })),
    Stored::Int(i) => Some(format!("I\t{}", i)),
    Stored::String(s) => Some(format!("S\t{}", url_encode(&arena::with(*s, |s| s.to_string())))),
    Stored::Charcode(c) => Some(format!("CH\t{}", c)),
    Stored::Catcode(cc) => Some(format!("CC\t{}", u8::from(*cc))),
    Stored::Token(t) => Some(format!("T\t{}", serialize_token(t))),
    Stored::Tokens(tks) => {
      let tok_strs: Vec<String> = tks.clone().unlist().iter().map(serialize_token).collect();
      Some(format!("TK\t{}", tok_strs.join(",")))
    }
    Stored::Expandable(exp) => {
      if let Some(crate::definition::ExpansionBody::Tokens(tks)) = exp.get_expansion() {
        let cs_name = exp.get_cs().with_str(url_encode);
        let tok_strs: Vec<String> = tks.clone().unlist().iter().map(serialize_token).collect();
        let nargs = exp.get_num_args();
        let mut flags = String::new();
        if exp.is_long { flags.push('L'); }
        if exp.is_protected() { flags.push('P'); }
        Some(format!(
          "E\t{}\t{}\t{}\t{}",
          cs_name, nargs, flags, tok_strs.join(",")
        ))
      } else {
        Option::None // Closure-based, can't serialize
      }
    }
    // Closure-based primitives can't be serialized directly — but if the entry's
    // CS differs from the primitive's own CS, it's a `\let`-alias, and we CAN
    // capture the alias so the dump reader can replay `\let <key> <target>` at
    // load time. This is how `\tex_let:D`, `\tex_def:D`, and hundreds of other
    // expl3-renamed primitives stay reachable across dump boundaries (the
    // defining assignment `\let \tex_let:D \let` in expl3-code.tex needs to
    // survive the dump for `\usepackage{expl3}`'s guard `\ifx\csname
    // tex_let:D\endcsname\relax` to short-circuit).
    //
    // NOTE: the KEY we're saving IS the dump entry's first column; the VALUE
    // we write is the primitive's OWN CS name. Dump reader compares these:
    // if equal, it's the "primary" primitive (already in bindings) and skipped;
    // if different, it's an alias — replay `\let` at load time.
    Stored::Primitive(p) => {
      let target_cs = p.cs.with_str(url_encode);
      Some(format!("PA\t{}", target_cs))
    }
    Stored::MathPrimitive(p) => {
      let target_cs = p.cs.with_str(url_encode);
      Some(format!("MPA\t{}", target_cs))
    }
    Stored::Register(reg) => {
      // Register: serialize as R\tCS\tTYPE\tVALUE[\tMATHGLYPH]
      // Only serialize simple registers without getter/setter closures
      if reg.getter.is_some() || reg.setter.is_some() {
        return Option::None; // Has closures, can't serialize
      }
      let cs_name = reg.cs.with_str(url_encode);
      let rtype = match reg.register_type {
        crate::definition::register::RegisterType::Number => "N",
        crate::definition::register::RegisterType::Dimension => "D",
        crate::definition::register::RegisterType::Glue => "G",
        crate::definition::register::RegisterType::MuGlue => "MG",
        crate::definition::register::RegisterType::Tokens => "TK",
        crate::definition::register::RegisterType::CharDef => "CD",
        _ => return Option::None,
      };
      let value_str = match &reg.value {
        Some(crate::definition::register::RegisterValue::Number(n)) => n.value_of().to_string(),
        Some(crate::definition::register::RegisterValue::Dimension(d)) => d.value_of().to_string(),
        Some(crate::definition::register::RegisterValue::Glue(g)) => {
          let mut s = g.skip.to_string();
          if let Some(p) = g.plus { s.push_str(&format!(",p{}", p)); }
          if let Some(ref pf) = g.pfill { s.push_str(&format!(",pf{}", fillcode_index(pf))); }
          if let Some(m) = g.minus { s.push_str(&format!(",m{}", m)); }
          if let Some(ref mf) = g.mfill { s.push_str(&format!(",mf{}", fillcode_index(mf))); }
          s
        }
        Some(crate::definition::register::RegisterValue::Tokens(tks)) => {
          let tok_strs: Vec<String> = tks.clone().unlist().iter().map(serialize_token).collect();
          tok_strs.join(",")
        }
        _ => "0".to_string(),
      };
      let mut s = format!("R\t{}\t{}\t{}", cs_name, rtype, value_str);
      if let Some(glyph) = reg.mathglyph {
        s.push_str(&format!("\t{}", glyph as u32));
      }
      Some(s)
    }
    Stored::Number(n) => Some(format!("I\t{}", n.value_of())),
    Stored::Float(f) => Some(format!("F\t{}", f.0)),
    Stored::Dimension(d) => Some(format!("D\t{}", d.0)),
    Stored::Glue(g) => {
      let mut s = format!("G\t{}", g.skip);
      if let Some(p) = g.plus { s.push_str(&format!(",p{}", p)); }
      if let Some(ref pf) = g.pfill { s.push_str(&format!(",pf{}", fillcode_index(pf))); }
      if let Some(m) = g.minus { s.push_str(&format!(",m{}", m)); }
      if let Some(ref mf) = g.mfill { s.push_str(&format!(",mf{}", fillcode_index(mf))); }
      Some(s)
    }
    Stored::MuDimension(d) => Some(format!("MD\t{}", d.0)),
    Stored::MuGlue(g) => {
      let mut s = format!("MG\t{}", g.skip);
      if let Some(p) = g.plus { s.push_str(&format!(",p{}", p)); }
      if let Some(ref pf) = g.pfill { s.push_str(&format!(",pf{}", fillcode_index(pf))); }
      if let Some(m) = g.minus { s.push_str(&format!(",m{}", m)); }
      if let Some(ref mf) = g.mfill { s.push_str(&format!(",mf{}", fillcode_index(mf))); }
      Some(s)
    }
    Stored::VecDequeStored(vd) if vd.is_empty() => Some("VD\t".to_string()),
    _ => Option::None,
  }
}

fn fillcode_index(fc: &crate::common::glue::FillCode) -> usize {
  use crate::common::glue::FillCode::*;
  match fc { Fil => 1, Fill => 2, Filll => 3 }
}

fn serialize_token(t: &crate::token::Token) -> String {
  let cc: u8 = t.get_catcode().into();
  let text = t.with_str(url_encode);
  format!("{}:{}", cc, text)
}

fn url_encode(s: &str) -> String {
  let mut result = String::with_capacity(s.len());
  for ch in s.chars() {
    match ch {
      '\t' => result.push_str("%09"),
      '\n' => result.push_str("%0A"),
      '\r' => result.push_str("%0D"),
      '%' => result.push_str("%25"),
      ',' => result.push_str("%2C"),
      _ if ch.is_ascii_control() => {
        result.push_str(&format!("%{:02X}", ch as u8));
      }
      _ => result.push(ch),
    }
  }
  result
}
