use std::collections::HashMap;
use state::{Scope, State, ObjectStore};
use common::error::*;
use {Digested, TexMode};
use mouth::Mouth;
use gullet::Gullet;
use tokens::Tokens;
use token::{Token, Catcode};
use definition::Definition;
use tbox::*;
use list::List;

static MAXSTACK: usize = 200;

pub struct Stomach {
  pub gullet: Gullet,
  token_stack: Vec<Token>,
  boxing: Vec<Token>,
}

impl Default for Stomach {
  fn default() -> Self {
    Stomach {
      gullet: Gullet::default(),
      token_stack: Vec::new(),
      boxing: Vec::new(),
    }
  }
}

impl Stomach {
  pub fn get_gullet_mut(&mut self) -> &mut Gullet {
    &mut self.gullet
  }
  pub fn get_gullet(&self) -> &Gullet {
    &self.gullet
  }

  // **********************************************************************
  // Digestion
  // **********************************************************************
  // NOTE: Worry about whether the $autoflush thing is right?
  // It puts a lot of cruft in Gullet; Should we just create a new Gullet?
  pub fn digest_next_body(&mut self, _terminal: bool, state: &mut State) -> Result<Vec<Digested>> {
    let _start_location = self.get_locator();
    let init_depth = self.boxing.len();
    let mut read_token: Option<Token>;
    let mut box_list: Vec<Digested> = Vec::new();
    let mut read_token_was_none = false; // TODO: make idiomatic rust here

    loop {
      read_token = try!(self.get_gullet_mut().read_x_token(true, true, state));
      match read_token {
        None => {
          read_token_was_none = true;
          break;
        },
        Some(token) => {
          box_list.extend(try!(self.invoke_token(token, state)));
          // TODO:
          // if terminal.is_some() && Equals(token, terminal)
          if init_depth > self.boxing.len() {
            break;
          }
        }
      };
    }

    // Warn('expected', $terminal, self, "body should have ended with '" . ToString($terminal) . "'",
    // "current body started at " . ToString($startloc))
    // if $terminal && !Equals($token, $terminal);

    if read_token_was_none {
      box_list.push(Digested::Box(Tbox::default())); // Dummy `trailer' if none explicit.
    }
    Ok(box_list)
  }

  // Digest a list of tokens independent from any current Gullet.
  // Typically used to digest arguments to primitives or constructors.
  // Returns a List containing the digested material.
  pub fn digest(&mut self, tokens : Tokens, state: &mut State) -> Result<Digested> {
    self.reading_from_mouth(Mouth::default(), state, Box::new(move |stomach, state| {
      stomach.get_gullet_mut().unread(tokens.clone().unlist());
      state.clear_prefixes(); // prefixes shouldn't apply here.
      let mode;
      {
        let ismath = state.lookup_value("IN_MATH");
        mode = match ismath {
           Some(&ObjectStore::Bool(true)) => TexMode::Math,
          _ => TexMode::Text
        };
      }
      let initdepth = stomach.boxing.len();
      let depth     = initdepth;
      // {
      //   let list = STOMACH_LIST.lock()
      //   *list = Rc::new(Vec::new());
      // }
      let mut list = Vec::new();
      while let Some(token) = try!(stomach.get_gullet_mut().read_x_token(true, true, state)) { // Done if we run out of tokens
        // {
        //   let list = STOMACH_LIST.lock()
        list.extend(try!(stomach.invoke_token(token, state)));
        // }

        if initdepth > stomach.boxing.len() { // if we've closed the initial mode.
          break;
        }
        if initdepth < depth {
          // TODO
          error!(target: "Fatal:internal:<EOF>", "We've fallen off the end, somehow !?!?!?");
          //     Fatal('internal', '<EOF>', self,
          //       "We've fallen off the end, somehow!?!?!",
          //       "Last token " . ToString($LaTeXML::CURRENT_TOKEN)
          //         . " (Boxing depth was $initdepth, now $depth: Boxing generated by "
          //         . join(', ', map { ToString($_) } @{ $self{boxing} }))
          //       if $initdepth < $depth;
        }
      }

      // let list = STOMACH_LIST.lock()
      let final_list = list;
      Ok(Digested::List(List{boxes: final_list, mode: mode}))
    }))
  }

  pub fn get_locator(&self) -> String {
    "fake stomach locator".to_string()
  }

  /// Invoke a token;
  /// If it is a primitive or constructor, the definition will be invoked,
  /// possibly arguments will be parsed from the Gullet.
  /// Otherwise, the token is simply digested: turned into an appropriate box.
  /// Returns a list of boxes/whatsits.
  pub fn invoke_token(&mut self, input_token: Token, state: &mut State) -> Result<Vec<Digested>> {
    let mut maybe_token = Some(input_token);

    // Overly complex, but want to avoid recursion/stack
    let mut result: Vec<Digested> = Vec::new();
    // INVOKE:
    while let Some(token) = maybe_token {

      self.token_stack.push(token.clone());
      if self.token_stack.len() > MAXSTACK {
        // Fatal('internal', '<recursion>', self,
        //   "Excessive recursion(?): ",
        //   "Tokens on stack: " . join(', ', map { ToString($_) } @{ $self{token_stack} })); }
      }
      state.current_token = Some(token.clone());
      result = Vec::new();
      let looked_up_definition: Option<ObjectStore> = state.lookup_digestable_definition(&token);
      match looked_up_definition {
        None => {
          // Supposedly executable token, but no definition!
          result = self.invoke_token_undefined(token, state);
        }
        Some(store) => {
          match store {
            ObjectStore::Token(meaning) => {
              // Common case
              result = self.invoke_token_simple(token.clone(), meaning, state);
            }
            ObjectStore::Expandable(meaning) => {
              // A math-active character will (typically) be a macro,
              // but it isn't expanded in the gullet, but later when digesting, in math mode (? I think)
              let invoked_meaning = try!(meaning.invoke(&mut self.gullet, state));
              self.gullet.unread(invoked_meaning);
              maybe_token = try!(self.gullet.read_x_token(true, false, state)); // replace the token by it's expansion!!!
              self.token_stack.pop();
              continue;
            }
            ObjectStore::Constructor(meaning) => {
              // Otherwise, a normal primitive or constructor
              result = try!(meaning.invoke_primitive(self, meaning.clone(), state));
              if !meaning.is_prefix() {
                state.clear_prefixes(); // Clear prefixes unless we just set one.
              }
            },
            ObjectStore::Primitive(meaning) => {
              // Otherwise, a normal primitive or constructor
              result = try!(meaning.invoke_primitive(self, meaning.clone(), state));
              if !meaning.is_prefix() {
                state.clear_prefixes(); // Clear prefixes unless we just set one.
              }
            }
            _ => {
              // TODO:
              // Fatal('misdefined', $meaning, self, "The object " . Stringify($meaning) . " should never reach Stomach!");
            }
          };
        }
      };
      break;
    }

    // TODO:
    // if grep { (!ref $_) || (!$_->isaBox) } @result {
    //   Fatal('misdefined', $token, self,
    //   "Execution yielded non boxes",
    //   "Returned " . join(',', map { "'" . Stringify($_) . "'" }
    //       grep { (!ref $_) || (!$_->isaBox) } @result))
    // }

    self.token_stack.pop();
    Ok(result)
  }

  fn invoke_token_undefined(&mut self, _token: Token, _state: &mut State) -> Vec<Digested> {
    // log!("-- Undefined invoke {:?}", token);
    // TODO: Rework this carefully
    Vec::new()
  }
  fn invoke_token_simple(&mut self, _token: Token, meaning: Token, state: &mut State) -> Vec<Digested> {
    // log!("-- Simple invoke {:?}", token);
    // let font = state.lookup_value("font");
    state.clear_prefixes();    // prefixes shouldn't apply here.

    if meaning.code == Catcode::SPACE {
      let in_math_lookup: Option<&ObjectStore> = state.lookup_value("IN_MATH");
      let in_math = match in_math_lookup {
        Some(&ObjectStore::Bool(x)) => x,
        _ => false,
      };
      let in_preamble_lookup: Option<&ObjectStore> = state.lookup_value("inPreamble");
      let in_preamble = match in_preamble_lookup {
        Some(&ObjectStore::Bool(x)) => x,
        _ => false,
      };
      if in_math || in_preamble {
        Vec::new()
      } else {
        vec![Digested::Box(Tbox {
               text: meaning.to_string(),
               font: String::new(),
               locator: self.gullet.get_locator(),
               tokens: vec![meaning],
               properties: HashMap::new(),
             })]
      }
    } else if meaning.code == Catcode::COMMENT {
      // Note: Comments need char decoding as well!
      //  let comment = LaTeXML::Package::FontDecodeString($meaning->getString, undef, 1);
      // // However, spaces normally would have be digested away as positioning...
      // let badspace = pack('U', 0xA0) . "\x{0335}";    // This is at space's pos in OT1
      // $comment =~ s/\Q$badspace\E/ /g;
      // return LaTeXML::Comment->new($comment); }
      Vec::new()
    }
    // TODO
    // else if ($forbidden_cc[meaning.code]) {
    // Fatal('misdefined', $token, self,
    //   "The token " . Stringify($token) . " should never reach Stomach!");
    // return; }
    else {
      vec![Digested::Box(Tbox {
             text: meaning.to_string(),
             font: String::new(),
             locator: String::new(),
             tokens: vec![meaning],
             properties: HashMap::new(),
           })]
    }
  }

  // Do something, while reading stuff from a specific Mouth.
  // This reads ONLY from that mouth (or any mouth openned by code in that source),
  // and the mouth should end up empty afterwards, and only be closed here.
  pub fn reading_from_mouth<R>(&mut self, mouth: Mouth, state: &mut State,
                            reader: Box<Fn(&mut Stomach, &mut State) -> R>) -> R {
    let mouth_source = mouth.source.clone();
    {
      let gullet = self.get_gullet_mut();
      gullet.open_mouth(mouth, false);  // only allow mouth to be explicitly closed here.
    }
    let results : R = reader(self, state);
    let gullet = self.get_gullet_mut();
    // `mouth` must still be open, with (at worst) empty autoclosable mouths in front of it
    loop {
      let mut is_mouth = false;
      {
        if let Some(ref mut runtime) = gullet.mouth {
          if runtime.mouth.source == mouth_source {
            is_mouth = true;
          }
        } else {
          error!(target: "unexpected:runtime", "TODO: gullet had no active runtime");
          break;
        }
      }
      if is_mouth {
        gullet.close_mouth(true, state);
        break;
      } else if gullet.mouthstack.is_empty() {
        error!(target: "unexpected:<closed>", "TODO: Mouth is unexpectedly already closed");
        // Error('unexpected', '<closed>', $gullet, "Mouth is unexpectedly already closed",
        //   "Reading from " . Stringify($mouth) . ", but it has already been closed.");
        break;
      }
      else {
        let mut ready_to_read = false;
        { if let Some(ref mut runtime) = gullet.mouth {
            if !runtime.autoclose || !runtime.pushback.is_empty() || runtime.mouth.has_more_input() {
              ready_to_read = true;
            }
          }
        }
        if ready_to_read {
          let _next = gullet.read_token(state); // stringify( ?
          error!(target: "unexpected:next", "TODO: unexpected input remaining");
          // Error('unexpected', $next, $gullet, "Unexpected input remaining: '$next'",
          //   "Finished reading from " . Stringify($mouth) . ", but it still has input.");
          { if let Some(ref mut runtime) = gullet.mouth {
              runtime.mouth.finish(state);
            }
          }
          gullet.close_mouth(true, state);
        } // ?? if we continue?
        else {
          gullet.close_mouth(false, state);
        }
      }
    }
    results
  }



  //**********************************************************************
  // Maintaining State.
  //**********************************************************************
  // State changes that the Stomach needs to moderate and know about (?)

  //======================================================================
  // Dealing with TeX's bindings & grouping.
  // Note that lookups happen more often than bgroup/egroup (which open/close frames).

  pub fn push_stack_frame(&mut self, nobox: bool, state: &mut State) {
    let current_token = match state.current_token {
      Some(ref t) => t.clone(),
      _ => T_OTHER!(String::new())
    };

    state.push_frame();
    state.assign_value("beforeAfterGroup"      , ObjectStore::VecDigested(Vec::new()), Some(Scope::Local));  // ALWAYS bind this!
    state.assign_value("afterGroup"            , ObjectStore::VecDigested(Vec::new()), Some(Scope::Local));  // ALWAYS bind this!
    state.assign_value("afterAssignment"       , ObjectStore::VecDigested(Vec::new()), Some(Scope::Local));  // ALWAYS bind this!
    state.assign_value("groupNonBoxing"        , ObjectStore::Bool(nobox),             Some(Scope::Local));  // ALWAYS bind this!
    state.assign_value("groupInitiator"        , ObjectStore::Token(current_token.clone()), Some(Scope::Local));
    // state.assign_value("groupInitiatorLocator" , self.getLocator,       Scope::Local);
    if !nobox {
      self.boxing.push(current_token)  // For begingroup/endgroup
    }
  }

  pub fn pop_stack_frame(&mut self, nobox: bool, state: &mut State) -> Result<()> {
    if let Some(ObjectStore::VecToken(beforeafter)) = state.remove_value("beforeAfterGroup") {
      if !beforeafter.is_empty() {
        let _result = beforeafter.into_iter().map(|t| t.be_digested(self, state)).collect::<Vec<_>>();
        // if (my ($x) = grep { !$_->isaBox } @result) {
        //   Fatal('misdefined', $x, $self, "Expected a Box|List|Whatsit, but got '" . Stringify($x) . "'"); }
        // push(@LaTeXML::LIST, @result); }
      }
    }
    let after = state.remove_value("afterGroup");
    state.pop_frame();
    if !nobox {
      self.boxing.pop(); // For begingroup/endgroup
    }
    if let Some(ObjectStore::VecToken(after)) = after {
      if !after.is_empty() {
        self.gullet.unread(after);
      }
    }
    Ok(())
  }

  pub fn current_frame_message(&self) -> String {
    // return "current frame is "
    //   . (state.isValueBound('MODE', 0)       // SET mode in CURRENT frame ?
    //   ? "mode-switch to " . state.lookup_value('MODE')
    //   : (state.lookup_value('groupNonBoxing')    // Current frame is a non-boxing group?
    //     ? "non-boxing" : "boxing") . " group")
    //   . " due to " . Stringify(state.lookup_value('groupInitiator'))
    //   . " " . ToString(state.lookup_value('groupInitiatorLocator')); }
    "current frame is mock".to_string()
  }


  //======================================================================
  // Grouping pushes a new stack frame for binding definitions, etc.
  //======================================================================

  /// if $nobox is true, inhibit incrementing the boxingLevel
  pub fn bgroup(&mut self, state: &mut State) {
    self.push_stack_frame(false, state);
  }

  pub fn egroup(&mut self, state: &mut State) -> Result<()> {
    // if state.is_value_bound("MODE", Some(0))   // Last stack frame was a mode switch!?!?!
    //   || state.lookup_value("groupNonBoxing") {    // or group was opened with \begingroup
    //     error!("unexpected:{:?}: Attempt to close boxing group", state.lookup_value("CURRENT_TOKEN"));
    //   // Error('unexpected', $LaTeXML::CURRENT_TOKEN, self, "Attempt to close boxing group",
    //   //   self.currentFrameMessage); }
    // }
    // else {    // Don't pop if there's an error; maybe we'll recover?
    self.pop_stack_frame(false, state)
    // }
  }

  pub fn begingroup(&mut self, state: &mut State) {
    self.push_stack_frame(true, state);
  }

  pub fn endgroup(&mut self, state: &mut State) -> Result<()> {
    // if state.is_value_bound("MODE", Some(0))    // Last stack frame was a mode switch!?!?!
    //   || state.lookup_value("groupNonBoxing").is_none() {    // or group was opened with \bgroup
    //     error!("unexpected:{:?}: Attempt to close non-boxing group", state.lookup_value("CURRENT_TOKEN"));
    //     // Error('unexpected', $LaTeXML::CURRENT_TOKEN, self, "Attempt to close non-boxing group",
    //     // self.currentFrameMessage); }
    // }
    // else {    // Don't pop if there's an error; maybe we'll recover?
      self.pop_stack_frame(true, state)
    //}
  }

  //======================================================================
  // Mode (minimal so far; math vs text)
  // Could (should?) be taken up by Stomach by building horizontal, vertical or math lists ?

  pub fn begin_mode(&mut self, mode: &str, state: &mut State) -> Result<()> {
    self.push_stack_frame(false, state);    // Effectively bgroup
    // let prevmode = state.lookup_string("MODE");
    let ismath   = mode.ends_with("math");
    state.assign_value("MODE", ObjectStore::String(mode.to_string()), Some(Scope::Local));
    state.assign_value("IN_MATH", ObjectStore::Bool(ismath), Some(Scope::Local));
    // let curfont = state.lookup_value("font");
    // if mode == prevmode { }
    // else if ismath {
      // When entering math mode, we set the font to the default math font,
      // and save the text font for any embedded text.
      // if let Some(cf) = curfont {
      //   state.assign_value("savedfont", cf.clone(), Some(Scope::Local));
      // }
      // TODO:
      // state.assign_value(font, state.lookup_value("mathfont").merge(
      //     color => $curfont->getColor, background => $curfont->getBackground,
      //     size => $curfont->getSize,
      //     mathstyle => ($mode =~ /^display/ ? "display" : "text")), Some(Scope::Local));
    // } else {
      // When entering text mode, we should set the font to the text font in use before the math
      // but inherit color and size
      // TODO:
      // state.assign_value("font", state.lookup_value("savedfont")->merge(
      //     color => $curfont->getColor, background => $curfont->getBackground,
      //     size => $curfont->getSize), Some(Scope::Local));
    // }
    Ok(())
  }

  pub fn end_mode(&mut self, mode: &str, state: &mut State) -> Result<()> {
    if !state.is_value_bound("MODE", Some(0))    // Last stack frame was NOT a mode switch!?!?!
      || (state.lookup_string("MODE") != mode) {    // Or was a mode switch to a different mode
      error!(target: &format!("unexpected:{:?}",state.current_token), "Attempt to end mode")
        // self.currentFrameMessage);
    } else {    // Don"t pop if there"s an error; maybe we'll recover?
      try!(self.pop_stack_frame(false ,state));
    }    // Effectively egroup.
    Ok(())
  }

  //**********************************************************************
}
