use std::borrow::Cow;
use std::collections::{HashMap, VecDeque};
use std::sync::Arc;

use crate::common::error::*;
use crate::common::font;
use crate::common::font::Font;
use crate::common::locator::Locator;
use crate::common::object::Object;
use crate::common::store::Stored;
use crate::definition::constructor::Constructor;
use crate::definition::expandable::Expandable;
use crate::definition::Definition;
use crate::gullet::Gullet;
use crate::list::List;
use crate::mouth::{Mouth, MouthOptions};
use crate::state::{Scope, State};
use crate::tbox::*;
use crate::token::{Catcode, Token};
use crate::tokens::Tokens;
use crate::{Digested, TexMode};

static MAXSTACK: usize = 200;

#[derive(Default)]
pub struct Stomach {
  pub gullet: Gullet,
  pub token_stack: Vec<Arc<Token>>,
  pub boxing: Vec<Token>,
  pub box_list: Vec<Digested>,
}

impl Object for Stomach {
  fn get_locator(&self) -> Cow<Locator> { self.get_gullet().get_locator() }
  fn stringify(&self) -> String { String::from("TODO Stomach") }
}

impl<'t> Stomach {
  pub fn get_gullet_mut(&mut self) -> &mut Gullet { &mut self.gullet }
  pub fn get_gullet(&self) -> &Gullet { &self.gullet }
  pub fn regurgitate(&mut self) -> Vec<Digested> { self.box_list.drain(..).collect() }
  // **********************************************************************
  // Digestion
  // **********************************************************************
  // NOTE: Worry about whether the $autoflush thing is right?
  // It puts a lot of cruft in Gullet; Should we just create a new Gullet?
  pub fn digest_next_body(&mut self, terminal_opt: Option<Token>, state: &mut State) -> Result<Vec<Digested>> {
    let start_location = self.get_locator().into_owned();
    let init_depth = self.boxing.len();
    let mut found_terminal = false;
    let local_box_list = self.regurgitate(); // grab the current boxes to emulate local frame;

    // try reading a executable token
    while let Some(token) = self.get_gullet_mut().read_x_token(true, true, state)? {
      // info!(target:"stomach:digest_next:invoke_token","{:?}", token);
      let invoked = self.invoke_token(&token, state)?;
      self.box_list.extend(invoked);
      if let Some(ref terminal) = terminal_opt {
        if &token == terminal {
          found_terminal = true;
          break;
        }
      }
      if init_depth > self.boxing.len() {
        // info!(target:"digest_next_body","init_depth");
        break;
      }
    }

    // We ran out, terminate,
    // and add a Dummy `trailer' if none explicit.
    if init_depth <= self.boxing.len() {
      self.box_list.push(Digested::TBox(Arc::new(Tbox::default())));
      // info!(target:"digest_next_body","no_token");
    }

    if let Some(ref terminal) = terminal_opt {
      if !found_terminal {
        let message = s!("body should have ended with {:?}. current body started at {:?}", terminal, start_location);
        Warn!("expected", terminal, self, state, message);
      }
    }

    let final_box_list = self.regurgitate(); // grab the local boxes and return
    self.box_list = local_box_list; // swap back in the boxes of the initial local frame
    Ok(final_box_list)
  }

  // Digest a list of tokens independent from any current Gullet.
  // Typically used to digest arguments to primitives or constructors.
  // Returns a List containing the digested material.
  pub fn digest<T: Into<Tokens>>(&mut self, tokens: T, outer_state: &mut State) -> Result<Digested> {
    let mut tokens: Tokens = tokens.into();

    self.reading_from_mouth(Mouth::default(), outer_state, move |stomach, state| {
      let local_box_list = stomach.regurgitate(); // grab the current boxes to emulate local frame;

      stomach.get_gullet_mut().unread(tokens);
      state.clear_prefixes(); // prefixes shouldn't apply here.
      let mode = if state.lookup_bool("IN_MATH") { TexMode::Math } else { TexMode::Text };
      let initdepth = stomach.boxing.len();
      let depth = initdepth;

      while let Some(token) = stomach.get_gullet_mut().read_x_token(true, true, state)? {
        // Done if we run out of tokens
        // {
        //   let list = STOMACH_LIST.lock()
        // info!(target:"stomach:digest:invoke_token","{:?}", token);
        let mut invoked = stomach.invoke_token(&token, state)?;
        stomach.box_list.extend(invoked);
        // }

        if initdepth > stomach.boxing.len() {
          // if we've closed the initial mode.
          break;
        }
        if initdepth < depth {
          // TODO
          fatal!(Internal, EoF, "We've fallen off the end, somehow !?!?!?");
          //     Fatal('internal', '<EOF>', self,
          //       "We've fallen off the end, somehow!?!?!",
          //       "Last token " . ToString($LaTeXML::CURRENT_TOKEN)
          //         . " (Boxing depth was $initdepth, now $depth: Boxing generated by "
          //         . join(', ', map { ToString($_) } @{ $self{boxing} }))
          //       if $initdepth < $depth;
        }
      }

      let final_box_list = stomach.regurgitate(); // grab the local boxes and return
      stomach.box_list = local_box_list; // swap back in the boxes of the initial local frame

      let mut digested_list = List::new(final_box_list);
      digested_list.mode = Some(mode);
      digested_list.into()
    })
  }

  pub fn raw_tex(&mut self, text: &str, state: &mut State) -> Result<()> {
    // It could be as simple as this, except if catcodes get changed, it's too late!!!
    //  Digest(TokenizeInternal($text));
    let savedcc = state.lookup_catcode('@').unwrap_or(Catcode::OTHER);
    state.assign_catcode('@', Catcode::LETTER, None);
    let raw_tex_mouth = Mouth::new(
      text,
      Some(MouthOptions {
        fordefinitions: true,
        ..MouthOptions::default()
      }),
      state,
    )?;
    self.reading_from_mouth(raw_tex_mouth, state, move |stomach, state| -> Result<()> {
      while let Some(token) = stomach.get_gullet_mut().read_x_token(false, false, state)? {
        if token != T_SPACE!() {
          // info!(target:"raw_tex:invoke_token","{:?}", token);
          stomach.invoke_token(&token, state)?;
        }
      }
      Ok(())
    })?;

    state.assign_catcode('@', savedcc, None);
    Ok(())
  }

  /// Invoke a token;
  /// If it is a primitive or constructor, the definition will be invoked,
  /// possibly arguments will be parsed from the Gullet.
  /// Otherwise, the token is simply digested: turned into an appropriate box.
  /// Returns a list of boxes/whatsits.
  pub fn invoke_token<'a>(&mut self, input_token: &'a Token, state: &mut State) -> Result<Vec<Digested>> {
    let mut maybe_token: Option<Cow<'a, Token>> = Some(Cow::Borrowed(input_token));

    // Overly complex, but want to avoid recursion/stack
    let mut result: Vec<Digested> = Vec::new();
    // INVOKE:
    while maybe_token.is_some() {
      let token = Arc::new(maybe_token.take().unwrap().into_owned());
      // info!(target:"invoke_token", "{:?}", token);
      state.current_token = Some(Arc::clone(&token));
      self.token_stack.push(Arc::clone(&token));
      if self.token_stack.len() > MAXSTACK {
        fatal!(Stomach, Recursion, s!("Excessive recursion(?): Tokens on stack: {:?}", self.token_stack));
      }
      result = Vec::new();

      // Rust notes: It would be ideal if we could unify the cases for (Primtive, Constructor,
      // MathPrimitive), as well as (Expandable, Conditional) since the
      // API is identical. However, as the types are different, Rust
      // constrains us here, we need separate match arms for each
      // distinctly typed enum case.
      match state.lookup_digestable_definition(&token) {
        // should always return a value, self if no def
        Stored::Token(meaning) => {
          // Common case
          let cc = meaning.get_catcode();
          if cc == Catcode::CS {
            result = self.invoke_token_undefined(&token, state)?;
          } else if cc.is_absorbable() {
            if let Some(digested) = self.invoke_token_simple(&*token, meaning, state)? {
              result.push(digested);
            }
          } else {
            let message = s!("The token {:?} (catcode {:?}) should never reach Stomach!", token, cc);
            Error!("misdefined", token, self, state, &message);
            if let Some(digested) = self.invoke_token_simple(&*token, meaning, state)? {
              result.push(digested);
            }
          }
        },
        Stored::Expandable(meaning) => {
          // A math-active character will (typically) be a macro,
          // but it isn't expanded in the gullet, but later when digesting, in math mode
          // (? I think)
          let mut invoked_meaning = meaning.invoke(&mut self.gullet, false, state)?;
          if !invoked_meaning.is_empty() {
            self.gullet.unread(invoked_meaning);
          }
          // replace the token by it's expansion!!!
          maybe_token = self.gullet.read_x_token(true, false, state)?.map(Cow::Owned);
          self.token_stack.pop();
          continue;
        },
        Stored::Conditional(meaning) => {
          // Conditionals are "expandable", use the regular invoke.
          let mut invoked_meaning = meaning.invoke(&mut self.gullet, false, state)?;
          self.gullet.unread(invoked_meaning);
          maybe_token = self.gullet.read_x_token(true, false, state)?.map(Cow::Owned);
          self.token_stack.pop();
          continue;
        },
        Stored::Constructor(meaning) => {
          // Otherwise, a normal primitive or constructor
          result = meaning.invoke_primitive(self, meaning.clone(), state)?;
          if !meaning.is_prefix() {
            state.clear_prefixes(); // Clear prefixes unless we just set one.
          }
        },
        Stored::Primitive(meaning) => {
          // Otherwise, a normal primitive or constructor
          result = meaning.invoke_primitive(self, meaning.clone(), state)?;
          if !meaning.is_prefix() {
            state.clear_prefixes(); // Clear prefixes unless we just set one.
          }
        },
        Stored::MathPrimitive(meaning) => {
          // Copy of regular Primitive
          // Otherwise, a normal primitive or constructor
          result = meaning.invoke_primitive(self, meaning.clone(), state)?;
          if !meaning.is_prefix() {
            state.clear_prefixes(); // Clear prefixes unless we just set one.
          }
        },
        Stored::Register(meaning) => {
          // Registers are special primitives
          result = meaning.invoke_primitive(self, meaning.clone(), state)?;
          if !meaning.is_prefix() {
            state.clear_prefixes(); // Clear prefixes unless we just set one.
          }
        },
        meaning => {
          fatal!(Stomach, Misdefined, s!("The object {:?} should never reach Stomach!", meaning));
        },
      }
      break;
    }

    self.token_stack.pop();
    Ok(result)
  }

  fn invoke_token_undefined(&mut self, token: &'t Token, state: &mut State) -> Result<Vec<Digested>> {
    let cs = token.get_cs_name().to_owned(); // TODO: use the Cow directly
                                             // TODO: state.note_status("undefined", cs);

    // To minimize chatter, go ahead and define it...
    if cs.starts_with("\\if") {
      // Apparently an \ifsomething ???
      let name = cs.replace("\\if", "");
      let message = s!("The token {} is not defined.", token.stringify());
      Error!("undefined", token, self, state, &message, "Defining it now as with \\newif");
      // install stub definitions for new conditional
      let cs_clone = cs.clone();
      state.install_definition(
        Expandable::new(
          T_CS!(s!("\\{}true", name)),
          None,
          Tokens!(T_CS!("\\let"), T_CS!(cs_clone), T_CS!("\\iftrue")),
          None,
          state,
        ),
        None,
      );
      state.install_definition(
        Expandable::new(
          T_CS!(s!("\\{}false", name)),
          None,
          Tokens!(T_CS!("\\let"), T_CS!(cs), T_CS!("\\iffalse")),
          None,
          state,
        ),
        None,
      );

      let gullet = self.get_gullet_mut();
      state.let_i(token, T_CS!("\\iffalse"), None);
      gullet.unread_one(token.clone()); // Retry
      Ok(Vec::new())
    } else {
      let message = s!("The token {} is not defined.", token.stringify());
      Error!("undefined", token, self, state, &message, "Defining it now as <ltx:ERROR/>");
      let closure_cs = cs;
      state.install_definition(
        Constructor {
          cs: token.clone(),
          paramlist: None,
          replacement: Some(Arc::new(move |document, _args, _props, state| {
            document.make_error("undefined", &closure_cs, state)
          })),
          ..Constructor::default()
        },
        Some(Scope::Global),
      );
      // and then invoke it.
      self.invoke_token(token, state)
    }
  }

  fn invoke_token_simple(&mut self, token: &Token, meaning: Token, state: &mut State) -> Result<Option<Digested>> {
    let cc = meaning.get_catcode();
    let font = state.lookup_font();
    state.clear_prefixes(); // prefixes shouldn't apply here.
    match cc {
      Catcode::SPACE => {
        if state.lookup_bool("IN_MATH") {
          Ok(None)
        } else {
          Ok(Some(Digested::TBox(Arc::new(Tbox::new(
            meaning.to_string(),
            font,
            Some(self.gullet.get_locator().into_owned()),
            Tokens!(meaning),
            HashMap::new(),
            state,
          )))))
        }
      },
      Catcode::COMMENT => {
        unimplemented!()
      },
      _ => {
        let text = font::decode_string(meaning.get_string(), None, true, state);
        Ok(Some(Digested::TBox(Arc::new(Tbox::new(
          text,
          None,
          None,             // locator
          Tokens!(meaning), // tokens
          HashMap::new(),   // properties
          state,
        )))))
      },
    }
  }

  // Do something, while reading stuff from a specific Mouth.
  // This reads ONLY from that mouth (or any mouth openned by code in that source),
  // and the mouth should end up empty afterwards, and only be closed here.
  pub fn reading_from_mouth<R, FnR>(&mut self, mouth: Mouth, state: &mut State, mut reader: FnR) -> R
  where FnR: FnOnce(&mut Stomach, &mut State) -> R {
    let mouth_source = mouth.get_source().to_string();
    {
      let gullet = self.get_gullet_mut();
      gullet.open_mouth(mouth, false); // only allow mouth to be explicitly closed here.
    }
    let results: R = reader(self, state);
    let gullet = self.get_gullet_mut();
    // `mouth` must still be open, with (at worst) empty autoclosable mouths in front of it
    loop {
      let mut is_mouth = false;
      {
        if let Some(ref mut runtime) = gullet.mouth {
          if runtime.mouth.get_source() == mouth_source {
            is_mouth = true;
          }
        } else {
          Error!("unexpected", "runtime", self, state, "TODO: gullet had no active runtime");
          break;
        }
      }
      if is_mouth {
        gullet.close_mouth(true, state);
        break;
      } else if gullet.mouthstack.is_empty() {
        Error!("unexpected", "<closed>", self, state, "TODO: Mouth is unexpectedly already closed");
        // Error('unexpected', '<closed>', $gullet, "Mouth is unexpectedly already closed",
        //   "Reading from " . Stringify($mouth) . ", but it has already been closed.");
        break;
      } else {
        let mut stringify_mouth = String::new();
        let mut ready_to_read = false;
        {
          if let Some(ref mut runtime) = gullet.mouth {
            if !runtime.autoclose || !runtime.pushback.is_empty() || runtime.mouth.has_more_input() {
              ready_to_read = true;
              stringify_mouth = runtime.mouth.stringify();
            }
          }
        }
        if ready_to_read {
          let next = gullet.read_token(state);
          let message = s!("Unexpected input remaining: {:?}", next);
          let detail = s!("Finished reading from {}, but it still has input.", stringify_mouth);
          Error!("unexpected", "next", gullet, state, message, detail);
          {
            if let Some(ref mut runtime) = gullet.mouth {
              runtime.mouth.finish(state);
            }
          }
          gullet.close_mouth(true, state);
        }
        // ?? if we continue?
        else {
          gullet.close_mouth(false, state);
        }
      }
    }
    results
  }

  //**********************************************************************
  // Maintaining State.
  //**********************************************************************
  // State changes that the Stomach needs to moderate and know about (?)

  //======================================================================
  // Dealing with TeX's bindings & grouping.
  // Note that lookups happen more often than bgroup/egroup (which open/close frames).

  pub fn push_stack_frame(&mut self, nobox: bool, state: &mut State) {
    let current_token = match &state.current_token {
      Some(t) => (*t).clone(),
      _ => unimplemented!(), // should never happen?
    };

    state.push_frame();
    state.assign_value("beforeAfterGroup", Stored::VecDequeStored(VecDeque::new()), Some(Scope::Local)); // ALWAYS bind this!
    state.assign_value("afterGroup", Stored::VecDequeStored(VecDeque::new()), Some(Scope::Local)); // ALWAYS bind this!
    state.assign_value("afterAssignment", Stored::Tokens(Tokens!()), Some(Scope::Local)); // ALWAYS bind this!
    state.assign_value("groupNonBoxing", nobox, Some(Scope::Local)); // ALWAYS bind this!
    state.assign_value("groupInitiator", (*current_token).clone(), Some(Scope::Local));
    state.assign_value("groupInitiatorLocator", self.get_locator().into_owned(), Some(Scope::Local));
    if !nobox {
      // For begingroup/endgroup
      self.boxing.push((*current_token).clone())
    }
  }

  pub fn pop_stack_frame(&mut self, nobox: bool, state: &mut State) -> Result<()> {
    if let Some(Stored::Tokens(beforeafter)) = state.remove_value("beforeAfterGroup") {
      if !beforeafter.is_empty() {
        let mut result = Vec::new();
        for frametok in beforeafter.unlist().into_iter() {
          result.push(frametok.be_digested(self, state)?);
        }
        // TODO
        // if (my ($x) = grep { !$_->isaBox } @result) {
        // Fatal('misdefined', $x, $self, "Expected a Box|List|Whatsit, but got '" .
        // Stringify($x) . "'"); }
        self.box_list.extend(result);
      }
    }
    let after = state.remove_value("afterGroup");
    state.pop_frame()?;
    if !nobox {
      self.boxing.pop(); // For begingroup/endgroup
    }
    if let Some(Stored::VecDequeStored(after_entries)) = after {
      for entry in after_entries.into_iter().rev() {
        match entry {
          Stored::Tokens(t) => self.gullet.unread(t),
          Stored::Token(t) => self.gullet.unread_one(t),
          other => panic!(r"\aftergroup should be used with tokens, got instead: {:?}", other),
        };
      }
    }
    Ok(())
  }

  pub fn current_frame_message(&self) -> String {
    // return "current frame is "
    //   . (state.isValueBound('MODE', 0)       // SET mode in CURRENT frame ?
    //   ? "mode-switch to " . state.lookup_value('MODE')
    //   : (state.lookup_value('groupNonBoxing')    // Current frame is a non-boxing group?
    //     ? "non-boxing" : "boxing") . " group")
    //   . " due to " . Stringify(state.lookup_value('groupInitiator'))
    //   . " " . ToString(state.lookup_value('groupInitiatorLocator')); }
    s!("current frame is mock")
  }

  //======================================================================
  // Grouping pushes a new stack frame for binding definitions, etc.
  //======================================================================

  /// if $nobox is true, inhibit incrementing the boxingLevel
  pub fn bgroup(&mut self, state: &mut State) { self.push_stack_frame(false, state); }

  pub fn egroup(&mut self, state: &mut State) -> Result<()> {
    if state.lookup_bool("groupNonBoxing") {
      // or group was opened with \begingroup
      Error!(
        "unexpected",
        state.current_token.as_ref().unwrap(),
        self,
        state,
        "Attempt to close boxing group"
      );
    } else {
      // Don't pop if there's an error; maybe we'll recover?
      self.pop_stack_frame(false, state)?;
    }
    Ok(())
  }

  pub fn begingroup(&mut self, state: &mut State) { self.push_stack_frame(true, state); }

  pub fn endgroup(&mut self, state: &mut State) -> Result<()> {
    if !state.lookup_bool("groupNonBoxing") {
      // or group was opened with \bgroup
      Error!(
        "unexpected",
        state.current_token.as_ref().unwrap().to_string(),
        self,
        state,
        s!("Attempt to close non-boxing group {}", self.current_frame_message())
      );
    } else {
      self.pop_stack_frame(true, state)?;
    }
    Ok(())
  }

  //======================================================================
  // Mode (minimal so far; math vs text)
  // Could (should?) be taken up by Stomach by building horizontal, vertical or math lists ?

  pub fn begin_mode(&mut self, mode: &str, state: &mut State) -> Result<()> {
    self.push_stack_frame(false, state); // Effectively bgroup
    let prevmode = state.lookup_string("MODE");
    let ismath = mode.ends_with("math");
    let isdisplay = mode.starts_with("display");
    state.assign_value("MODE", mode.to_string(), Some(Scope::Local));
    state.assign_value("IN_MATH", ismath, Some(Scope::Local));
    let curfont = state.lookup_font();
    if let Some(cf) = curfont {
      if mode == prevmode {
      } else if ismath {
        // When entering math mode, we set the font to the default math font,
        // and save the text font for any embedded text.
        state.assign_value("savedfont", cf.clone(), Some(Scope::Local));
        let new_font = state.lookup_mathfont().unwrap().merge(Font {
          color: cf.color.clone(),
          bg: cf.bg.clone(),
          size: cf.size,
          mathstyle: if isdisplay { Some("display".into()) } else { Some("text".into()) },
          ..Font::default()
        });
        state.assign_value("font", new_font, Some(Scope::Local));
      } else {
        // When entering text mode, we should set the font to the text font in use before the math
        // but inherit color and size
        let new_font = if let Some(&Stored::Font(ref saved_font)) = state.lookup_value("savedfont") {
          Some(saved_font.merge(Font {
            color: cf.color.clone(),
            bg: cf.bg.clone(),
            size: cf.size,
            ..Font::default()
          }))
        } else {
          None
        };
        if let Some(nf) = new_font {
          state.assign_value("font", nf, Some(Scope::Local));
        }
      }
    }
    Ok(())
  }

  pub fn end_mode(&mut self, mode: &str, state: &mut State) -> Result<()> {
    // Last stack frame was NOT a mode switch!?!?!
    if !state.is_value_bound("MODE", Some(0)) || (state.lookup_string("MODE") != mode) {
      // Or was a mode switch to a different mode
      let message = s!("Attempt to end mode {} in {}", mode, state.lookup_string("MODE"));
      let category = match state.current_token {
        Some(ref token) => token.to_string(),
        None => String::from("mode"),
      };
      Error!("unexpected", category, self, state, &message); // self.currentFrameMessage);
    } else {
      // Don"t pop if there"s an error; maybe we'll recover?
      self.pop_stack_frame(false, state)?;
    } // Effectively egroup.
    Ok(())
  }

  //**********************************************************************
}
