//! Build script for latexml_package.
//!
//! Emits `latex_dump_loader.rs` into OUT_DIR. The loader does NOT `include_str!`
//! the dump at compile time (old behavior). Instead, at runtime it reads the
//! dump from disk, searching several locations in order:
//!
//!   0. `$LATEXML_NODUMP` — if set, skip entirely (matches Perl `Package.pm` `LoadFormat` behavior:
//!      `if (!$ENV{LATEXML_NODUMP} && FindFile(...))`).
//!   1. `$LATEXML_DUMP_PATH` (explicit override, full path to latex.dump.txt)
//!   2. `$LATEXML_DUMP_DIR/latex.dump.txt` (directory override)
//!   3. `<exe_dir>/../resources/dumps/latex.dump.txt` (installed layout)
//!   4. The dev-tree path baked in at compile time
//!      (`$CARGO_MANIFEST_DIR/../resources/dumps/latex.dump.txt`).
//!
//! This decouples the dump from the binary:
//!
//! - The build never fails because the dump is missing — we just log at info and fall through to
//!   in-engine defaults.
//! - Regenerating the dump (`latexml_oxide --init=latex.ltx`) does **not** require a rebuild.
//!   Re-run tests / converts directly.
//! - Tests and CI can call `tools/make_formats.sh` (or run `--init`) before the test phase to
//!   guarantee a fresh dump against the ambient texlive.
//!
//! Rationale: Perl's workflow is `make formats` → tests. Embedding the dump
//! via `include_str!` locked us into a two-compile chicken-egg and froze the
//! dump at whatever texlive was present the day the file was committed. The
//! runtime-load path is the "--init earlier" design SYNC_STATUS D0 calls for.

use std::env;
use std::path::Path;

const STUB: &str = r#"// No-op kernel dump loader fallback.
// Real loader is generated by build.rs into OUT_DIR/latex_dump_loader.rs.

pub fn load_definitions() -> latexml_core::common::error::Result<()> {
  Ok(())
}
"#;

fn main() {
  let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
  let out_dir = env::var("OUT_DIR").unwrap();
  // Engine modules are now at the crate root (latexml_engine/src/) since
  // the latexml_engine extraction. Previously this was src/engine/ when
  // the engine lived under latexml_package.
  let engine_dir = Path::new(&manifest_dir).join("src");
  let dumps_dir = Path::new(&manifest_dir).join("../resources/dumps");

  // Ensure both dump module files exist (Perl: plain_dump + latex_dump).
  // These just `include!` the generated loader from OUT_DIR.
  for dump_name in &["latex_dump.rs", "plain_dump.rs"] {
    let dump_path = engine_dir.join(dump_name);
    if !dump_path.exists() {
      std::fs::write(&dump_path, STUB)
        .unwrap_or_else(|_| panic!("Failed to write {dump_name} stub"));
    }
    println!("cargo:rerun-if-changed=src/{dump_name}");
  }

  // Emit the runtime-load loader. No dump content is embedded.
  let loader_path = Path::new(&out_dir).join("latex_dump_loader.rs");
  let default_dev_path = dumps_dir.join("latex.dump.txt");
  let default_dev_path_str = default_dev_path.to_string_lossy().replace('\\', "\\\\");

  let loader = format!(
    r##"// Runtime kernel-dump loader. Generated by `latexml_package/build.rs`.
//
// Searches for `latex.dump.txt` at runtime (see build.rs for the path list).
// If found, ingests it via `dump_reader::load_from_str`. If not found, logs
// at info and returns Ok(()) — the engine will fall back to in-code defaults.

pub fn load_definitions() -> latexml_core::common::error::Result<()> {{
  // Perl parity: Package.pm `LoadFormat` skips the dump when LATEXML_NODUMP
  // is set, falling back to re-processing the _base pool. We don't have a
  // fully separate _base path yet (see SYNC_STATUS D0) but we still respect
  // the opt-out so tooling can force the slower path deterministically.
  if std::env::var_os("LATEXML_NODUMP").is_some() {{
    log::info!("[latex_dump] LATEXML_NODUMP set — skipping dump, engine will \
                reconstruct kernel state from _base pool (slower, Perl-parity)");
    return Ok(());
  }}
  let path_opt = resolve_dump_path();
  let Some(path) = path_opt else {{
    log::info!("[latex_dump] no dump found (checked $LATEXML_DUMP_PATH, $LATEXML_DUMP_DIR, \
                exe-relative, and dev-tree path); run `latexml_oxide --init=latex.ltx` to generate");
    return Ok(());
  }};
  let content = match std::fs::read_to_string(&path) {{
    Ok(c) => c,
    Err(e) => {{
      log::warn!("[latex_dump] failed to read {{}}: {{}}", path.display(), e);
      return Ok(());
    }}
  }};
  // Staleness check: compare the dump's texlive.version stamp against
  // ambient kpsewhich --version. Mismatch means the dump was generated
  // against a different TeXLive; engine may see unfamiliar macro state.
  // Opt out with LATEXML_SKIP_DUMP_STAMP_CHECK=1 (for e.g. cross-env CI).
  if std::env::var_os("LATEXML_SKIP_DUMP_STAMP_CHECK").is_none() {{
    check_dump_staleness(&path);
  }}
  // Conservative add-only load. The latex dump can't fully replace
  // `latex_base.rs` (closure-backed defs aren't serializable), so the
  // engine loads BOTH; `load_from_str` skips dump entries already
  // installed by `_base` rather than overwriting them. This is the
  // "transitional" mode — strict Perl would call
  // `load_from_str_plain` (unconditional `assign_internal('global')`)
  // but that requires `_base` closures be re-expressible through the
  // dump.
  let count = latexml_core::dump_reader::load_from_str(&content)
    .map_err(|e: String| -> latexml_core::common::error::Error {{ e.into() }})?;
  log::info!("[latex_dump] loaded {{}} entries from {{}}", count, path.display());
  Ok(())
}}

fn check_dump_staleness(dump_path: &std::path::Path) {{
  let stamp_path = dump_path.with_file_name("texlive.version");
  let stamp_first_line = std::fs::read_to_string(&stamp_path).ok()
    .and_then(|s| s.lines().next().map(|l| l.to_string()));
  let Some(stamp) = stamp_first_line else {{ return; }};
  let ambient = std::process::Command::new("kpsewhich")
    .arg("--version").output().ok()
    .and_then(|o| if o.status.success() {{
      String::from_utf8(o.stdout).ok()
        .and_then(|s| s.lines().next().map(|l| l.to_string()))
    }} else {{ None }});
  let Some(ambient) = ambient else {{ return; }};
  if stamp.trim() != ambient.trim() {{
    log::warn!("[latex_dump] TeXLive MISMATCH — dump stamped `{{}}`, ambient \
                kpsewhich `{{}}`. The dump may reference macros unknown to the \
                current TeXLive (or vice versa). Run `tools/make_formats.sh` \
                to regenerate against ambient texlive. Silence with \
                LATEXML_SKIP_DUMP_STAMP_CHECK=1.",
               stamp.trim(), ambient.trim());
  }}
}}

fn resolve_dump_path() -> Option<std::path::PathBuf> {{
  // 1. Explicit full path override.
  if let Ok(p) = std::env::var("LATEXML_DUMP_PATH") {{
    let pb = std::path::PathBuf::from(p);
    if pb.is_file() {{ return Some(pb); }}
  }}
  // 2. Directory override — look for latex.dump.txt inside.
  if let Ok(dir) = std::env::var("LATEXML_DUMP_DIR") {{
    let pb = std::path::Path::new(&dir).join("latex.dump.txt");
    if pb.is_file() {{ return Some(pb); }}
  }}
  // 3. Installed layout: <exe_dir>/../resources/dumps/latex.dump.txt.
  if let Ok(exe) = std::env::current_exe() {{
    if let Some(exe_dir) = exe.parent() {{
      let installed = exe_dir.join("../resources/dumps/latex.dump.txt");
      if installed.is_file() {{ return Some(installed); }}
      // Also check sibling (for test binaries at target/release/deps/).
      let sibling = exe_dir.join("latex.dump.txt");
      if sibling.is_file() {{ return Some(sibling); }}
    }}
  }}
  // 4. Dev-tree path baked in at compile time.
  let dev = std::path::PathBuf::from("{}");
  if dev.is_file() {{ return Some(dev); }}
  None
}}
"##,
    default_dev_path_str
  );

  std::fs::write(&loader_path, loader)
    .unwrap_or_else(|_| panic!("Failed to write latex_dump_loader.rs"));

  // Rerun if the dump file changes — even though we don't embed it, this
  // ensures builds that WERE stale by chance get a fresh mtime signal.
  println!("cargo:rerun-if-changed={}", default_dev_path.display());
  // Rerun if the texlive.version marker changes.
  let version_file = dumps_dir.join("texlive.version");
  println!("cargo:rerun-if-changed={}", version_file.display());

  // Also rerun if the environment override changes.
  println!("cargo:rerun-if-env-changed=LATEXML_DUMP_PATH");
  println!("cargo:rerun-if-env-changed=LATEXML_DUMP_DIR");
  println!("cargo:rerun-if-env-changed=LATEXML_NODUMP");

  println!("cargo:rerun-if-changed=build.rs");
}
