//! Build script for latexml_package.
//!
//! Checks if `src/engine/latex_dump.rs` contains a real dump (generated by
//! `latexml_oxide --init=latex.ltx`). If the file doesn't exist or is just
//! the stub, it generates a no-op stub.
//!
//! The dump is Rust-native: compiled directly into the binary as
//! state::assign_value / install_definition calls. No runtime parsing needed.
//! This is an intentional improvement over Perl's text-format dumps.

use std::env;
use std::path::Path;

fn main() {
  let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
  let dump_rs_path = Path::new(&manifest_dir).join("src/engine/latex_dump.rs");

  // If latex_dump.rs doesn't exist, create a no-op stub
  if !dump_rs_path.exists() {
    let stub = r#"//! No-op kernel dump (not yet generated).
//! Generate with: cargo run --release --bin latexml_oxide -- --init=latex.ltx
//! The engine will use classic runtime loading instead.

pub fn load_definitions() -> latexml_core::common::error::Result<()> {
  Ok(())
}
"#;
    std::fs::write(&dump_rs_path, stub).expect("Failed to write dump stub");
  }

  // Rerun if the dump source changes
  println!("cargo:rerun-if-changed=src/engine/latex_dump.rs");
  println!("cargo:rerun-if-changed=build.rs");
}
