//! Build script for latexml_package.
//!
//! Ensures `src/engine/latex_dump.rs` and `src/engine/plain_dump.rs` exist.
//! If either doesn't exist, generates a no-op stub (Perl parity: LoadFormat
//! falls back to _base pool when dump is missing).
//!
//! Real dumps are generated by `latexml_oxide --init=latex.ltx` and
//! `latexml_oxide --init=plain.tex`. The dumps use typed static data
//! tables — every entry is compiler-checked at build time.

use std::env;
use std::path::Path;

const STUB: &str = r#"// No-op kernel dump (not yet generated).
// Generate with: cargo run --release --bin latexml_oxide -- --init=latex.ltx
// The engine will use classic runtime loading instead.

pub fn load_definitions() -> latexml_core::common::error::Result<()> {
  Ok(())
}
"#;

fn main() {
  let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
  let out_dir = env::var("OUT_DIR").unwrap();
  let engine_dir = Path::new(&manifest_dir).join("src/engine");

  // Ensure both dump files exist (Perl: plain_dump + latex_dump)
  for dump_name in &["latex_dump.rs", "plain_dump.rs"] {
    let dump_path = engine_dir.join(dump_name);
    if !dump_path.exists() {
      std::fs::write(&dump_path, STUB).unwrap_or_else(|_| panic!("Failed to write {dump_name} stub"));
    }
    println!("cargo:rerun-if-changed=src/engine/{dump_name}");
  }

  // Ensure latex_dump_loader.rs exists in OUT_DIR (included by latex_dump.rs)
  let loader_path = Path::new(&out_dir).join("latex_dump_loader.rs");
  if !loader_path.exists() {
    std::fs::write(&loader_path, STUB).unwrap_or_else(|_| panic!("Failed to write latex_dump_loader.rs stub"));
  }

  println!("cargo:rerun-if-changed=build.rs");
}
