use crate::prelude::*;
LoadDefinitions!({
  // #======================================================================
  // # C.11.4 Splitting the input
  // #======================================================================
  Let!("\\@@input", "\\input"); // Save TeX's version.
  // LaTeX's \input is a bit different...

  // Input, now
  DefPrimitive!("\\ltx@input {}", sub[(arg)] { Input!(&Expand!(arg).to_string()); });
  DefMacro!("\\input", "\\@ifnextchar\\bgroup\\@iinput\\@@input");
  Let!("\\@iinput", "\\ltx@input");
  DefMacro!(
    "\\@input{}",
    "\\IfFileExists{#1}{\\@@input\\@filef@und}{\\typeout{No file #1.}}"
  );
  DefMacro!(
    "\\@input@{}",
    "\\InputIfFileExists{#1}{}{\\typeout{No file #1.}}"
  );

  DefMacro!("\\quote@name{}", "\"\\quote@@name#1\\@gobble\"\"");
  DefMacro!("\\quote@@name{} Match:\"", "#1\\quote@@name");
  DefMacro!("\\unquote@name{}", "\\quote@@name#1\\@gobble\"");

  // Perl L4313-4315: \include — input a file, respecting \includeonly
  DefPrimitive!("\\include{}", sub[(path)] {
    let path_str = Expand!(path).to_string();
    // Check if \includeonly restricts inclusion
    let table = state::lookup_value("including@only");
    let should_include = match table {
      None => true, // no \includeonly — include everything
      Some(Stored::HashString(map)) => map.contains_key(&path_str),
      _ => true,
    };
    if should_include {
      Input!(&path_str);
    }
  });

  // Perl L4303-4311: \includeonly — restrict which files \include loads
  DefPrimitive!("\\includeonly{}", sub[(paths)] {
    let paths_str = Expand!(paths).to_string();
    let mut map = rustc_hash::FxHashMap::default();
    for part in paths_str.split(',') {
      let trimmed = part.trim().to_string();
      if !trimmed.is_empty() {
        map.insert(trimmed, "1".to_string());
      }
    }
    state::assign_value("including@only", Stored::HashString(map), Scope::Global);
  });

  // Perl latex_constructs L4316-4353: {filecontents} and {filecontents*} environments
  // Read raw lines until \end{filecontents}, cache content for later \input.
  fn cache_filecontents(end_marker: &str, header_star: bool) -> Result<()> {
    gullet::skip_spaces()?;
    let filename_toks = gullet::read_arg(ExpansionLevel::Off)?;
    let filename = filename_toks.to_string();
    let mut lines: Vec<String> = vec![
      format!("%% LaTeX2e file `{filename}'"),
      if header_star {
        "%% generated by the `filecontents*' environment".to_string()
      } else {
        "%% generated by the `filecontents' environment".to_string()
      },
    ];
    if !header_star { lines.push("%%".to_string()); }
    // Discard remainder of \begin{filecontents} line
    gullet::read_raw_line();
    // Read raw lines until end marker
    loop {
      match gullet::read_raw_line() {
        Some(line) if !line.contains(end_marker) => lines.push(line),
        _ => break,
      }
    }
    let n = lines.len();
    let content = lines.join("\n");
    Info!("note", "filecontents", s!("Cached filecontents for {filename} ({n} lines)"));
    state::assign_value(&s!("{filename}_contents"), Stored::from(content), Some(Scope::Global));
    Ok(())
  }
  // Perl: DefConstructorI(T_CS("\\begin{filecontents}"), "Semiverbatim", '', afterDigest => ...)
  // The \filecontents primitive reads filename + raw lines until \end{filecontents}.
  // When called via \begin{filecontents}, \begin opens a group first.
  // We manually close the group after caching, matching the \end that was consumed.
  DefPrimitive!("\\filecontents", {
    cache_filecontents("\\end{filecontents}", false)?;
    // \begin{filecontents} opens a \begingroup; since we consumed \end{filecontents}
    // as raw text, we must close the group that \begin opened.
    stomach::endgroup()?;
  });
  DefPrimitive!("\\lx@filecontents@star", {
    cache_filecontents("\\end{filecontents*}", true)?;
    // Same: close the \begingroup from \begin{filecontents*}
    stomach::endgroup()?;
  });
  state::assign_meaning(
    &T_CS!("\\filecontents*"),
    state::lookup_meaning(&T_CS!("\\lx@filecontents@star")).unwrap_or(Stored::None),
    Some(Scope::Global),
  );
  DefMacro!("\\endfilecontents", "");
  state::assign_meaning(
    &T_CS!("\\endfilecontents*"),
    state::lookup_meaning(&T_CS!("\\endfilecontents")).unwrap_or(Stored::None),
    Some(Scope::Global),
  );
});
