//! Auto-generated LaTeX kernel dump loader.
//! Generated by dump_codegen. DO NOT EDIT.
//! Regenerate with: `latexml_oxide --init=latex.ltx` then `--codegen=...`

/// The embedded kernel dump data.
const DUMP_DATA: &str = include_str!("latex_dump.oxide");

/// Load the precompiled LaTeX kernel definitions into the global state.
/// This replaces processing latex.ltx at every test run.
pub fn load_definitions() -> latexml_core::common::error::Result<()> {
  latexml_core::dump_reader::load_from_str(DUMP_DATA)
    .map_err(|e| latexml_core::common::error::Error::from(e))?;
  Ok(())
}
