use crate::prelude::*;
LoadDefinitions!({
  // #======================================================================
  // # C.11.4 Splitting the input
  // #======================================================================
  Let!("\\@@input", "\\input"); // Save TeX's version.
  // LaTeX's \input is a bit different...

  // Input, now
  DefPrimitive!("\\ltx@input {}", sub[(arg)] { Input!(&Expand!(arg).to_string()); });
  DefMacro!("\\input", "\\@ifnextchar\\bgroup\\@iinput\\@@input");
  Let!("\\@iinput", "\\ltx@input");
  DefMacro!(
    "\\@input{}",
    "\\IfFileExists{#1}{\\@@input\\@filef@und}{\\typeout{No file #1.}}"
  );
  DefMacro!(
    "\\@input@{}",
    "\\InputIfFileExists{#1}{}{\\typeout{No file #1.}}"
  );

  DefMacro!("\\quote@name{}", "\"\\quote@@name#1\\@gobble\"\"");
  DefMacro!("\\quote@@name{} Match:\"", "#1\\quote@@name");
  DefMacro!("\\unquote@name{}", "\\quote@@name#1\\@gobble\"");

  // # Note that even excluded files SHOULD have the effects of their inclusion
  // # simulated by having read the corresponding aux file;
  // # But we're not bothering with that.
  // DefPrimitive('\include{}', sub {
  //     my ($stomach, $path) = @_;
  //     $path = ToString($path);
  //     my $table = LookupValue('including@only');
  //     if (!$table || $$table{$path}) {
  //       Input($path); }
  //     return; });

  // # [note, this will load name.tex, if it exists, else name]
  // DefPrimitive('\includeonly{}', sub {
  //     my ($stomach, $paths) = @_;
  //     $paths = ToString($paths);
  //     my $table = LookupValue('including@only');
  //     AssignValue('including@only', $table = {}, 'global') unless $table;
  //     map { $$table{$_} = 1 } map { /^\s*(.*?)\s*$/ && $1; } split(/,/, $paths);
  //     return; });

  // Perl latex_constructs L4316-4353: {filecontents} and {filecontents*} environments
  // Read raw lines until \end{filecontents}, cache content for later \input.
  fn cache_filecontents(end_marker: &str, header_star: bool) -> Result<()> {
    gullet::skip_spaces()?;
    let filename_toks = gullet::read_arg(ExpansionLevel::Off)?;
    let filename = filename_toks.to_string();
    let mut lines: Vec<String> = vec![
      format!("%% LaTeX2e file `{filename}'"),
      if header_star {
        "%% generated by the `filecontents*' environment".to_string()
      } else {
        "%% generated by the `filecontents' environment".to_string()
      },
    ];
    if !header_star { lines.push("%%".to_string()); }
    // Discard remainder of \begin{filecontents} line
    gullet::read_raw_line();
    // Read raw lines until end marker
    loop {
      match gullet::read_raw_line() {
        Some(line) if !line.contains(end_marker) => lines.push(line),
        _ => break,
      }
    }
    let n = lines.len();
    let content = lines.join("\n");
    Info!("note", "filecontents", s!("Cached filecontents for {filename} ({n} lines)"));
    state::assign_value(&s!("{filename}_contents"), Stored::from(content), Some(Scope::Global));
    Ok(())
  }
  DefPrimitive!("\\filecontents", {
    cache_filecontents("\\end{filecontents}", false)?;
  });
  // Star variant: \filecontents* (the * is part of the CS name)
  DefPrimitive!("\\lx@filecontents@star", {
    cache_filecontents("\\end{filecontents*}", true)?;
  });
  state::assign_meaning(
    &T_CS!("\\filecontents*"),
    state::lookup_meaning(&T_CS!("\\lx@filecontents@star")).unwrap_or(Stored::None),
    Some(Scope::Global),
  );
  DefMacro!("\\endfilecontents", "");
  state::assign_meaning(
    &T_CS!("\\endfilecontents*"),
    state::lookup_meaning(&T_CS!("\\endfilecontents")).unwrap_or(Stored::None),
    Some(Scope::Global),
  );
});
