//! Two compile-time tasks:
//!
//! 1. Bake the current git SHA into `LATEXML_GIT_SHA` so the telemetry
//!    module can include it in every per-job record. See
//!    `docs/TELEMETRY.md` §4 Step 5.
//!
//! 2. Walk `resources/RelaxNG/` and emit an `embedded_relaxng.rs`
//!    manifest in `OUT_DIR` that lists every schema file (.rng/.rnc/
//!    .model + the svg/ subtree) as `(relative_path, include_str!(absolute_path))`
//!    pairs. The runtime extracts these to a temp dir on first use so
//!    a single-binary distribution can run `--validate` and load
//!    compiled `.model` files without a `resources/` tree on disk.

use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
  // Re-run when the git ref moves (commit, checkout, etc.)
  println!("cargo:rerun-if-changed=../.git/HEAD");
  println!("cargo:rerun-if-changed=../.git/refs/heads");
  // Also re-run if the env override changes
  println!("cargo:rerun-if-env-changed=LATEXML_GIT_SHA_OVERRIDE");

  let sha = std::env::var("LATEXML_GIT_SHA_OVERRIDE")
    .ok()
    .or_else(|| {
      Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .and_then(|o| {
          if o.status.success() {
            String::from_utf8(o.stdout)
              .ok()
              .map(|s| s.trim().to_string())
          } else {
            None
          }
        })
    })
    .unwrap_or_default();

  println!("cargo:rustc-env=LATEXML_GIT_SHA={sha}");

  emit_embedded_relaxng();
}

/// Walk `../resources/RelaxNG/` and emit a manifest file that lists
/// every RelaxNG resource as `(rel_path, include_str!(abs_path))`.
/// Caller imports it via `include!(concat!(env!("OUT_DIR"), "/embedded_relaxng.rs"))`.
///
/// Paths are absolute so the generated file remains valid regardless
/// of where it gets included from. Forward slashes used in the manifest
/// keys for stable cross-platform lookup; the runtime joins them onto
/// the temp-dir root with `Path::join`.
fn emit_embedded_relaxng() {
  let crate_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
  let resource_root = crate_dir
    .parent()
    .expect("workspace root above crate dir")
    .join("resources")
    .join("RelaxNG");

  // Tell cargo to re-run this build script when any RelaxNG file
  // changes. Granular per-file is overkill; the directory hint is
  // enough — cargo invalidates whenever any descendant is touched.
  println!(
    "cargo:rerun-if-changed={}",
    resource_root.display()
  );

  let mut files: Vec<(String, PathBuf)> = Vec::new();
  collect_files(&resource_root, &resource_root, &mut files);
  files.sort_by(|a, b| a.0.cmp(&b.0));

  let mut out = String::with_capacity(files.len() * 200);
  out.push_str(
    "// Auto-generated by latexml_core/build.rs — do not edit.\n\
     pub static FILES: &[(&str, &str)] = &[\n",
  );
  for (rel, abs) in &files {
    out.push_str("  (\"");
    out.push_str(rel);
    out.push_str("\", include_str!(r\"");
    out.push_str(&abs.to_string_lossy());
    out.push_str("\")),\n");
  }
  out.push_str("];\n");

  let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
  std::fs::write(out_dir.join("embedded_relaxng.rs"), out)
    .expect("write embedded_relaxng.rs");
}

fn collect_files(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
  let Ok(entries) = std::fs::read_dir(dir) else {
    return;
  };
  for entry in entries.flatten() {
    let path = entry.path();
    if path.is_dir() {
      collect_files(root, &path, out);
    } else if path.is_file() {
      let rel = path.strip_prefix(root).expect("path under root");
      // Forward slashes — stable key shape regardless of host OS.
      let rel_str = rel
        .to_string_lossy()
        .replace(std::path::MAIN_SEPARATOR, "/");
      out.push((rel_str, path));
    }
  }
}
