use crate::prelude::*;
use latexml_core::common::color::from_model_components;

#[rustfmt::skip]
LoadDefinitions!({
  // Perl L20-30: \DefineNamedColor — defines a named color + \text<name> + \<name>.
  // Perl kind is DefMacro with an imperative sub body that returns no tokens;
  // Rust DefPrimitive is the stomach-level analogue. WISDOM #44: the two
  // kinds differ under `\edef`/`\ifx`/`\expandafter`; safe here because
  // `\DefineNamedColor` is invoked at document-preamble stomach time by
  // `\input{dvipsnam.def}`, never captured in an expansion context.
  // WISDOM #44 verified 2026-04-23: zero `\edef`/`\ifx`/`\expandafter`
  // uses of `\DefineNamedColor` across LaTeXML/lib + ar5iv-bindings.
  DefPrimitive!("\\DefineNamedColor{}{}{}{}", sub[(_dmodel, name, model, spec)] {
    let name_str = do_expand(name)?.to_string();
    let model_str = do_expand(model)?.to_string().trim().to_string();
    let spec_str = do_expand(spec)?.to_string();
    let spec_trimmed = spec_str.trim().trim_matches(|c| c == '{' || c == '}').trim().to_string();
    let model = if model_str.is_empty() { "cmyk".to_string() } else { model_str };
    let comps: Vec<f64> = if spec_trimmed.contains(',') {
      spec_trimmed.split(',').filter_map(|s| s.trim().parse().ok()).collect()
    } else {
      spec_trimmed.split_whitespace().filter_map(|s| s.parse().ok()).collect()
    };
    let color = from_model_components(&model, &comps);
    def_color(&name_str, &color, Some(Scope::Global))?;
    // Define \text<name> and \<name>{text} via RawTeX.
    //
    // Perl colordvi.sty.ltxml L28 defines `\text<name>` as a `DefPrimitive`
    // that calls `MergeFont(color => $color)` directly — so the package is
    // SELF-CONTAINED and does NOT require `color.sty` or `xcolor.sty` to
    // provide `\color`. Papers that only load `colordvi` (e.g. 0705.1190)
    // should still work.
    //
    // We achieve the same by routing `\text<name>` through the
    // `\lx@colordvi@setcolor` primitive below, which looks up the
    // previously-stored named color from the color registry and merges it
    // into the current font — no `\color` needed.
    // Perl L28-29: scope => 'global' on both \text<name> and \<name>.
    // Without it, named-color macros defined while colordvi loads inside
    // a TeX group (e.g. via \input nested under \begingroup) would
    // disappear at group close. Use \global\def to match Perl's global
    // scope semantics — the bare \def fallback is local by default.
    let text_def = s!(
      "\\global\\expandafter\\def\\csname text{}\\endcsname{{\\lx@colordvi@setcolor{{{}}}}}",
      name_str, name_str
    );
    let name_def = s!(
      "\\global\\expandafter\\def\\csname {}\\endcsname#1{{{{\\csname text{}\\endcsname #1}}}}",
      name_str, name_str
    );
    for def_str in [&text_def, &name_def] {
      let tokens = mouth::tokenize_internal(def_str);
      gullet::do_expand(tokens)?;
    }
    Ok(Vec::new())
  });

  // Internal primitive: look up a named color in the registry and merge
  // it into the current font. Used by `\text<name>` macros generated by
  // `\DefineNamedColor` so colordvi works WITHOUT `color.sty`/`xcolor.sty`.
  DefPrimitive!("\\lx@colordvi@setcolor{}", sub[(name_arg)] {
    let name_str = do_expand(name_arg)?.to_string();
    let color = crate::package::color_sty::lookup_color_obj(&name_str);
    MergeFont!(color => color);
    Ok(Vec::new())
  });

  // Perl L34-37: \background — sets background color
  DefPrimitive!("\\background{}", sub[(color_arg)] {
    let color_str = do_expand(color_arg)?.to_string();
    let color = crate::package::color_sty::lookup_color_obj(&color_str);
    MergeFont!(bg => color);
    Ok(Vec::new())
  });

  DefMacro!("\\subdef{}", "");

  // Perl L42-53: \textColor — set color from CMYK spec
  DefPrimitive!("\\textColor{}", sub[(cmyk_arg)] {
    let cmyk_str = do_expand(cmyk_arg)?.to_string();
    let spec = cmyk_str.trim().trim_matches(|c| c == '{' || c == '}').trim().to_string();
    let comps: Vec<f64> = if spec.contains(',') {
      spec.split(',').filter_map(|s| s.trim().parse().ok()).collect()
    } else {
      spec.split_whitespace().filter_map(|s| s.parse().ok()).collect()
    };
    let color = from_model_components("cmyk", &comps);
    if state::lookup_bool_sym(pin!("inPreamble")) {
      assign_value("preambleTextcolor", Stored::String(arena::pin(color.to_stored())), None);
    }
    MergeFont!(color => color);
    Ok(Vec::new())
  });

  // Perl L56: \Color{CMYK}{text}
  DefMacro!("\\Color{}{}", "{\\textColor{#1} #2}");

  // Perl L61-63: \newColor — stub with warning
  DefPrimitive!("\\newColor{}", sub[(name)] {
    let name_str = name.to_string();
    Warn!("unexpected", "newColor", &s!("Ignoring definition of \\newColor {}", name_str));
    Ok(Vec::new())
  });

  // Perl L66: load DVI color definitions
  InputDefinitions!("dvipsnam", extension => Some(Cow::Borrowed("def")));
});
