use crate::prelude::*;

#[rustfmt::skip]
LoadDefinitions!({
  RequirePackage!("amsbsy");
  RequirePackage!("amsgen");
  RequirePackage!("amssymb");
  RequirePackage!("amsfonts");
  DefMacro!("\\balpha",      "\\boldsymbol{\\alpha}");
  DefMacro!("\\bbeta",       "\\boldsymbol{\\beta}");
  DefMacro!("\\bgamma",      "\\boldsymbol{\\gamma}");
  DefMacro!("\\bdelta",      "\\boldsymbol{\\delta}");
  DefMacro!("\\bepsilon",    "\\boldsymbol{\\epsilon}");
  DefMacro!("\\bzeta",       "\\boldsymbol{\\zeta}");
  DefMacro!("\\bfeta",       "\\boldsymbol{\\eta}");
  DefMacro!("\\btheta",      "\\boldsymbol{\\theta}");
  DefMacro!("\\biota",       "\\boldsymbol{\\iota}");
  DefMacro!("\\bkappa",      "\\boldsymbol{\\kappa}");
  DefMacro!("\\blambda",     "\\boldsymbol{\\lambda}");
  DefMacro!("\\bmu",         "\\boldsymbol{\\mu}");
  DefMacro!("\\bnu",         "\\boldsymbol{\\nu}");
  DefMacro!("\\bxi",         "\\boldsymbol{\\xi}");
  DefMacro!("\\bpi",         "\\boldsymbol{\\pi}");
  DefMacro!("\\brho",        "\\boldsymbol{\\rho}");
  DefMacro!("\\bsigma",      "\\boldsymbol{\\sigma}");
  DefMacro!("\\btau",        "\\boldsymbol{\\tau}");
  DefMacro!("\\bupsilon",    "\\boldsymbol{\\upsilon}");
  DefMacro!("\\bphi",        "\\boldsymbol{\\phi}");
  DefMacro!("\\bchi",        "\\boldsymbol{\\chi}");
  DefMacro!("\\bpsi",        "\\boldsymbol{\\psi}");
  DefMacro!("\\bomega",      "\\boldsymbol{\\omega}");
  DefMacro!("\\bvarepsilon", "\\boldsymbol{\\varepsilon}");
  DefMacro!("\\bvartheta",   "\\boldsymbol{\\vartheta}");
  DefMacro!("\\bvaromega",   "\\boldsymbol{\\varomega}");
  DefMacro!("\\bvarymega",   "\\boldsymbol{\\varomega}");
  DefMacro!("\\bvarrho",     "\\boldsymbol{\\varrho}");
  DefMacro!("\\bvarzeta",    "\\boldsymbol{\\varsigma}");
  DefMacro!("\\bvarsigma",   "\\boldsymbol{\\varsigma}");
  DefMacro!("\\bvarphi",     "\\boldsymbol{\\varphi}");
  DefMacro!("\\bGamma",   "\\boldsymbol{\\Gamma}");
  DefMacro!("\\bDelta",   "\\boldsymbol{\\Delta}");
  DefMacro!("\\bTheta",   "\\boldsymbol{\\Theta}");
  DefMacro!("\\bLambda",  "\\boldsymbol{\\Lambda}");
  DefMacro!("\\bXi",      "\\boldsymbol{\\Xi}");
  DefMacro!("\\bPi",      "\\boldsymbol{\\Pi}");
  DefMacro!("\\bSigma",   "\\boldsymbol{\\Sigma}");
  DefMacro!("\\bUpsilon", "\\boldsymbol{\\Upsilon}");
  DefMacro!("\\bPhi",     "\\boldsymbol{\\Phi}");
  DefMacro!("\\bPsi",     "\\boldsymbol{\\Psi}");
  DefMacro!("\\bOmega",   "\\boldsymbol{\\Omega}");
  DefMacro!("\\bpartial", "\\boldsymbol{\\partial}");
  DefMacro!("\\bell",     "\\boldsymbol{\\ell}");
  DefMacro!("\\bimath",   "\\boldsymbol{\\imath}");
  DefMacro!("\\bjmath",   "\\boldsymbol{\\jmath}");
  DefMacro!("\\binfty",   "\\boldsymbol{\\infty}");
  DefMacro!("\\bnabla",   "\\boldsymbol{\\nabla}");
  DefMacro!("\\bdot",     "\\boldsymbol{\\cdot}");
  DefPrimitive!(T_CS!("\\opencircle"),       None, "\u{25CB}",);
  DefPrimitive!(T_CS!("\\opensquare"),       None, "\u{25A1}",);
  DefPrimitive!(T_CS!("\\opentriangle"),     None, "\u{25B3}",);
  DefPrimitive!(T_CS!("\\opentriangledown"), None, "\u{25BD}",);
  DefPrimitive!(T_CS!("\\opendiamond"),      None, "\u{25C7}",);
  DefPrimitive!(T_CS!("\\fullcircle"),       None, "\u{25CF}",);
  DefPrimitive!(T_CS!("\\fullsquare"),       None, "\u{25A0}",);
  DefPrimitive!(T_CS!("\\fulldiamond"),      None, "\u{25C6}",);
  DefPrimitive!(T_CS!("\\fullstar"),         None, "\u{2605}",);
  DefPrimitive!(T_CS!("\\fulltriangle"),     None, "\u{25B2}",);
  DefPrimitive!(T_CS!("\\fulltriangledown"), None, "\u{25BC}",);
});
