//! LAE font encoding: arabi's Arabic font encoding (laeenc.def).
//!
//! Each slot decodes to the character its glyph shows in the encoding's default font (aealmohanadb, laecmr.fd), as the font's
//! encoding vector `fonts/enc/dvips/arabi/ararabeyes.enc` names it (generated by `tools/arabi_fontmap_tables.py`). A letter's slot holds one of its
//! contextual forms (the font's ligature program picks the others while setting); every form decodes to the
//! letter itself, which the browser shapes again. A ligature decodes to its letters (`\llahchar`, set after
//! `\alef`: lam lam shadda heh). The font draws for right-to-left setting: a slot holding the mirror image of a
//! Bidi_Mirrored character (`(` holds `parenright`, `<` `guillemotright`) decodes to the logical character, which
//! the bidi algorithm mirrors again on display; the font's `/` slot holds a backslash, which Unicode does not
//! mirror, and decodes to the typed `/`. Perl has no LAE map: the encoding falls back to OT1 and the letters
//! decode to nothing (OXIDIZED_DESIGN_DIVERGENCES #415). Witness: arabi/samplebook.
use crate::prelude::*;

LoadDefinitions!({
  #[rustfmt::skip]
  DeclareFontMap!("LAE", mixrc![
    // 0x00: alefisolated alefwithhamzaaboveisolated alefwithhamzaabovefinal
    //   alefwithhamzabelowisolated
    Some('\u{0627}'), Some('\u{0623}'), Some('\u{0623}'), Some('\u{0625}'),
    // 0x04: alefwithhamzabelowfinal alefwithmaddaaboveisolated alefwithmaddaabovefinal behinitial
    Some('\u{0625}'), Some('\u{0622}'), Some('\u{0622}'), Some('\u{0628}'),
    // 0x08: .notdef behfinal behisolated tehinitial
    None, Some('\u{0628}'), Some('\u{0628}'), Some('\u{062A}'),
    // 0x0C: .notdef tehfinal tehisolated thehinitial
    None, Some('\u{062A}'), Some('\u{062A}'), Some('\u{062B}'),
    // 0x10: thehmedial thehfinal thehisolated jeeminitial
    Some('\u{062B}'), Some('\u{062B}'), Some('\u{062B}'), Some('\u{062C}'),
    // 0x14: jeemmedial jeemfinal jeemisolated hahinitial
    Some('\u{062C}'), Some('\u{062C}'), Some('\u{062C}'), Some('\u{062D}'),
    // 0x18: hahmedial hahfinal hahisolated khahinitial
    Some('\u{062D}'), Some('\u{062D}'), Some('\u{062D}'), Some('\u{062E}'),
    // 0x1C: khahmedial khahfinal khahisolated .notdef
    Some('\u{062E}'), Some('\u{062E}'), Some('\u{062E}'), None,
    // 0x20: dal exclam sukun numbersign
    Some('\u{062F}'), Some('\u{0021}'), Some('\u{0652}'), Some('\u{0023}'),
    // 0x24: dollar arabicpercentsign ampersand quotesingle
    Some('\u{0024}'), Some('\u{066A}'), Some('\u{0026}'), Some('\u{0027}'),
    // 0x28: parenright parenleft arabicfivepointedstar quotedbl
    Some('\u{0028}'), Some('\u{0029}'), Some('\u{066D}'), Some('\u{0022}'),
    // 0x2C: arabiccomma hyphenminus period backslash
    Some('\u{060C}'), Some('\u{002D}'), Some('\u{002E}'), Some('\u{002F}'),
    // 0x30: arabicindicdigitzero arabicindicdigitone arabicindicdigittwo arabicindicdigitthree
    Some('\u{0660}'), Some('\u{0661}'), Some('\u{0662}'), Some('\u{0663}'),
    // 0x34: arabicindicdigitfour arabicindicdigitfive arabicindicdigitsix arabicindicdigitseven
    Some('\u{0664}'), Some('\u{0665}'), Some('\u{0666}'), Some('\u{0667}'),
    // 0x38: arabicindicdigiteight arabicindicdigitnine colon arabicsemicolon
    Some('\u{0668}'), Some('\u{0669}'), Some('\u{003A}'), Some('\u{061B}'),
    // 0x3C: guillemotright .notdef guillemotleft arabicquestionmark
    Some('\u{00AB}'), None, Some('\u{00BB}'), Some('\u{061F}'),
    // 0x40: thalfinal aleffinal .notdef rehisolated
    Some('\u{0630}'), Some('\u{0627}'), None, Some('\u{0631}'),
    // 0x44: .nodef zainisolated seeninitial .notdef
    None, Some('\u{0632}'), Some('\u{0633}'), None,
    // 0x48: seenfinal yehmedial sheeninitial sheenmedial
    Some('\u{0633}'), Some('\u{064A}'), Some('\u{0634}'), Some('\u{0634}'),
    // 0x4C: sheenfinal sheenisolated .notdef sadmedial
    Some('\u{0634}'), Some('\u{0634}'), None, Some('\u{0635}'),
    // 0x50: sadfinal sadisolated dadinitial dadmedial
    Some('\u{0635}'), Some('\u{0635}'), Some('\u{0636}'), Some('\u{0636}'),
    // 0x54: tehmarbutafinal wawfinal tahinitial tahmedial
    Some('\u{0629}'), Some('\u{0648}'), Some('\u{0637}'), Some('\u{0637}'),
    // 0x58: tahfinal alefmaksurafinal zahinitial ornaterightparenthesis
    Some('\u{0637}'), Some('\u{0649}'), Some('\u{0638}'), Some('\u{FD3F}'),
    // 0x5C: zahmedial ornateleftparenthesis zahfinal zahisolated
    Some('\u{0638}'), Some('\u{FD3E}'), Some('\u{0638}'), Some('\u{0638}'),
    // 0x60: ainmedial fathah behmedial .notdef
    Some('\u{0639}'), Some('\u{064E}'), Some('\u{0628}'), None,
    // 0x64: dalfinal .notdef fehmedial .notdef
    Some('\u{062F}'), None, Some('\u{0641}'), None,
    // 0x68: hehmedial kasrah .notdef kafmedial
    Some('\u{0647}'), Some('\u{0650}'), None, Some('\u{0643}'),
    // 0x6C: lammedial meemmedial noonmedial .notdef
    Some('\u{0644}'), Some('\u{0645}'), Some('\u{0646}'), None,
    // 0x70: pehmedial qafmedial rehfinal seenmedial
    Some('\u{067E}'), Some('\u{0642}'), Some('\u{0631}'), Some('\u{0633}'),
    // 0x74: tehmedial dammah .notdef wawfinal
    Some('\u{062A}'), Some('\u{064F}'), None, Some('\u{0648}'),
    // 0x78: seenisolated yehmedial zainfinal dadfinal
    Some('\u{0633}'), Some('\u{064A}'), Some('\u{0632}'), Some('\u{0636}'),
    // 0x7C: dadisolated sadinitial .notdef .notdef
    Some('\u{0636}'), Some('\u{0635}'), None, None,
    // 0x80: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0x84: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0x88: aininitial ainfinal ainisolated ghaininitial
    Some('\u{0639}'), Some('\u{0639}'), Some('\u{0639}'), Some('\u{063A}'),
    // 0x8C: ghainmedial ghainfinal ghainisolated fehinitial
    Some('\u{063A}'), Some('\u{063A}'), Some('\u{063A}'), Some('\u{0641}'),
    // 0x90: fehfinal fehisolated qafinitial qaffinal
    Some('\u{0641}'), Some('\u{0641}'), Some('\u{0642}'), Some('\u{0642}'),
    // 0x94: qafisolated kafinitial arabickaffinal kafisolated
    Some('\u{0642}'), Some('\u{0643}'), Some('\u{0643}'), Some('\u{0643}'),
    // 0x98: laminitial lamfinal lamisolated meeminitial
    Some('\u{0644}'), Some('\u{0644}'), Some('\u{0644}'), Some('\u{0645}'),
    // 0x9C: meemfinal meemisolated nooninitial noonfinal
    Some('\u{0645}'), Some('\u{0645}'), Some('\u{0646}'), Some('\u{0646}'),
    // 0xA0: noonisolated hehinitial hehfinal hehisolated
    Some('\u{0646}'), Some('\u{0647}'), Some('\u{0647}'), Some('\u{0647}'),
    // 0xA4: wawisolated wawwithhamzaabovefinal wawwithhamzaaboveisolated yehinitial
    Some('\u{0648}'), Some('\u{0624}'), Some('\u{0624}'), Some('\u{064A}'),
    // 0xA8: yehfinal yehisolated tahisolated alefmaksuraisolated
    Some('\u{064A}'), Some('\u{064A}'), Some('\u{0637}'), Some('\u{0649}'),
    // 0xAC: .notdef tehmarbutaisolated lamwithaleffinal lamwithalefisolated
    None, Some('\u{0629}'), None, None,
    // 0xB0: lamwithalefhamzaabovefinal lamwithalefhamzaaboveisolatedd lamwithalefhamzabelowfinal
    //   lamwithalefhamzabelowisolated
    None, None, None, None,
    // 0xB4: lamwithalefmaddaabovefinal lamwithalefmaddaaboveisolatedd yehwithhamzaaboveinitial
    //   yehwithhamzaabovemedial
    None, None, Some('\u{0626}'), Some('\u{0626}'),
    // 0xB8: yehwithhamzaabovefinal yehwithhamzaaboveisolated hamzaisolated .notdef
    Some('\u{0626}'), Some('\u{0626}'), Some('\u{0621}'), None,
    // 0xBC: .notdef .notdef fathatan dammatan
    None, None, Some('\u{064B}'), Some('\u{064C}'),
    // 0xC0: kasratan fathah dammah kasrah
    Some('\u{064D}'), Some('\u{064E}'), Some('\u{064F}'), Some('\u{0650}'),
    // 0xC4: shaddah sukun .notdef .notdef
    Some('\u{0651}'), Some('\u{0652}'), None, None,
    // 0xC8: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xCC: shaddah .notdef .notdef .notdef
    Some('\u{0651}'), None, None, None,
    // 0xD0: thalisolated .notdef .notdef .notdef
    Some('\u{0630}'), None, None, None,
    // 0xD4: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xD8: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xDC: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xE0: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xE4: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xE8: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xEC: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xF0: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xF4: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xF8: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xFC: allahisolated mhmd tatweel sallallahou
    None, None, Some('\u{0640}'), None
  ]);
  #[rustfmt::skip]
  DeclareFontMapMultichar!("LAE", {
    0xAEu8 => "\u{0644}\u{0627}", // lamwithaleffinal
    0xAFu8 => "\u{0644}\u{0627}", // lamwithalefisolated
    0xB0u8 => "\u{0644}\u{0623}", // lamwithalefhamzaabovefinal
    0xB1u8 => "\u{0644}\u{0623}", // lamwithalefhamzaaboveisolatedd
    0xB2u8 => "\u{0644}\u{0625}", // lamwithalefhamzabelowfinal
    0xB3u8 => "\u{0644}\u{0625}", // lamwithalefhamzabelowisolated
    0xB4u8 => "\u{0644}\u{0622}", // lamwithalefmaddaabovefinal
    0xB5u8 => "\u{0644}\u{0622}", // lamwithalefmaddaaboveisolatedd
    0xFCu8 => "\u{0644}\u{0644}\u{0651}\u{0647}", // allahisolated: lam lam shadda heh, `\alef\llahchar` = الله
    0xFDu8 => "\u{0645}\u{062D}\u{0645}\u{062F}", // mhmd
    0xFFu8 => "\u{0635}\u{0644}\u{0649}\u{0020}\u{0627}\u{0644}\u{0644}\u{0647}\u{0020}\u{0639}\u{0644}\u{064A}\u{0647}\u{0020}\u{0648}\u{0633}\u{0644}\u{0645}",
  });
});
