//! LFE font encoding: arabi's Farsi font encoding (lfeenc.def).
//!
//! Each slot decodes to the character its glyph shows in the encoding's default font (nazli, lfecmr.fd), as the font's
//! encoding vector `fonts/enc/dvips/arabi/farsiwebencoding.enc` names it (generated by `tools/arabi_fontmap_tables.py`). A letter's slot holds one of its
//! contextual forms (the font's ligature program picks the others while setting); every form decodes to the
//! letter itself, which the browser shapes again. A ligature decodes to its letters (`\llahchar`, set after
//! `\alef`: lam lam shadda heh). The font draws for right-to-left setting: a slot holding the mirror image of a
//! Bidi_Mirrored character (`(` holds `parenright`, `<` `guillemotright`) decodes to the logical character, which
//! the bidi algorithm mirrors again on display. Perl has no LFE map: the encoding falls back to OT1 and the
//! letters decode to nothing (OXIDIZED_DESIGN_DIVERGENCES #415). Witness: arabi/samplebook.
//! `\alefmaqsura`'s slot holds the Farsi yeh glyph and decodes to it.
use crate::prelude::*;

LoadDefinitions!({
  #[rustfmt::skip]
  DeclareFontMap!("LFE", mixrc![
    // 0x00: afii57415.isol afii57411.isol afii57411.fina afii57413.isol
    Some('\u{0627}'), Some('\u{0623}'), Some('\u{0623}'), Some('\u{0625}'),
    // 0x04: afii57413.fina afii57410.isol afii57410.fina afii57416.init
    Some('\u{0625}'), Some('\u{0622}'), Some('\u{0622}'), Some('\u{0628}'),
    // 0x08: .notdef afii57416.fina afii57416.isol afii57418.init
    None, Some('\u{0628}'), Some('\u{0628}'), Some('\u{062A}'),
    // 0x0C: .notdef afii57418.fina afii57418.isol afii57419.init
    None, Some('\u{062A}'), Some('\u{062A}'), Some('\u{062B}'),
    // 0x10: afii57419.medi afii57419.fina afii57419.isol afii57420.init
    Some('\u{062B}'), Some('\u{062B}'), Some('\u{062B}'), Some('\u{062C}'),
    // 0x14: afii57420.medi afii57420.fina afii57420.isol afii57421.init
    Some('\u{062C}'), Some('\u{062C}'), Some('\u{062C}'), Some('\u{062D}'),
    // 0x18: afii57421.medi afii57421.fina afii57421.isol afii57422.init
    Some('\u{062D}'), Some('\u{062D}'), Some('\u{062D}'), Some('\u{062E}'),
    // 0x1C: afii57422.medi afii57422.fina afii57422.isol .notdef
    Some('\u{062E}'), Some('\u{062E}'), Some('\u{062E}'), None,
    // 0x20: afii57423.isol exclam afii57458 numbersign
    Some('\u{062F}'), Some('\u{0021}'), Some('\u{0652}'), Some('\u{0023}'),
    // 0x24: dollar afii57381 ampersand quotesingle
    Some('\u{0024}'), Some('\u{066A}'), Some('\u{0026}'), Some('\u{0027}'),
    // 0x28: parenright parenleft asterisk quotedbl
    Some('\u{0028}'), Some('\u{0029}'), Some('\u{002A}'), Some('\u{0022}'),
    // 0x2C: afii57388 hyphen period slash
    Some('\u{060C}'), Some('\u{002D}'), Some('\u{002E}'), Some('\u{002F}'),
    // 0x30: uni06F0 uni06F1 uni06F2 uni06F3
    Some('\u{06F0}'), Some('\u{06F1}'), Some('\u{06F2}'), Some('\u{06F3}'),
    // 0x34: uni06F4 uni06F5 uni06F6 uni06F7
    Some('\u{06F4}'), Some('\u{06F5}'), Some('\u{06F6}'), Some('\u{06F7}'),
    // 0x38: uni06F8 uni06F9 colon afii57403
    Some('\u{06F8}'), Some('\u{06F9}'), Some('\u{003A}'), Some('\u{061B}'),
    // 0x3C: guillemotright .notdef guillemotleft afii57407
    Some('\u{00AB}'), None, Some('\u{00BB}'), Some('\u{061F}'),
    // 0x40: afii57424.fina afii57415.fina .notdef afii57425.isol
    Some('\u{0630}'), Some('\u{0627}'), None, Some('\u{0631}'),
    // 0x44: .nodef afii57426.isol afii57427.init .notdef
    None, Some('\u{0632}'), Some('\u{0633}'), None,
    // 0x48: afii57427.fina uni06CC.media afii57428.init afii57428.medi
    Some('\u{0633}'), Some('\u{06CC}'), Some('\u{0634}'), Some('\u{0634}'),
    // 0x4C: afii57428.fina afii57428.isol .notdef afii57429.medi
    Some('\u{0634}'), Some('\u{0634}'), None, Some('\u{0635}'),
    // 0x50: afii57429.fina afii57429.isol afii57430.init afii57430.medi
    Some('\u{0635}'), Some('\u{0635}'), Some('\u{0636}'), Some('\u{0636}'),
    // 0x54: afii57417.fina afii57448.fina afii57431.init afii57431.medi
    Some('\u{0629}'), Some('\u{0648}'), Some('\u{0637}'), Some('\u{0637}'),
    // 0x58: afii57431.fina uni06CC.fina afii57432.init bracketright
    Some('\u{0637}'), Some('\u{06CC}'), Some('\u{0638}'), Some('\u{005B}'),
    // 0x5C: afii57432.medi bracketleft afii57432.fina afii57432.isol
    Some('\u{0638}'), Some('\u{005D}'), Some('\u{0638}'), Some('\u{0638}'),
    // 0x60: afii57433.medi afii57454 afii57416.medi afii57507.medi
    Some('\u{0639}'), Some('\u{064E}'), Some('\u{0628}'), Some('\u{0686}'),
    // 0x64: afii57423.fina .notdef afii57441.medi afii57509.medi
    Some('\u{062F}'), None, Some('\u{0641}'), Some('\u{06AF}'),
    // 0x68: afii57470.medi afii57456 .notdef uni06A9.medi
    Some('\u{0647}'), Some('\u{0650}'), None, Some('\u{06A9}'),
    // 0x6C: afii57444.medi afii57445.medi afii57446.medi .notdef
    Some('\u{0644}'), Some('\u{0645}'), Some('\u{0646}'), None,
    // 0x70: afii57506.medi afii57442.medi afii57425.fina afii57427.medi
    Some('\u{067E}'), Some('\u{0642}'), Some('\u{0631}'), Some('\u{0633}'),
    // 0x74: afii57418.medi afii57455 .notdef afii57448.fina
    Some('\u{062A}'), Some('\u{064F}'), None, Some('\u{0648}'),
    // 0x78: afii57427.isol uni06CC.medi afii57426.fina afii57430.fina
    Some('\u{0633}'), Some('\u{06CC}'), Some('\u{0632}'), Some('\u{0636}'),
    // 0x7C: afii57430.isol afii57429.init .notdef .notdef
    Some('\u{0636}'), Some('\u{0635}'), None, None,
    // 0x80: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0x84: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0x88: afii57433.init afii57433.fina afii57433.isol afii57434.init
    Some('\u{0639}'), Some('\u{0639}'), Some('\u{0639}'), Some('\u{063A}'),
    // 0x8C: afii57434.medi afii57434.fina afii57434.isol afii57441.init
    Some('\u{063A}'), Some('\u{063A}'), Some('\u{063A}'), Some('\u{0641}'),
    // 0x90: afii57441.fina afii57441.isol afii57442.init afii57442.fina
    Some('\u{0641}'), Some('\u{0641}'), Some('\u{0642}'), Some('\u{0642}'),
    // 0x94: afii57442.isol uni06A9.init uni06A9.fina uni06A9.isol
    Some('\u{0642}'), Some('\u{06A9}'), Some('\u{06A9}'), Some('\u{06A9}'),
    // 0x98: afii57444.init afii57444.fina afii57444.isol afii57445.init
    Some('\u{0644}'), Some('\u{0644}'), Some('\u{0644}'), Some('\u{0645}'),
    // 0x9C: afii57445.fina afii57445.isol afii57446.init afii57446.fina
    Some('\u{0645}'), Some('\u{0645}'), Some('\u{0646}'), Some('\u{0646}'),
    // 0xA0: afii57446.isol afii57470.init afii57470.fina afii57470.isol
    Some('\u{0646}'), Some('\u{0647}'), Some('\u{0647}'), Some('\u{0647}'),
    // 0xA4: afii57448.isol afii57412.fina afii57412.isol uni06CC.init
    Some('\u{0648}'), Some('\u{0624}'), Some('\u{0624}'), Some('\u{06CC}'),
    // 0xA8: uni06CC.fina uni06CC.isol afii57431.isol .notdef
    Some('\u{06CC}'), Some('\u{06CC}'), Some('\u{0637}'), None,
    // 0xAC: .notdef afii57417.isol afii57444_afii57415.fina afii57444_afii57415.isol
    None, Some('\u{0629}'), None, None,
    // 0xB0: afii57444_afii57411.fina afii57444_afii57411.isol afii57444_afii57413.fina
    //   afii57444_afii57413.isol
    None, None, None, None,
    // 0xB4: afii57444_afii57410.fina afii57444_afii57410.isol afii57414.init afii57414.medi
    None, None, Some('\u{0626}'), Some('\u{0626}'),
    // 0xB8: afii57414.fina afii57414.isol afii57409 .notdef
    Some('\u{0626}'), Some('\u{0626}'), Some('\u{0621}'), None,
    // 0xBC: .notdef .notdef afii57451 afii57452
    None, None, Some('\u{064B}'), Some('\u{064C}'),
    // 0xC0: afii57453 afii57454 afii57455 afii57456
    Some('\u{064D}'), Some('\u{064E}'), Some('\u{064F}'), Some('\u{0650}'),
    // 0xC4: afii57457 afii57458 afii57457_afii57451 afii57457_afii57452
    Some('\u{0651}'), Some('\u{0652}'), None, None,
    // 0xC8: afii57457_afii57453 afii57457_afii57454 afii57457_afii57455 afii57457_afii57456
    None, None, None, None,
    // 0xCC: afii57457 afii57457_afii57454 afii57457_afii57455 afii57457_afii57456
    Some('\u{0651}'), None, None, None,
    // 0xD0: afii57424.isol afii57508.fina afii57508.isol afii57506.init
    Some('\u{0630}'), Some('\u{0698}'), Some('\u{0698}'), Some('\u{067E}'),
    // 0xD4: afii57506.fina afii57506.isol afii57509.init afii57509.fina
    Some('\u{067E}'), Some('\u{067E}'), Some('\u{06AF}'), Some('\u{06AF}'),
    // 0xD8: afii57509.isol afii57507.init afii57507.fina afii57507.isol
    Some('\u{06AF}'), Some('\u{0686}'), Some('\u{0686}'), Some('\u{0686}'),
    // 0xDC: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xE0: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xE4: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xE8: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xEC: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xF0: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xF4: .notdef .notdef .notdef .notdef
    None, None, None, None,
    // 0xF8: .notdef .notdef uni066C uni066B
    None, None, Some('\u{066C}'), Some('\u{066B}'),
    // 0xFC: uni0644064406510647 uniFDFC afii57440 .notdef
    None, None, Some('\u{0640}'), None
  ]);
  #[rustfmt::skip]
  DeclareFontMapMultichar!("LFE", {
    0xAEu8 => "\u{0644}\u{0627}", // afii57444_afii57415.fina
    0xAFu8 => "\u{0644}\u{0627}", // afii57444_afii57415.isol
    0xB0u8 => "\u{0644}\u{0623}", // afii57444_afii57411.fina
    0xB1u8 => "\u{0644}\u{0623}", // afii57444_afii57411.isol
    0xB2u8 => "\u{0644}\u{0625}", // afii57444_afii57413.fina
    0xB3u8 => "\u{0644}\u{0625}", // afii57444_afii57413.isol
    0xB4u8 => "\u{0644}\u{0622}", // afii57444_afii57410.fina
    0xB5u8 => "\u{0644}\u{0622}", // afii57444_afii57410.isol
    0xC6u8 => "\u{0651}\u{064B}", // afii57457_afii57451
    0xC7u8 => "\u{0651}\u{064C}", // afii57457_afii57452
    0xC8u8 => "\u{0651}\u{064D}", // afii57457_afii57453
    0xC9u8 => "\u{0651}\u{064E}", // afii57457_afii57454
    0xCAu8 => "\u{0651}\u{064F}", // afii57457_afii57455
    0xCBu8 => "\u{0651}\u{0650}", // afii57457_afii57456
    0xCDu8 => "\u{0651}\u{064E}", // afii57457_afii57454
    0xCEu8 => "\u{0651}\u{064F}", // afii57457_afii57455
    0xCFu8 => "\u{0651}\u{0650}", // afii57457_afii57456
    0xFCu8 => "\u{0644}\u{0644}\u{0651}\u{0647}", // uni0644064406510647
    0xFDu8 => "\u{0631}\u{06CC}\u{0627}\u{0644}", // uniFDFC
  });
});
