//! Binding definitions for the `LaTeXML` converter, reimplemented in Rust
#![recursion_limit = "1024"]

#[macro_use]
extern crate latexml_codegen;
// re-export small auxiliary macros
#[macro_use]
pub mod macros;
// Prelude for writing bindings
#[macro_use]
pub mod prelude;
// The TeX/LaTeX/eTeX/PdfTeX kernels
#[macro_use]
pub mod engine;
// Supported LaTeX packages
#[macro_use]
pub mod package;

// TODO: This entire file may be better left generated by latexml_codegen at compile time?
// that way it will always be dynamically updated based on the files in
//  latexml_package/src/package
use latexml_core::common::error::Result;
pub fn dispatch(filename: &str) -> Option<Result<()>> {
  Some(match filename {
    "TeX.pool" => engine::tex::load_definitions(),
    "LaTeX.pool" => engine::latex::load_definitions(),
    "eTeX.pool" => engine::etex::load_definitions(),
    "pdfTeX.pool" => engine::pdftex::load_definitions(),
    "latexml.sty" => package::latexml_sty::load_definitions(),
    "article.cls" => package::article_cls::load_definitions(),
    "alltt.sty" => package::alltt_sty::load_definitions(),
    "appendix.sty" => package::appendix_sty::load_definitions(),
    "book.cls" => package::book_cls::load_definitions(),
    "booktabs.sty" => package::booktabs_sty::load_definitions(),
    "caption.sty" => package::caption_sty::load_definitions(),
    "remreset.sty" => package::remreset_sty::load_definitions(),
    "report.cls" => package::report_cls::load_definitions(),
    "amsmath.sty" => package::amsmath_sty::load_definitions(),
    "amsfonts.sty" => package::amsfonts_sty::load_definitions(),
    "amssymb.sty" => package::amssymb_sty::load_definitions(),
    "amsthm.sty" => package::amsthm_sty::load_definitions(),
    "theorem.sty" => package::theorem_sty::load_definitions(),
    "ntheorem.sty" => package::ntheorem_sty::load_definitions(),
    "amsbsy.sty" => package::amsbsy_sty::load_definitions(),
    "amsgen.sty" => package::amsgen_sty::load_definitions(),
    "fancyhdr.sty" => package::fancyhdr_sty::load_definitions(),
    "fullpage.sty" => package::fullpage_sty::load_definitions(),
    "comment.sty" => package::comment_sty::load_definitions(),
    "endnotes.sty" => package::endnotes_sty::load_definitions(),
    "IEEEtran.cls" => package::ieeetran_cls::load_definitions(),
    "url.sty" => package::url_sty::load_definitions(),
    "xargs.sty" => package::xargs_sty::load_definitions(),
    "etoolbox.sty" => package::etoolbox_sty::load_definitions(),
    "hyperref.sty" => package::hyperref_sty::load_definitions(),
    "nameref.sty" => package::nameref_sty::load_definitions(),
    "verbatim.sty" => package::verbatim_sty::load_definitions(),
    "fontenc.sty" => package::fontenc_sty::load_definitions(),
    "inputenc.sty" => package::inputenc_sty::load_definitions(),
    "textcomp.sty" => package::textcomp_sty::load_definitions(),
    "multicol.sty" => package::multicol_sty::load_definitions(),
    "multido.sty" => package::multido_sty::load_definitions(),
    "t1enc.sty" => package::t1enc_def::load_definitions(),
    "t1enc.def" => package::t1enc_sty::load_definitions(),
    "t1.fontmap" => package::t1_fontmap::load_definitions(),
    "utf8.def" => package::utf8_def::load_definitions(),
    "textcase.sty" => package::textcase_sty::load_definitions(),
    "cite.sty" => package::cite_sty::load_definitions(),
    "calc.sty" => package::calc_sty::load_definitions(),
    "chngcntr.sty" => package::chngcntr_sty::load_definitions(),
    _other => return None,
  })
}
