//! XSLT `LATEXML_VERSION` generator-stamp: parity with Perl (`LaTeXML.pm:562`) + BookML.
//!
//! Perl LaTeXML always passes its `$LaTeXML::VERSION` as the XSLT `LATEXML_VERSION`
//! parameter, so `resources/XSLT/LaTeXML-common.xsl`'s `LaTeXML_identifier` template
//! emits the `<!--Generated by LaTeXML (version X) http://dlmf.nist.gov/LaTeXML/.-->`
//! stamp into the HTML head/footer. oxide historically left the param unset, so the
//! `<xsl:if test="$LATEXML_VERSION">` was false and the stamp was silently omitted — a
//! parity gap, and BookML's `utils.xsl` `b:version-leq($LATEXML_VERSION,…)` saw an
//! empty string. We now inject `core_interface::LATEXML_VERSION` (our OWN Cargo
//! `X.Y.Z`, see #320) as the default, overridable via `--xsltparameter`.
//!
//! End-to-end only: the in-process `Converter` stops at Core XML; the XSLT chain runs
//! solely through the binary (`--dest *.html`), like the `07/08/09_xslt_*` tests.

use std::{path::Path, process::Command};

use latexml::core_interface::LATEXML_VERSION;

fn run(cwd: &Path, args: &[&str]) -> std::process::Output {
  Command::new(env!("CARGO_BIN_EXE_latexml_oxide"))
    .args(args)
    .current_dir(cwd)
    .output()
    .expect("spawn latexml_oxide")
}

const DOC: &str = "\\documentclass{article}\n\\begin{document}\nHello.\n\\end{document}\n";

/// Default HTML output carries the generator stamp with OUR crate version (parity with
/// Perl `LaTeXML.pm:562`; BookML's `$LATEXML_VERSION` becomes non-empty).
#[test]
fn generator_stamp_carries_our_version() {
  let work = tempfile::tempdir().expect("tempdir");
  std::fs::write(work.path().join("v.tex"), DOC).unwrap();
  let out = run(work.path(), &["v.tex", "--dest", "v.html"]);
  assert!(
    out.status.success(),
    "conversion failed (status {:?}):\n{}",
    out.status.code(),
    String::from_utf8_lossy(&out.stderr)
  );
  let html = std::fs::read_to_string(work.path().join("v.html")).expect("read v.html");
  let expected = format!("by LaTeXML (version {LATEXML_VERSION})");
  assert!(
    html.contains(&expected),
    "generator stamp missing OUR version; expected substring {expected:?} in the \
     <!--Generated…--> comment (is the LATEXML_VERSION XSLT param injected?):\n{html}"
  );
}

/// A user `--xsltparameter LATEXML_VERSION=<x>` overrides the injected default. This is
/// the mechanism Perl's own test suite uses (via `LATEXML_VERSION:TEST`) to keep golden
/// HTML version-independent (`LaTeXML.pm:574-576`; the `daemon/formats/citation.xml`
/// Perl golden shows `version TEST`). Confirms the default does not shadow an explicit
/// param — the override loop runs last in `post.rs`.
#[test]
fn xsltparameter_overrides_generator_version() {
  let work = tempfile::tempdir().expect("tempdir");
  std::fs::write(work.path().join("v.tex"), DOC).unwrap();
  let out = run(work.path(), &[
    "v.tex",
    "--dest",
    "v.html",
    "--xsltparameter",
    "LATEXML_VERSION=9.9.9-probe",
  ]);
  assert!(
    out.status.success(),
    "conversion failed:\n{}",
    String::from_utf8_lossy(&out.stderr)
  );
  let html = std::fs::read_to_string(work.path().join("v.html")).expect("read v.html");
  assert!(
    html.contains("by LaTeXML (version 9.9.9-probe)"),
    "explicit --xsltparameter LATEXML_VERSION did not win:\n{html}"
  );
  assert!(
    !html.contains(&format!("version {LATEXML_VERSION})")),
    "override did not replace the injected default version:\n{html}"
  );
}
