//! Embedded RelaxNG schema tree — bundled at compile time so a
//! single-binary distribution can serve compiled `.model` files and
//! `.rng` schemas without an accompanying `resources/RelaxNG/` tree
//! on disk.
//!
//! The manifest is generated by `latexml_core/build.rs`, which walks
//! `resources/RelaxNG/` and emits a static array of `(relative_path,
//! file_content)` pairs. On first call, [`ensure_extracted`] writes
//! every entry to a process-wide temp directory, preserving the
//! `svg/` subdirectory shape so that URN-based includes
//! (`urn:x-LaTeXML:RelaxNG:svg:svg11.rng` → `svg/svg11.rng`) resolve
//! against the extracted root the same way they did against the
//! source tree.
//!
//! Used by:
//! * `Model::load_schema` — fallback after `pathname::find` returns
//!   None, so the runtime can locate the compiled `LaTeXML.model`.
//! * `relaxng::scan::find_file` — fallback for unresolved schema
//!   `<include>` / `<externalRef>` references.

use std::path::PathBuf;
use std::sync::OnceLock;

use crate::util::cache_dir;

include!(concat!(env!("OUT_DIR"), "/embedded_relaxng.rs"));

static EXTRACTED_DIR: OnceLock<Option<PathBuf>> = OnceLock::new();

/// Materialize every embedded RelaxNG file to the user's cache directory
/// (`~/.cache/latexml_oxide/relaxng/` by default; see
/// [`cache_dir::for_subdir`]) and return its path. Returns `None` if no
/// writable cache location could be found, in which case schema-driven
/// features (`--validate`, `--schemadocs`) fall back to whatever paths
/// the caller's search list points at.
///
/// libxml2's RelaxNG validator and the schema-docs generator resolve
/// `<include>` / `<externalRef>` directives through the filesystem, so
/// the tree has to live somewhere on disk. Using the cache dir over
/// `/tmp` lets the extraction survive reboots (skipping the writes on
/// subsequent runs — content is idempotent across the binary's lifetime)
/// and stays per-user on shared hosts.
///
/// Only called from the `--validate` / `--schemadocs` paths; ordinary
/// HTML conversion never touches this — the runtime schema model is
/// baked into the binary by `latexml_codegen::modelable` at compile time.
pub fn ensure_extracted() -> Option<PathBuf> {
  EXTRACTED_DIR
    .get_or_init(|| {
      let dir = match cache_dir::for_subdir("relaxng") {
        Some(d) => d,
        None => {
          eprintln!(
            "latexml_oxide: no writable cache directory for embedded RelaxNG extraction",
          );
          return None;
        },
      };
      for (rel, content) in FILES {
        let path = dir.join(rel);
        if let Some(parent) = path.parent() {
          if let Err(e) = std::fs::create_dir_all(parent) {
            eprintln!(
              "latexml_oxide: failed to create embedded-RelaxNG subdir {}: {e}",
              parent.display(),
            );
            return None;
          }
        }
        // Skip the write when the on-disk content already matches —
        // RelaxNG is 108 files, so this avoids ~108 stat+write
        // syscalls per run after the first.
        if std::fs::read(&path)
          .map(|existing| existing.as_slice() == content.as_bytes())
          .unwrap_or(false)
        {
          continue;
        }
        if let Err(e) = std::fs::write(&path, content) {
          eprintln!(
            "latexml_oxide: failed to write embedded RelaxNG file {}: {e}",
            path.display(),
          );
          return None;
        }
      }
      Some(dir)
    })
    .clone()
}
